import type { FlatSpec } from "../../../lib/flatten.ts";
import { pascalCase } from "../../../lib/pascal-case.ts";

/** Workspace README for `@teseor/contract`. Lists every component's exported
 *  types and shows a representative deep-import example using the first spec. */
export function renderReadme(specs: FlatSpec[]): string {
  const componentList = specs
    .map((spec) => {
      const Name = pascalCase(spec.name);
      const exports: string[] = [];
      if (spec.variants) exports.push(`\`${Name}Variant\``);
      if (spec.intents) exports.push(`\`${Name}Intent\``);
      if (spec.sizes) exports.push(`\`${Name}Size\``);
      exports.push(`\`${Name}Props\``);
      return `- \`${Name}\` — ${exports.join(", ")}`;
    })
    .join("\n");

  const firstSpec = specs[0];
  const exampleName = firstSpec ? pascalCase(firstSpec.name) : "Button";

  return `<!-- AUTOGENERATED by gen-contract. Do not edit. -->

# @teseor/contract

Framework-agnostic TypeScript type contracts for Teseor components. Generated from \`specs/*.yaml\`.

The React wrapper (\`@teseor/react\`) inlines its own type unions for self-containment; this package is the canonical type surface for consumers integrating Teseor in non-React TypeScript codebases (or in framework-agnostic tooling).

## Install

\`\`\`
pnpm add @teseor/contract
\`\`\`

## Usage

\`\`\`ts
import type { ${exampleName}Props } from "@teseor/contract/${exampleName}.ts";

function buildAttrs(props: ${exampleName}Props): Record<string, string | undefined> {
  return { "data-variant": props.variant, "data-intent": props.intent };
}
\`\`\`

## Types

${componentList}

## Generated content

Files in \`src/\` are autogenerated from \`specs/*.yaml\`. Do not edit them. The generator is \`codegen/src/generators/gen-contract.ts\`.
`;
}
