import { type Breakpoint, breakpointNames } from "../../../lib/breakpoints.ts";
import { quote } from "../_shared/type-printer.ts";

/** Workspace-level `Responsive<T>` helper module. Lists every breakpoint key
 *  plus `base`, so prop types like `Responsive<ButtonVariant>` widen to
 *  `T | Partial<Record<Breakpoint, T>>`. */
export function renderResponsiveModule(breakpoints: Breakpoint[]): string {
  const keys = ["base", ...breakpointNames(breakpoints)].map(quote).join(" | ");
  return `// AUTOGENERATED by gen-contract. Do not edit.

type Breakpoint = ${keys};

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;
`;
}
