import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderAtomicVueWrapper } from "./atomic.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

function atomicSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "button",
    kind: "atomic",
    props: {},
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

/** Build a static-tag `root` descriptor, optionally polymorphic. */
function staticRoot(tag: string, polymorphic?: "asChild"): Spec["root"] {
  return polymorphic ? { kind: "static", tag, polymorphic } : { kind: "static", tag };
}

describe("renderAtomicVueWrapper", () => {
  test("opens with the AUTOGENERATED banner and the spec source comment", () => {
    const out = renderAtomicVueWrapper(atomicSpec(), {});
    expect(out).toContain("<!-- AUTOGENERATED by gen-vue. Do not edit. -->");
    expect(out).toContain("<!-- Source: specs/button.yaml -->");
  });

  test("imports the per-component CSS module", () => {
    const out = renderAtomicVueWrapper(atomicSpec(), {});
    expect(out).toContain(`import "@teseor/css/components/button.css";`);
  });

  test("uses the spec's `root` tag for the root element when no `as` prop exists", () => {
    const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("span") }), {});
    expect(out).toContain(`<span class="t-button" v-bind="attrs">`);
    expect(out).toContain("</span>");
  });

  test('switches to `<component :is="as">` when an `as` prop is declared', () => {
    const out = renderAtomicVueWrapper(
      atomicSpec({ props: { as: prop({ type: "string", default: "button" }) } }),
      {},
    );
    expect(out).toContain(`<component :is="as" class="t-button" v-bind="attrs">`);
    expect(out).toContain("</component>");
  });

  test("imports the responsive runtime helpers only when there's a responsive prop", () => {
    const noResp = renderAtomicVueWrapper(atomicSpec(), {});
    expect(noResp).not.toContain("responsiveDataAttrs");

    const withResp = renderAtomicVueWrapper(atomicSpec({ sizes: { md: { description: "" } } }), {});
    expect(withResp).toContain(
      `import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";`,
    );
  });

  test("wraps `<slot />` in slotElement when set", () => {
    const out = renderAtomicVueWrapper(
      atomicSpec({ name: "codeblock", root: staticRoot("pre"), slotElement: "code" }),
      {},
    );
    expect(out).toContain("<pre");
    expect(out).toContain("<code>");
    expect(out).toContain("<slot");
    expect(out).toContain("</code>");
  });

  test("omits the slot wrapper when slotElement is unset", () => {
    const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("div") }), {});
    expect(out).not.toContain("<code>");
  });

  describe("polymorphic: 'asChild'", () => {
    test("imports Slot, adds the asChild prop, and switches root via `:is`", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("div", "asChild") }), {});
      expect(out).toContain(`import { Slot } from "./components/Slot.ts";`);
      expect(out).toContain("asChild?: boolean;");
      expect(out).toContain(
        `<component :is="asChild ? Slot : 'div'" class="t-button" v-bind="attrs">`,
      );
      expect(out).toContain("</component>");
    });

    test("includes asChild in the defineProps destructure", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("div", "asChild") }), {});
      expect(out).toMatch(/const\s*\{[^}]*\basChild\b[^}]*\}\s*=\s*defineProps/s);
    });

    test("omits Slot import and asChild prop when polymorphic is unset", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("div") }), {});
      expect(out).not.toContain(`import { Slot }`);
      expect(out).not.toContain("asChild?: boolean;");
    });
  });

  describe("byProp root", () => {
    function headingSpec(polymorphic?: "asChild", props?: Spec["props"]): Spec {
      return atomicSpec({
        name: "heading",
        root: {
          kind: "byProp",
          prop: "level",
          map: { "1": "h1", "2": "h2", "3": "h3" },
          ...(polymorphic ? { polymorphic } : {}),
        },
        props: props ?? {
          level: prop({ type: "string", values: ["1", "2", "3"], default: "1" }),
        },
      });
    }

    test("emits a tagMap constant and a `:is` expression keyed by the prop", () => {
      const out = renderAtomicVueWrapper(headingSpec(), {});
      expect(out).toContain(`const tagMap = { "1": "h1", "2": "h2", "3": "h3" } as const;`);
      expect(out).toContain(`<component :is="tagMap[level ?? '1']"`);
      expect(out).toContain("</component>");
    });

    test("falls back to the first map key when the prop has no `default`", () => {
      const out = renderAtomicVueWrapper(
        headingSpec(undefined, {
          level: prop({ type: "string", values: ["1", "2", "3"] }),
        }),
        {},
      );
      expect(out).toContain(`<component :is="tagMap[level ?? '1']"`);
    });

    test("composes with `polymorphic: 'asChild'`", () => {
      const out = renderAtomicVueWrapper(headingSpec("asChild"), {});
      expect(out).toContain(`const tagMap =`);
      expect(out).toContain(`<component :is="asChild ? Slot : tagMap[level ?? '1']"`);
    });

    test("omits tagMap when the root is static", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ root: staticRoot("div") }), {});
      expect(out).not.toContain("const tagMap");
    });

    describe("mixed byProp map (void + non-void)", () => {
      function dividerSpec(polymorphic?: "asChild"): Spec {
        return atomicSpec({
          name: "divider",
          root: {
            kind: "byProp",
            prop: "orientation",
            map: { horizontal: "hr", vertical: "div" },
            ...(polymorphic ? { polymorphic } : {}),
          },
          props: {
            orientation: prop({
              type: "string",
              values: ["horizontal", "vertical"],
              default: "horizontal",
            }),
          },
        });
      }

      test("emits resolvedTag + isVoidResolved computeds derived from the tagMap", () => {
        const out = renderAtomicVueWrapper(dividerSpec(), {});
        expect(out).toContain(`const tagMap = { "horizontal": "hr", "vertical": "div" } as const;`);
        expect(out).toContain(
          `const resolvedTag = computed(() => tagMap[orientation ?? 'horizontal']);`,
        );
        expect(out).toContain(`const isVoidResolved = computed(() => resolvedTag.value === 'hr');`);
      });

      test("branches the template on isVoidResolved with v-if / v-else", () => {
        const out = renderAtomicVueWrapper(dividerSpec(), {});
        expect(out).toContain(`<template v-if="isVoidResolved">`);
        expect(out).toContain(`<template v-else>`);
        expect(out).toContain(`<component :is="resolvedTag" class="t-divider" v-bind="attrs" />`);
        expect(out).toContain(`<component :is="resolvedTag" class="t-divider" v-bind="attrs">`);
        expect(out).toContain("</component>");
      });

      test("guards asChild on the non-void branch so Slot never wraps a void tag", () => {
        const out = renderAtomicVueWrapper(dividerSpec("asChild"), {});
        expect(out).toContain(`asChild && !isVoidResolved ? Slot : resolvedTag`);
      });
    });

    describe("boolean state props", () => {
      test("emits a `data-{name}` entry on the attrs object for boolean state props", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            root: staticRoot("div"),
            props: {
              decorative: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).toContain(`"data-decorative": decorative ? "true" : undefined,`);
      });

      test("does not emit a data-* entry for the byProp controlling prop", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            root: {
              kind: "byProp",
              prop: "ordered",
              map: { false: "ul", true: "ol" },
            },
            props: {
              ordered: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).not.toContain(`"data-ordered":`);
      });
    });

    describe("htmlAttrs", () => {
      test("emits each entry in the attrs computed object", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            name: "switch",
            root: staticRoot("input"),
            htmlAttrs: { type: "checkbox" },
          }),
          {},
        );
        expect(out).toContain(`"type": "checkbox",`);
      });

      test("emits no static attribute entries when htmlAttrs is unset", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({ name: "input", root: staticRoot("input") }),
          {},
        );
        expect(out).not.toContain(`"type": "checkbox",`);
      });

      test("emits multiple entries", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            name: "image",
            root: staticRoot("img"),
            htmlAttrs: { loading: "lazy", decoding: "async" },
          }),
          {},
        );
        expect(out).toContain(`"loading": "lazy",`);
        expect(out).toContain(`"decoding": "async",`);
      });
    });

    describe("imperativeProps", () => {
      test("emits useTemplateRef + watch + ref attr when a DOM property is declared", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            name: "checkbox",
            root: staticRoot("input"),
            imperativeProps: { indeterminate: { type: "boolean" } },
          }),
          {},
        );
        expect(out).toContain(`import { computed, useTemplateRef, watch, type VNode } from "vue";`);
        expect(out).toContain(
          `const rootRef = useTemplateRef<HTMLElementTagNameMap['input']>("rootRef");`,
        );
        expect(out).toContain(
          `watch(() => indeterminate, (value) => {\n  if (rootRef.value) rootRef.value.indeterminate = value ?? false;\n}, { immediate: true, flush: "post" });`,
        );
        expect(out).toContain(`ref="rootRef"`);
      });

      test("does not emit the imperative-prop block when none are declared", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({ name: "switch", root: staticRoot("input") }),
          {},
        );
        expect(out).not.toContain("useTemplateRef");
        expect(out).not.toContain(`ref="rootRef"`);
        expect(out).not.toContain("watch(");
      });

      test("declares each imperative prop as an optional boolean on PropsType", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            name: "checkbox",
            root: staticRoot("input"),
            imperativeProps: {
              indeterminate: { type: "boolean", description: "Mixed state." },
            },
          }),
          {},
        );
        expect(out).toContain(`/** Mixed state. */\n  indeterminate?: boolean;`);
      });
    });

    describe("a11y emission", () => {
      test("emits a static role on the root from spec.a11y.role", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({ root: staticRoot("div"), a11y: { role: "separator" } }),
          {},
        );
        expect(out).toContain(`role: "separator",`);
      });

      test('forwards each ariaProps entry as `"aria-{prop}": prop`', () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            root: staticRoot("div"),
            props: {
              orientation: prop({
                type: "string",
                values: ["horizontal", "vertical"],
                responsive: false,
                description: "",
              }),
            },
            a11y: { ariaProps: ["orientation"] },
          }),
          {},
        );
        expect(out).toContain(`"aria-orientation": orientation,`);
      });

      test("toggles role to none and adds aria-hidden when decorativeProp is set", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            root: staticRoot("div"),
            props: { decorative: prop({ type: "boolean", description: "" }) },
            a11y: { role: "separator", decorativeProp: "decorative" },
          }),
          {},
        );
        expect(out).toContain(`role: decorative ? "none" : "separator",`);
        expect(out).toContain(`"aria-hidden": decorative ? "true" : undefined,`);
      });
    });
  });
});
