import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderCompositeOverlayVueWrapper } from "./composite-overlay.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

const OVERLAY = {
  anchor: "trigger",
  anchorVar: "--t-anchor",
  mode: "manual" as const,
  modal: false,
};

function tooltipSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "tooltip",
    kind: "composite",
    description: "Floating panel.",
    parts: {
      trigger: { fromChildren: true },
      content: { element: "div", a11y: { role: "tooltip" }, overlay: OVERLAY },
    },
    props: {
      open: prop({ type: "boolean", pattern: "controllable" }),
      text: prop({ type: "string", slot: true, __part: "content" }),
    },
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderCompositeOverlayVueWrapper", () => {
  test("emits an SFC banner with the spec source", () => {
    const out = renderCompositeOverlayVueWrapper(tooltipSpec(), {});
    expect(out).toContain("<!-- AUTOGENERATED by gen-vue. Do not edit. -->");
    expect(out).toContain("<!-- Source: specs/tooltip.yaml -->");
  });

  test("wires the useOverlay composable with the controllable prop name", () => {
    const out = renderCompositeOverlayVueWrapper(tooltipSpec(), {});
    expect(out).toContain("const overlay = useOverlay({");
    expect(out).toContain("open: () => openProp,");
    expect(out).toContain("defaultOpen,");
    expect(out).toContain("onOpenChange,");
  });

  test("throws when no `pattern: controllable` boolean prop is declared", () => {
    const spec = tooltipSpec({
      props: { text: prop({ type: "string", slot: true, __part: "content" }) },
    });
    expect(() => renderCompositeOverlayVueWrapper(spec, {})).toThrow(/pattern: controllable/);
  });

  test("uses the trigger part's rootClass when declared", () => {
    const spec = tooltipSpec({
      parts: {
        trigger: { fromChildren: true, rootClass: "custom-trigger" },
        content: { element: "div", a11y: { role: "tooltip" }, overlay: OVERLAY },
      },
    });
    const out = renderCompositeOverlayVueWrapper(spec, {});
    expect(out).toContain(`class="custom-trigger"`);
  });

  test("exposes contentRef via defineExpose so consumers can read the popover DOM", () => {
    const out = renderCompositeOverlayVueWrapper(tooltipSpec(), {});
    expect(out).toContain("defineExpose({ contentRef });");
    expect(out).toMatch(/const contentRef = overlay\.contentRef;\n[^\n]*\ndefineExpose/);
  });

  test("wraps the floating element in <Teleport> for modal dialogs", () => {
    const spec = tooltipSpec({
      parts: {
        trigger: { fromChildren: true },
        content: {
          element: "div",
          a11y: { role: "dialog" },
          overlay: { ...OVERLAY, modal: true },
        },
      },
    });
    const out = renderCompositeOverlayVueWrapper(spec, {});
    expect(out).toContain(`<Teleport to="body">`);
    expect(out).toContain("</Teleport>");
    expect(out).toContain(`aria-modal="true"`);
  });
});
