export function renderContractHarness(): string {
  return `// AUTOGENERATED by gen-tests. Do not edit.

import { expect, test, type Page } from "@playwright/test";

type ContractTestOptions = {
  component: string;
  rootClass: string;
  fixtureIds: readonly string[];
};

async function capture(
  page: Page,
  component: string,
  rootClass: string,
  framework: "react" | "vue",
  fixture: string,
): Promise<string> {
  await page.goto(\`/\${framework}/\${component}?fixture=\${fixture}\`);
  await page.locator(\`.\${rootClass}\`).first().waitFor({ state: "attached" });
  return page.evaluate((selector) => {
    function canon(el: Element): string {
      const tag = el.tagName.toLowerCase();
      const attrs = Array.from(el.attributes)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((a) => {
          const v = a.value.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
          return \`\${a.name}="\${v}"\`;
        })
        .join(" ");
      const open = attrs ? \`<\${tag} \${attrs}>\` : \`<\${tag}>\`;
      const close = \`</\${tag}>\`;
      const children = Array.from(el.childNodes)
        .map((node) => {
          if (node.nodeType === 1) return canon(node as Element);
          if (node.nodeType === 3) {
            const text = node.textContent ?? "";
            return text.trim() === "" ? "" : text;
          }
          return "";
        })
        .join("");
      return \`\${open}\${children}\${close}\`;
    }
    const root = document.querySelector(selector);
    if (!root) throw new Error(\`harness: selector "\${selector}" not found\`);
    return canon(root);
  }, \`.\${rootClass}\`);
}

export function defineContractTests(options: ContractTestOptions): void {
  const { component, rootClass, fixtureIds } = options;

  for (const id of fixtureIds) {
    test(\`\${component} "\${id}" — React and Vue render identical DOM\`, async ({ page }) => {
      const reactHtml = await capture(page, component, rootClass, "react", id);
      const vueHtml = await capture(page, component, rootClass, "vue", id);
      expect(vueHtml).toBe(reactHtml);
    });
  }

  test(\`\${component} — combined DOM snapshot\`, async ({ page }) => {
    const sections: string[] = [];
    for (const id of fixtureIds) {
      const reactHtml = await capture(page, component, rootClass, "react", id);
      sections.push(\`<!-- \${id} -->\\n\${reactHtml}\`);
    }
    expect(\`\${sections.join("\\n\\n")}\\n\`).toMatchSnapshot(\`\${component}.html\`);
  });
}
`;
}
