import { pascalCase } from "../../../lib/pascal-case.ts";

export function renderReactBarrel(names: string[]): string {
  const imports = names
    .map((n) => `import { fixtures as ${n}Fixtures } from "./${pascalCase(n)}.react.tsx";`)
    .join("\n");
  const entries = names.map((n) => `  ${n}: ${n}Fixtures,`).join("\n");
  return `// AUTOGENERATED by gen-tests. Do not edit.

import type { ReactNode } from "react";
${imports}

export const reactFixtures: Record<string, Record<string, () => ReactNode>> = {
${entries}
};
`;
}
