"pkg: css":
  - changed-files:
      - any-glob-to-any-file:
          - packages/css/**

"pkg: docgen":
  - changed-files:
      - any-glob-to-any-file:
          - packages/docgen/**

"type: ci":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

"type: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/*.md"

"component: button":
  - changed-files:
      - any-glob-to-any-file:
          - packages/css/src/components/actions/button/**

"component: card":
  - changed-files:
      - any-glob-to-any-file:
          - packages/css/src/components/data-display/card/**

"component: layout":
  - changed-files:
      - any-glob-to-any-file:
          - packages/css/src/layout/**
