import { describe, expect, test } from "vitest";
import { renderCssShim } from "./css-shim.ts";

describe("renderCssShim", () => {
  test("starts with the AUTOGENERATED banner", () => {
    expect(renderCssShim().split("\n")[0]).toBe("// AUTOGENERATED by gen-react. Do not edit.");
  });

  test('declares the wildcard CSS module so `import "…css"` typechecks', () => {
    expect(renderCssShim()).toContain('declare module "*.css";');
  });

  test("ends with a trailing newline", () => {
    expect(renderCssShim().endsWith("\n")).toBe(true);
  });

  test("renders identically on repeated calls", () => {
    expect(renderCssShim()).toBe(renderCssShim());
  });
});
