import { pascalCase } from "../../../lib/pascal-case.ts";

/** Workspace barrel that re-exports every component's `<Name>Props` type so
 *  consumers can `import { ModalProps } from "@teseor/contract"`. Matches the
 *  package.json `exports["."]` mapping; deep imports
 *  (`@teseor/contract/Modal.ts`) keep working. */
export function renderBarrel(names: string[]): string {
  const lines = ["// AUTOGENERATED by gen-contract. Do not edit.", ""];
  for (const name of names) {
    const Name = pascalCase(name);
    lines.push(`export type { ${Name}Props } from "./${Name}.ts";`);
  }
  return `${lines.join("\n")}\n`;
}
