import type { FlatSpec } from "../../../lib/flatten.ts";
import { pascalCase } from "../../../lib/pascal-case.ts";

export type BarrelEntry = Pick<FlatSpec, "name" | "events">;

/** Workspace barrel that re-exports every component's `<Name>Props` type — and
 *  `<Name>Event` for specs that declare an `events:` block — so consumers can
 *  `import { ModalProps, ModalEvent } from "@teseor/contract"`. Matches the
 *  package.json `exports["."]` mapping; deep imports
 *  (`@teseor/contract/Modal.ts`) keep working. */
export function renderBarrel(entries: BarrelEntry[]): string {
  const lines = ["// AUTOGENERATED by gen-contract. Do not edit.", ""];
  for (const entry of entries) {
    const Name = pascalCase(entry.name);
    const types = [`${Name}Props`];
    if (entry.events && Object.keys(entry.events).length > 0) {
      types.push(`${Name}Event`);
    }
    lines.push(`export type { ${types.join(", ")} } from "./${Name}.ts";`);
  }
  return `${lines.join("\n")}\n`;
}
