import { describe, expect, test } from "vitest";
import { renderBarrel } from "./barrel.ts";

describe("renderBarrel", () => {
  test("emits the AUTOGENERATED banner followed by a blank line", () => {
    const out = renderBarrel(["button"]);
    const lines = out.split("\n");
    expect(lines[0]).toBe("// AUTOGENERATED by gen-contract. Do not edit.");
    expect(lines[1]).toBe("");
  });

  test("PascalCases names and re-exports `<Name>Props` from `./<Name>.ts`", () => {
    const out = renderBarrel(["button", "modal-overlay"]);
    expect(out).toContain('export type { ButtonProps } from "./Button.ts";');
    expect(out).toContain('export type { ModalOverlayProps } from "./ModalOverlay.ts";');
  });

  test("ends with a trailing newline", () => {
    const out = renderBarrel(["button"]);
    expect(out.endsWith("\n")).toBe(true);
  });

  test("returns banner-only for an empty list", () => {
    expect(renderBarrel([])).toBe("// AUTOGENERATED by gen-contract. Do not edit.\n\n");
  });
});
