import { describe, expect, test } from "vitest";
import { type BarrelEntry, renderBarrel } from "./barrel.ts";

function entry(name: string, events?: BarrelEntry["events"]): BarrelEntry {
  return { name, events };
}

describe("renderBarrel", () => {
  test("emits the AUTOGENERATED banner followed by a blank line", () => {
    const out = renderBarrel([entry("button")]);
    const lines = out.split("\n");
    expect(lines[0]).toBe("// AUTOGENERATED by gen-contract. Do not edit.");
    expect(lines[1]).toBe("");
  });

  test("PascalCases names and re-exports `<Name>Props` from `./<Name>.ts`", () => {
    const out = renderBarrel([entry("button"), entry("modal-overlay")]);
    expect(out).toContain('export type { ButtonProps } from "./Button.ts";');
    expect(out).toContain('export type { ModalOverlayProps } from "./ModalOverlay.ts";');
  });

  test("ends with a trailing newline", () => {
    const out = renderBarrel([entry("button")]);
    expect(out.endsWith("\n")).toBe(true);
  });

  test("returns banner-only for an empty list", () => {
    expect(renderBarrel([])).toBe("// AUTOGENERATED by gen-contract. Do not edit.\n\n");
  });

  test("re-exports `<Name>Event` alongside Props for specs that declare events", () => {
    const out = renderBarrel([
      entry("modal", { dismiss: { description: "Closed.", payload: {} } }),
      entry("button"),
    ]);
    expect(out).toContain('export type { ModalProps, ModalEvent } from "./Modal.ts";');
    expect(out).toContain('export type { ButtonProps } from "./Button.ts";');
    expect(out).not.toContain("ButtonEvent");
  });

  test("does not re-export Event for a spec with an empty events: block", () => {
    const out = renderBarrel([entry("modal", {})]);
    expect(out).toContain('export type { ModalProps } from "./Modal.ts";');
    expect(out).not.toContain("ModalEvent");
  });
});
