import { describe, expect, test } from "vitest";
import type { FlatSpec } from "../../../lib/flatten.ts";
import { renderReadme } from "./readme.ts";

type SpecOverrides = Omit<Partial<FlatSpec>, "name"> & { name: string };

function spec(overrides: SpecOverrides): FlatSpec {
  const base: FlatSpec = {
    name: overrides.name,
    kind: "atomic",
    props: {},
    tokens: {},
    states: {},
  };
  return { ...base, ...overrides };
}

describe("renderReadme", () => {
  test("starts with the AUTOGENERATED banner", () => {
    const out = renderReadme([spec({ name: "button" })]);
    expect(out.split("\n")[0]).toBe("<!-- AUTOGENERATED by gen-contract. Do not edit. -->");
  });

  test("lists every component with its Props type", () => {
    const out = renderReadme([spec({ name: "button" }), spec({ name: "stack" })]);
    expect(out).toContain("- `Button` — `ButtonProps`");
    expect(out).toContain("- `Stack` — `StackProps`");
  });

  test("includes Variant / Intent / Size exports when present on the spec", () => {
    const out = renderReadme([
      spec({
        name: "button",
        variants: { solid: { description: "" }, outline: { description: "" } },
        intents: { primary: { description: "" } },
        sizes: { md: { description: "" } },
      }),
    ]);
    expect(out).toContain(
      "- `Button` — `ButtonVariant`, `ButtonIntent`, `ButtonSize`, `ButtonProps`",
    );
  });

  test("uses the first spec as the deep-import example", () => {
    const out = renderReadme([spec({ name: "modal" }), spec({ name: "button" })]);
    expect(out).toContain('import type { ModalProps } from "@teseor/contract/Modal.ts";');
  });

  test("falls back to Button in the example when no specs are provided", () => {
    const out = renderReadme([]);
    expect(out).toContain('import type { ButtonProps } from "@teseor/contract/Button.ts";');
  });
});
