import { pascalCase } from "../../../lib/pascal-case.ts";

/** Emit the `index.ts` barrel for `@teseor/react` — one named re-export pair
 *  (component + props type) per generated wrapper, keyed by its PascalCase name. */
export function renderBarrel(names: string[]): string {
  const lines = ["// AUTOGENERATED by gen-react. Do not edit.", ""];
  for (const name of names) {
    const Name = pascalCase(name);
    lines.push(`export { ${Name}, type ${Name}Props } from "./${Name}.tsx";`);
  }
  lines.push("");
  return lines.join("\n");
}
