/** Emit the `_css.d.ts` declaration that lets React wrappers `import "…css"`
 *  without TypeScript complaining about a missing module. */
export function renderCssShim(): string {
  return `// AUTOGENERATED by gen-react. Do not edit.

declare module "*.css";
`;
}
