// Forbids `typeof document !== "undefined"` / `typeof window !== "undefined"`
// branches in wrapper component files. Gating JSX on `typeof document` causes
// a hydration mismatch: the server renders the "no" branch, the client's
// first render hits the same `typeof document === "undefined"` truth (it
// hasn't run effects yet), then a later render flips it. The user-facing
// result is a flicker plus a React hydration warning.
//
// The fix is the mounted-flag pattern:
//
//   const [mounted, setMounted] = useState(false);
//   useEffect(() => setMounted(true), []);
//   return mounted ? createPortal(...) : null;
//
// Scope: hand-authored wrapper component files only —
// `packages/{react,vue}/src/**/*.{tsx,vue}`. Generated runtime helpers
// (`_runtime.ts`) and primitives (DOM utilities deliberately ssr-guarded at
// the function boundary, not inside JSX) are out of scope. The check is the
// "don't write this in JSX" rule, not a global typeof ban.
import type { FileRule } from "../registry.ts";

// `typeof X !== "undefined"` and the reverse direction. Matches either quote
// style and tolerates whitespace.
const TYPEOF_PATTERN = /\btypeof\s+(document|window)\s*(?:!==?|===?)\s*['"]undefined['"]/g;

/** Scan one source for `typeof document|window` SSR-gate expressions. */
export function findTypeofViolations(source: string): { line: number; expression: string }[] {
  const out: { line: number; expression: string }[] = [];
  const lines = source.split("\n");
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    for (const match of line.matchAll(TYPEOF_PATTERN)) {
      out.push({ line: i + 1, expression: match[0] });
    }
  }
  return out;
}

/** Registry entry consumed by `scripts/lint/run.ts`. */
export const rule: FileRule = {
  kind: "file-rule",
  pathspec: ["packages/react/src/**/*.tsx", "packages/vue/src/**/*.vue"],
  noun: "wrapper file(s)",
  // `_runtime.ts` is autogenerated and gates `matchMedia` at a function
  // boundary, not inside JSX. Tests can mock environments freely.
  accepts: (rel) =>
    !rel.includes("_runtime.") && !rel.endsWith(".test.ts") && !rel.endsWith(".test.tsx"),
  run: (_file, source) =>
    findTypeofViolations(source).map(({ line, expression }) => ({
      line,
      message: `\`${expression}\``,
    })),
  hint:
    "Gating JSX on `typeof document` causes a hydration flicker — the server and\n" +
    "the client's first render both see the same branch, then an effect flips it.\n" +
    "Use the mounted flag instead:\n" +
    "  const [mounted, setMounted] = useState(false);\n" +
    "  useEffect(() => setMounted(true), []);\n" +
    "  return mounted ? createPortal(...) : null;",
};
