// Two pairings — both fail loud pre-push and in CI:
//
//   1. `scripts/codegen/src/**` ↔ codegen test
//      Change a generator → touch a snapshot or a `__tests__/` file.
//      Snapshots count: auto-updating them confirms the diff is intentional.
//
//   2. `packages/{react,vue}/src/_runtime.ts` ↔ `_runtime.test.{ts,tsx}`
//      The runtime is autogenerated; snapshots verify the emitted string, not
//      its behavior. PR #660 shipped 8 runtime bugs across 12 Copilot rounds
//      because that was the only signal. See GitHub issue #661.
import type { DiffAwareCheck, ViolationDetail } from "../registry.ts";

/** Files that, when changed, demand a corresponding codegen test-side change. */
function isProductionCodegen(path: string): boolean {
  if (!path.startsWith("scripts/codegen/src/")) return false;
  if (path.endsWith(".test.ts")) return false;
  if (path.endsWith(".test.tsx")) return false;
  return path.endsWith(".ts") || path.endsWith(".tsx");
}

/** Files that count as a codegen test-side change. */
function isTestChange(path: string): boolean {
  if (path.startsWith("scripts/codegen/__tests__/")) return true;
  if (path.startsWith("scripts/codegen/src/") && path.endsWith(".test.ts")) return true;
  if (path.startsWith("scripts/codegen/src/") && path.endsWith(".test.tsx")) return true;
  return false;
}

const RUNTIME_PACKAGES = ["react", "vue"] as const;

function runtimePackageFor(path: string): (typeof RUNTIME_PACKAGES)[number] | undefined {
  for (const pkg of RUNTIME_PACKAGES) {
    if (path === `packages/${pkg}/src/_runtime.ts`) return pkg;
  }
  return undefined;
}

function isRuntimeTestFor(path: string, pkg: (typeof RUNTIME_PACKAGES)[number]): boolean {
  return (
    path === `packages/${pkg}/src/_runtime.test.ts` ||
    path === `packages/${pkg}/src/_runtime.test.tsx`
  );
}

function checkCodegenTests(changed: readonly string[]): ViolationDetail[] {
  if (changed.length === 0) return [];
  const out: ViolationDetail[] = [];

  // Pairing 1: codegen source files demand a test-side change.
  const productionChanges = changed.filter(isProductionCodegen);
  const testChanges = changed.filter(isTestChange);
  if (productionChanges.length > 0 && testChanges.length === 0) {
    for (const path of productionChanges) {
      out.push({
        file: path,
        message:
          "codegen source changed without a `scripts/codegen/__tests__/` or colocated `*.test.ts` change",
      });
    }
  }

  // Pairing 2: generated `_runtime.ts` demands a behavior-test change in the same package.
  for (const path of changed) {
    const pkg = runtimePackageFor(path);
    if (!pkg) continue;
    if (!changed.some((p) => isRuntimeTestFor(p, pkg))) {
      out.push({
        file: path,
        message: `\`_runtime.ts\` changed — needs a paired \`packages/${pkg}/src/_runtime.test.{ts,tsx}\` edit (see #661)`,
      });
    }
  }

  return out;
}

export const rule: DiffAwareCheck = {
  kind: "diff-aware",
  triggers: [
    "scripts/codegen/src/**",
    "packages/react/src/_runtime.ts",
    "packages/vue/src/_runtime.ts",
  ],
  run: checkCodegenTests,
  hint:
    "Snapshots count as a test-side change — auto-updating them confirms the diff is intentional.\n" +
    "For `_runtime.ts`, generator-output snapshots verify the string, not behavior — extend `_runtime.test.{ts,tsx}` so the branches you changed are exercised.",
};
