import { describe, expect, test } from "vitest";
import { renderBarrel } from "./barrel.ts";

describe("renderBarrel", () => {
  test("starts with the AUTOGENERATED banner", () => {
    expect(renderBarrel([]).split("\n")[0]).toBe("// AUTOGENERATED by gen-react. Do not edit.");
  });

  test("emits one named re-export pair per spec name, pascal-cased", () => {
    const out = renderBarrel(["button", "tooltip"]);
    expect(out).toContain(`export { Button, type ButtonProps } from "./Button.tsx";`);
    expect(out).toContain(`export { Tooltip, type TooltipProps } from "./Tooltip.tsx";`);
  });

  test("converts kebab-case spec names to PascalCase", () => {
    const out = renderBarrel(["icon-button"]);
    expect(out).toContain(`export { IconButton, type IconButtonProps } from "./IconButton.tsx";`);
  });

  test("ends with a trailing newline", () => {
    expect(renderBarrel(["button"]).endsWith("\n")).toBe(true);
  });
});
