import { describe, expect, test } from "vitest";
import type { Spec } from "../../gen-contract.ts";
import { renderReadme } from "./readme.ts";

function atomicSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "button",
    kind: "atomic",
    props: {},
    tokens: {},
    states: {},
    ...overrides,
  };
}

describe("renderReadme", () => {
  test("starts with the AUTOGENERATED banner", () => {
    expect(renderReadme([]).split("\n")[0]).toBe(
      "<!-- AUTOGENERATED by gen-react. Do not edit. -->",
    );
  });

  test("uses the first spec for the usage snippet, pascal-cased", () => {
    const out = renderReadme([atomicSpec({ name: "icon-button" })]);
    expect(out).toContain(`import { IconButton } from "@teseor/react";`);
    expect(out).toContain("<IconButton variant=");
  });

  test("falls back to `Button` in the usage snippet when there are no specs", () => {
    const out = renderReadme([]);
    expect(out).toContain(`import { Button } from "@teseor/react";`);
  });

  test("emits a bullet per spec under `## Components`", () => {
    const out = renderReadme([
      atomicSpec({ name: "button", description: "Push-button." }),
      atomicSpec({ name: "tooltip", description: "Floating tip." }),
    ]);
    expect(out).toContain("- `Button` — Push-button.");
    expect(out).toContain("- `Tooltip` — Floating tip.");
  });
});
