name: Bug Report
description: Report a bug in Teseor
labels: ["type: bug", "status: triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - "@teseor/css"
        - "@teseor/react (planned)"
        - "@teseor/svelte (planned)"
        - "docs"
        - "other"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "button"
        - "card"
        - "table"
        - "tabs"
        - "code"
        - "stack"
        - "grid"
        - "cluster"
        - "tokens"
        - "other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce or link to reproduction
      placeholder: |
        1. Apply class `.ui-button--primary`
        2. Add `disabled` attribute
        3. See incorrect hover state
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, package version
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
        - Version: @teseor/css@1.0.0
    validations:
      required: false
