import { pascalCase } from "../../../lib/pascal-case.ts";

/** Emit the `index.ts` barrel for `@teseor/vue` — one default re-export per
 *  generated SFC, keyed by its PascalCase component name. */
export function renderBarrel(names: string[]): string {
  const lines = ["// AUTOGENERATED by gen-vue. Do not edit.", ""];
  for (const name of names) {
    const Name = pascalCase(name);
    lines.push(`export { default as ${Name} } from "./${Name}.vue";`);
  }
  lines.push("");
  return lines.join("\n");
}
