import { pascalCase } from "../../../lib/pascal-case.ts";
import type { Spec } from "../../gen-contract.ts";

/** Emit the `@teseor/vue` README — install, setup, usage, and a flat list of
 *  every generated component. The first spec drives the usage snippet. */
export function renderReadme(specs: Spec[]): string {
  const componentList = specs
    .map((spec) => {
      const Name = pascalCase(spec.name);
      const desc = spec.description ?? "";
      return `- \`${Name}\` — ${desc}`;
    })
    .join("\n");

  const firstSpec = specs[0];
  const exampleName = firstSpec ? pascalCase(firstSpec.name) : "Button";

  return `<!-- AUTOGENERATED by gen-vue. Do not edit. -->

# @teseor/vue

Vue 3 wrappers for Teseor components. Generated from \`specs/*.yaml\`.

## Install

\`\`\`
pnpm add @teseor/vue @teseor/css vue
\`\`\`

## Setup

Import the CSS foundation once in your app entry. Components pull in their own per-component CSS automatically.

\`\`\`ts
import "@teseor/css/reset.css";
import "@teseor/css/tokens.css";
import "@teseor/css/base.css";
import "@teseor/css/utilities.css";
\`\`\`

## Usage

\`\`\`vue
<script setup lang="ts">
import { ${exampleName} } from "@teseor/vue";
</script>

<template>
  <${exampleName} variant="solid" intent="primary" @click="save">
    Save
  </${exampleName}>
</template>
\`\`\`

## Components

${componentList}

## Tests

Component behavior is verified framework-agnostically against the rendered DOM, in \`tests/contract/<name>.spec.ts\` (Playwright). The wrapper code itself is autogenerated; correctness of the emission is verified by snapshot tests in \`scripts/codegen/__tests__/\`.

## Generated content

Files in \`src/\` are autogenerated from \`specs/*.yaml\`. Do not edit them. The generator is \`scripts/codegen/src/generators/gen-vue.ts\`.
`;
}
