// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/avatar.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "avatar",
  rootClass: "t-avatar",
  fixtureIds: [
    "image",
    "initials",
    "initials-single",
    "empty-fallback",
    "size-sm",
    "size-lg",
    "square",
    "color-primary",
  ],
});
