// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/badge.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "badge",
  rootClass: "t-badge",
  fixtureIds: [
    "default",
    "solid-success",
    "outline-info",
    "ghost-danger",
    "pill",
    "with-icon",
    "small",
    "large",
  ],
});
