// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/button.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "button",
  rootClass: "t-button",
  fixtureIds: [
    "solid-primary",
    "solid-danger-md",
    "outline-neutral",
    "ghost-with-icon",
    "link-primary",
    "loading",
    "block-mobile",
  ],
});
