// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/button.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "button",
  rootClass: "t-button",
  fixtureIds: [
    "solid-primary",
    "solid-danger-md",
    "outline-neutral",
    "ghost-with-icon",
    "link-primary",
    "loading",
    "block-mobile",
    "m-ghost-danger-lg",
    "m-outline-danger-md",
    "m-solid-danger-sm",
    "m-link-neutral-lg",
    "m-solid-neutral-lg",
    "m-ghost-neutral-md",
    "m-link-neutral-sm",
    "m-outline-neutral-sm",
    "m-outline-primary-lg",
    "m-solid-primary-lg",
    "m-link-primary-md",
    "m-ghost-primary-sm",
    "m-solid-success-lg",
    "m-ghost-success-md",
    "m-outline-success-sm",
    "m-ghost-warning-lg",
    "m-solid-warning-md",
    "m-outline-warning-sm",
  ],
});
