// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/center.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "center",
  rootClass: "t-center",
  fixtureIds: [
    "default",
    "screen",
    "responsive",
  ],
});
