// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "cluster",
  rootClass: "t-cluster",
  fixtureIds: [
    "gap-3",
    "gap-0",
    "justify-between",
    "justify-around",
    "align-center",
    "align-baseline",
    "responsive-gap",
    "responsive-justify",
    "cov-baseline-around",
    "cov-baseline-between",
    "cov-baseline-center",
    "cov-baseline-end",
    "cov-baseline-start",
    "cov-center-around",
    "cov-center-between",
    "cov-center-center",
    "cov-center-end",
    "cov-center-start",
    "cov-end-around",
    "cov-end-between",
    "cov-end-center",
    "cov-end-end",
    "cov-end-start",
    "cov-start-around",
    "cov-start-between",
    "cov-start-center",
    "cov-start-end",
    "cov-start-start",
    "cov-stretch-around",
    "cov-stretch-between",
    "cov-stretch-center",
    "cov-stretch-end",
    "cov-stretch-start",
  ],
});
