// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "cluster",
  rootClass: "t-cluster",
  fixtureIds: [
    "gap-3",
    "gap-0",
    "justify-between",
    "justify-around",
    "align-center",
    "align-baseline",
    "responsive-gap",
    "responsive-justify",
  ],
});
