// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { expect, test } from "@playwright/test";

const ROOT_CLASS = "t-cluster";
const COMPONENT = "cluster";

const FIXTURE_IDS = [
  "gap-3",
  "gap-0",
  "justify-between",
  "justify-around",
  "align-center",
  "align-baseline",
  "responsive-gap",
  "responsive-justify",
] as const;

async function capture(
  page: import("@playwright/test").Page,
  framework: "react" | "vue",
  fixture: string,
): Promise<string> {
  await page.goto(`/${framework}/${COMPONENT}?fixture=${fixture}`);
  await page.locator(`.${ROOT_CLASS}`).first().waitFor({ state: "attached" });
  return page.evaluate((selector) => {
    function canon(el: Element): string {
      const tag = el.tagName.toLowerCase();
      const attrs = Array.from(el.attributes)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((a) => {
          const v = a.value.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
          return `${a.name}="${v}"`;
        })
        .join(" ");
      const open = attrs ? `<${tag} ${attrs}>` : `<${tag}>`;
      const close = `</${tag}>`;
      const children = Array.from(el.childNodes)
        .map((node) => {
          if (node.nodeType === 1) return canon(node as Element);
          if (node.nodeType === 3) {
            const text = node.textContent ?? "";
            return text.trim() === "" ? "" : text;
          }
          return "";
        })
        .join("");
      return `${open}${children}${close}`;
    }
    const root = document.querySelector(selector);
    if (!root) throw new Error(`harness: selector "${selector}" not found`);
    return canon(root);
  }, `.${ROOT_CLASS}`);
}

for (const id of FIXTURE_IDS) {
  test(`${COMPONENT} "${id}" — React and Vue render identical DOM`, async ({ page }) => {
    const reactHtml = await capture(page, "react", id);
    const vueHtml = await capture(page, "vue", id);
    expect(vueHtml).toBe(reactHtml);
    expect(reactHtml).toMatchSnapshot(`${COMPONENT}-${id}.html`);
  });
}
