// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/codeblock.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "codeblock",
  rootClass: "t-codeblock",
  fixtureIds: [
    "default",
  ],
});
