// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/code.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "code",
  rootClass: "t-code",
  fixtureIds: [
    "default",
  ],
});
