// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/divider.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "divider",
  rootClass: "t-divider",
  fixtureIds: [
    "default",
    "vertical",
    "decorative",
  ],
});
