// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/dot.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "dot",
  rootClass: "t-dot",
  fixtureIds: [
    "default",
    "success",
    "small",
    "status-online",
    "status-busy",
    "labeled",
  ],
});
