// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/heading.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "heading",
  rootClass: "t-heading",
  fixtureIds: [
    "default",
    "h1-display",
    "h2-as-md-size",
  ],
});
