// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/icon.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "icon",
  rootClass: "t-icon",
  fixtureIds: [
    "default",
    "small",
    "large",
    "colored-success",
    "labeled",
  ],
});
