// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/image.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "image",
  rootClass: "t-image",
  fixtureIds: [
    "default",
    "fit-cover",
    "fit-contain",
    "responsive-fit",
  ],
});
