// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/input.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "input",
  rootClass: "t-input",
  fixtureIds: [
    "default",
    "variant-outline",
    "variant-subtle",
    "variant-plain",
    "size-sm",
    "size-lg",
    "type-email",
    "type-number",
    "type-password",
    "invalid",
    "disabled",
    "form-control",
  ],
});
