// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/kbd.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "kbd",
  rootClass: "t-kbd",
  fixtureIds: [
    "default",
    "small",
    "large",
  ],
});
