// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/link.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "link",
  rootClass: "t-link",
  fixtureIds: [
    "default",
    "subtle",
    "plain",
  ],
});
