// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/list.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "list",
  rootClass: "t-list",
  fixtureIds: [
    "default",
    "ordered",
    "compact",
    "comfortable",
  ],
});
