// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/stack.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "stack",
  rootClass: "t-stack",
  fixtureIds: [
    "gap-3",
    "gap-0",
    "align-center",
    "align-stretch",
    "responsive-gap",
    "responsive-align",
    "gap-and-align",
    "cov-center",
    "cov-end",
    "cov-start",
    "cov-stretch",
  ],
});
