// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/switch.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "switch",
  rootClass: "t-switch",
  fixtureIds: [
    "default",
    "checked",
    "size-sm",
    "size-lg",
    "size-lg-checked",
    "disabled",
    "disabled-checked",
    "form-control",
  ],
});
