// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/text.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "text",
  rootClass: "t-text",
  fixtureIds: [
    "default",
    "paragraph",
    "muted-small",
    "highlight-strong",
    "lead-paragraph",
  ],
});
