// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/textarea.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: "textarea",
  rootClass: "t-textarea",
  fixtureIds: [
    "default",
    "variant-outline",
    "variant-subtle",
    "variant-plain",
    "size-sm",
    "size-lg",
    "rows-2",
    "rows-6",
    "resize-none",
    "resize-both",
    "invalid",
    "disabled",
    "form-control",
  ],
});
