// AUTOGENERATED by gen-react. Do not edit.

import type { ElementType } from "react";

const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;

type Breakpoint = (typeof RESPONSIVE_KEYS)[number];

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;

export function responsiveDataAttrs(
  name: string,
  value: unknown,
): Record<string, string | undefined> {
  if (value == null || value === false) return {};
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, string | undefined> = {};
    for (const key of RESPONSIVE_KEYS) {
      const v = obj[key];
      if (v == null || v === false) continue;
      const attr = key === "base" ? `data-${name}` : `data-${name}-${key}`;
      out[attr] = v === true ? "true" : String(v);
    }
    return out;
  }
  return { [`data-${name}`]: value === true ? "true" : String(value) };
}

/**
 * Widen a narrow tag-name union (e.g. `"button" | "a"`) back to
 * `ElementType` so the rendered `<Component>` does not pin JSX's ref slot to
 * the intersection of the per-tag ref types. The narrow union still types
 * the consumer-facing `as` prop; this only widens the local variable used in
 * JSX. No cast: the parameter type accepts the union by structural assignment.
 */
export function asElement(value: ElementType): ElementType {
  return value;
}
