// AUTOGENERATED by gen-react. Do not edit.

import {
  Children,
  cloneElement,
  type ElementType,
  isValidElement,
  type ReactElement,
  type ReactNode,
  type Ref,
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
} from "react";

const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;

type Breakpoint = (typeof RESPONSIVE_KEYS)[number];

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;

// matchMedia queries baked from specs/_breakpoints.yaml. Single source.
const BREAKPOINT_QUERIES: Partial<Record<Breakpoint, string>> = {
  md: "(min-width: 48rem)",
  lg: "(min-width: 64rem)",
  xl: "(min-width: 80rem)",
  "2xl": "(min-width: 96rem)",
};

function readActiveBreakpoint(): Breakpoint {
  if (typeof window === "undefined" || typeof window.matchMedia !== "function") return "base";
  for (let i = RESPONSIVE_KEYS.length - 1; i > 0; i--) {
    const key = RESPONSIVE_KEYS[i];
    if (!key) continue;
    const q = BREAKPOINT_QUERIES[key];
    if (q && window.matchMedia(q).matches) return key;
  }
  return "base";
}

/** Reactive active-breakpoint key. Drives `Responsive<T>` runtime behavior. */
export function useActiveBreakpoint(): Breakpoint {
  const [bp, setBp] = useState<Breakpoint>(() => readActiveBreakpoint());
  useEffect(() => {
    if (typeof window === "undefined" || typeof window.matchMedia !== "function") return;
    const onChange = () => setBp(readActiveBreakpoint());
    const cleanups: Array<() => void> = [];
    for (const key of RESPONSIVE_KEYS) {
      if (key === "base") continue;
      const q = BREAKPOINT_QUERIES[key];
      if (!q) continue;
      const mql = window.matchMedia(q);
      mql.addEventListener("change", onChange);
      cleanups.push(() => mql.removeEventListener("change", onChange));
    }
    return () => {
      for (const fn of cleanups) fn();
    };
  }, []);
  return bp;
}

/** Resolve a `Responsive<boolean>` at the active breakpoint (mobile-first cascade). */
export function isActiveAt(value: unknown, bp: Breakpoint): boolean {
  if (value === true) return true;
  if (value == null || value === false) return false;
  if (typeof value !== "object") return false;
  const obj = value as Partial<Record<Breakpoint, boolean>>;
  const idx = RESPONSIVE_KEYS.indexOf(bp);
  for (let i = idx; i >= 0; i--) {
    const key = RESPONSIVE_KEYS[i];
    if (key && key in obj) return obj[key] === true;
  }
  return false;
}

/** Resolve a `Responsive<T>` at the active breakpoint (mobile-first cascade). */
export function resolveResponsive<T>(
  value: Responsive<T> | undefined,
  bp: Breakpoint,
): T | undefined {
  if (value == null) return undefined;
  if (typeof value !== "object" || Array.isArray(value)) return value as T;
  const obj = value as Partial<Record<Breakpoint, T>>;
  const idx = RESPONSIVE_KEYS.indexOf(bp);
  for (let i = idx; i >= 0; i--) {
    const key = RESPONSIVE_KEYS[i];
    if (key && key in obj) return obj[key];
  }
  return undefined;
}

export function responsiveDataAttrs(
  name: string,
  value: unknown,
): Record<string, string | undefined> {
  if (value == null || value === false) return {};
  if (typeof value === "object") {
    // Emit every declared key (including `false` at non-base) — the CSS
    // override pattern needs the explicit attribute to match against.
    const obj = value as Record<string, unknown>;
    const out: Record<string, string | undefined> = {};
    for (const key of RESPONSIVE_KEYS) {
      const v = obj[key];
      if (v == null) continue;
      // `base: false` has no attribute (absence-of) — emitting "false" would never match.
      if (key === "base" && v === false) continue;
      const attr = key === "base" ? `data-${name}` : `data-${name}-${key}`;
      out[attr] = v === true ? "true" : v === false ? "false" : String(v);
    }
    return out;
  }
  return { [`data-${name}`]: value === true ? "true" : String(value) };
}

/** Widen a narrow tag-name union back to ElementType so JSX's ref slot isn't pinned. */
export function asElement(value: ElementType): ElementType {
  return value;
}

// ── Slot — clone-into-child pattern for `asChild` composites ────────────────

type SlotProps = Record<string, unknown> & { children?: ReactNode };

function mergeSlotProps(
  childProps: Record<string, unknown>,
  slotProps: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...childProps };
  for (const key of Object.keys(slotProps)) {
    if (key === "children") continue;
    const childValue = childProps[key];
    const slotValue = slotProps[key];
    if (key === "style") {
      out[key] = {
        ...((childValue as object | undefined) ?? {}),
        ...((slotValue as object | undefined) ?? {}),
      };
    } else if (key === "className") {
      out[key] = [childValue, slotValue].filter(Boolean).join(" ");
    } else if (
      key.startsWith("on") &&
      typeof childValue === "function" &&
      typeof slotValue === "function"
    ) {
      // Compose handlers: child fires first, then ours — skip ours if the
      // child called `event.preventDefault()` (Radix convention). Lets a
      // consumer suppress overlay behavior by preventing on their own handler.
      const childFn = childValue as (...a: unknown[]) => void;
      const slotFn = slotValue as (...a: unknown[]) => void;
      out[key] = (...args: unknown[]) => {
        childFn(...args);
        const event = args[0] as { defaultPrevented?: boolean } | undefined;
        if (event?.defaultPrevented !== true) slotFn(...args);
      };
    } else {
      // Slot props win for refs, aria-*, data-*.
      out[key] = slotValue;
    }
  }
  return out;
}

/**
 * Clone-into-child: merges slot props onto a single React element child.
 * Used by composite wrappers when `asChild` is true — `aria-describedby`,
 * event handlers, and the anchor binding land on the consumer's element
 * instead of an extra `<span>` wrapper. Warns and renders nothing if
 * `children` isn't exactly one valid React element (fragment, multiple
 * children, or null all hit the warn path — never throws).
 */
export function Slot({ children, ...slotProps }: SlotProps): ReactElement | null {
  const elements = Children.toArray(children).filter(isValidElement);
  if (elements.length !== 1) {
    if (typeof console !== "undefined") {
      console.warn(
        `Slot: expected exactly one React element child, got ${elements.length}. Pass a single element (e.g. <button>...</button>) or drop \`asChild\`.`,
      );
    }
    return null;
  }
  const child = elements[0] as ReactElement<Record<string, unknown>>;
  // Astro wraps slotted children in `<astro-slot>`. `cloneElement` merges
  // props onto that wrapper, not the element inside, so handlers and
  // `aria-describedby` never reach the consumer's button. Warn loudly —
  // there is no workaround at the React layer.
  if (typeof child.type === "string" && child.type.startsWith("astro-")) {
    if (typeof console !== "undefined") {
      console.warn(
        "Slot: `asChild` does not work inside Astro slots — children arrive wrapped in <astro-slot>. Drop `asChild` (use the default wrapper) when rendering this component from a .astro file.",
      );
    }
    return cloneElement(child, mergeSlotProps(child.props ?? {}, slotProps));
  }
  return cloneElement(child, mergeSlotProps(child.props ?? {}, slotProps));
}

// ── Overlay hook — used by composite overlay components ────────────────────

export type OverlayInteraction = {
  on: { event: string; target?: string; key?: string };
  do: "open" | "close" | "toggle";
  /** ms delay resolved at the call site from the consumer's delay props. */
  delayMs?: number;
  when?: string;
};

type OverlayConfig = {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  anchorVar: string;
  popoverMode: "auto" | "manual" | "hint";
  interactions: ReadonlyArray<OverlayInteraction>;
  /** Active at the current breakpoint? state machine no-ops; matches CSS `data-disabled-bp`. */
  disabled?: Responsive<boolean>;
};

type AnyEventHandler = (event: unknown) => void;

type OverlayHandlers = Record<string, AnyEventHandler>;

type OverlayReturn<T extends HTMLElement> = {
  open: boolean;
  state: "open" | "closed";
  activeBp: Breakpoint;
  setOpen: (next: boolean) => void;
  anchorName: string;
  anchorVar: string;
  popoverId: string;
  popoverMode: "auto" | "manual" | "hint";
  contentRef: Ref<T>;
  triggerHandlers: OverlayHandlers;
};

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "");
}

// `:popover-open` throws SyntaxError on engines that don't recognize it; probe once.
const SUPPORTS_POPOVER_OPEN_SELECTOR =
  typeof CSS !== "undefined" &&
  typeof CSS.supports === "function" &&
  CSS.supports("selector(:popover-open)");

function popoverIsOpen(node: HTMLElement): boolean | undefined {
  if (!SUPPORTS_POPOVER_OPEN_SELECTOR) return undefined;
  try {
    return node.matches(":popover-open");
  } catch {
    return undefined;
  }
}

const EVENT_TO_HANDLER: Record<string, string> = {
  pointerenter: "onPointerEnter",
  pointerleave: "onPointerLeave",
  pointerdown: "onPointerDown",
  pointerup: "onPointerUp",
  click: "onClick",
  focusin: "onFocus",
  focusout: "onBlur",
  keydown: "onKeyDown",
  keyup: "onKeyUp",
};

/** State machine + popover toggle + anchor binding + event wiring for overlay composites. */
export function useOverlay<T extends HTMLElement = HTMLElement>(
  config: OverlayConfig,
): OverlayReturn<T> {
  const {
    open: openProp,
    defaultOpen = false,
    onOpenChange,
    anchorVar,
    popoverMode,
    interactions,
    disabled,
  } = config;
  const activeBp = useActiveBreakpoint();
  const isDisabled = isActiveAt(disabled, activeBp);

  const controlled = openProp !== undefined;
  const [internalOpen, setInternalOpen] = useState<boolean>(defaultOpen);
  const open = controlled ? Boolean(openProp) : internalOpen;
  const onOpenChangeRef = useRef(onOpenChange);
  useEffect(() => {
    onOpenChangeRef.current = onOpenChange;
  }, [onOpenChange]);

  const setOpen = useCallback(
    (next: boolean) => {
      if (!controlled) setInternalOpen(next);
      onOpenChangeRef.current?.(next);
    },
    [controlled],
  );

  const rawId = useId();
  const idCore = sanitizeId(rawId);
  const anchorName = `--t-${idCore}`;
  const popoverId = `t-overlay-${idCore}`;

  // Callback ref + tracked node so the popover-sync effect re-runs when the
  // floating element mounts later (e.g. `{hasContent && <…/>}` flips true
  // while `open` is already true). A plain `useRef` wouldn't notify React.
  const [contentNode, setContentNode] = useState<T | null>(null);
  const contentRef = useCallback((node: T | null) => {
    setContentNode(node);
  }, []);

  const timersRef = useRef<{ open: number; close: number }>({ open: 0, close: 0 });
  const clearTimers = useCallback(() => {
    if (timersRef.current.open) window.clearTimeout(timersRef.current.open);
    if (timersRef.current.close) window.clearTimeout(timersRef.current.close);
    timersRef.current.open = 0;
    timersRef.current.close = 0;
  }, []);

  // `openRef` lets effect-bound handlers read latest state without re-binding.
  const openRef = useRef(open);
  useEffect(() => {
    openRef.current = open;
  }, [open]);

  const schedule = useCallback(
    (action: "open" | "close" | "toggle", delayMs: number) => {
      if (isDisabled) return;
      clearTimers();
      const next = action === "toggle" ? !openRef.current : action === "open";
      if (delayMs <= 0) {
        setOpen(next);
        return;
      }
      const slot: "open" | "close" = action === "close" ? "close" : "open";
      timersRef.current[slot] = window.setTimeout(() => setOpen(next), delayMs);
    },
    [clearTimers, setOpen, isDisabled],
  );

  useEffect(() => () => clearTimers(), [clearTimers]);

  // Drive Popover API from `open` + the tracked node. Re-runs when either
  // changes — handles "node mounts later while open is already true."
  useEffect(() => {
    if (!contentNode) return;
    const popoverState = popoverIsOpen(contentNode);
    if (open && popoverState !== true) {
      try {
        contentNode.showPopover();
      } catch {}
    } else if (!open && popoverState !== false) {
      try {
        contentNode.hidePopover();
      } catch {}
    }
  }, [open, contentNode]);

  // Document/window-bound rules. Listeners mount with the rules array;
  // `when:` is re-evaluated per fire via `openRef`.
  useEffect(() => {
    const cleanups: Array<() => void> = [];
    for (const rule of interactions) {
      const target = rule.on.target;
      if (target !== "document" && target !== "window") continue;
      const sink: EventTarget = target === "document" ? document : window;
      const handler = (event: Event) => {
        if (rule.when === "open" && !openRef.current) return;
        if (rule.on.key && event instanceof KeyboardEvent && event.key !== rule.on.key) return;
        schedule(rule.do, rule.delayMs ?? 0);
      };
      sink.addEventListener(rule.on.event, handler);
      cleanups.push(() => sink.removeEventListener(rule.on.event, handler));
    }
    return () => {
      for (const fn of cleanups) fn();
    };
  }, [interactions, schedule]);

  // Trigger-bound rules → React handlers spread on the wrapper element.
  // Same-event rules compose; `when` and `on.key` filter per-fire as above.
  const triggerHandlers: OverlayHandlers = {};
  for (const rule of interactions) {
    if (rule.on.target !== "trigger") continue;
    const handlerName = EVENT_TO_HANDLER[rule.on.event];
    if (!handlerName) continue;
    const previous = triggerHandlers[handlerName];
    const delayMs = rule.delayMs ?? 0;
    const next = (e: unknown) => {
      previous?.(e);
      if (rule.when === "open" && !openRef.current) return;
      if (rule.on.key) {
        if (!(e instanceof KeyboardEvent) || e.key !== rule.on.key) return;
      }
      schedule(rule.do, delayMs);
    };
    triggerHandlers[handlerName] = next;
  }

  return {
    open,
    state: open ? "open" : "closed",
    activeBp,
    setOpen,
    anchorName,
    anchorVar,
    popoverId,
    popoverMode,
    contentRef,
    triggerHandlers,
  };
}
