// AUTOGENERATED by gen-react. Do not edit.

const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;

export type Responsive<T> = T | Partial<Record<(typeof RESPONSIVE_KEYS)[number], T>>;

export function responsiveDataAttrs(
  name: string,
  value: unknown,
): Record<string, string | undefined> {
  if (value == null || value === false) return {};
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, string | undefined> = {};
    for (const key of RESPONSIVE_KEYS) {
      const v = obj[key];
      if (v == null || v === false) continue;
      const attr = key === "base" ? `data-${name}` : `data-${name}-${key}`;
      out[attr] = v === true ? "true" : String(v);
    }
    return out;
  }
  return { [`data-${name}`]: value === true ? "true" : String(value) };
}
