"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/avatar.yaml

import "@teseor/css/components/avatar.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { useState } from "react";
import { deriveInitials, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type AvatarSize = "sm" | "md" | "lg";

type AvatarShape = "circle" | "square";

type AvatarColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type AvatarOwnProps = {
  /** Size scale. */
  size?: Responsive<AvatarSize>;
  /** Image source URL. When set and the image loads, the avatar renders `<img>`. On `onError`, falls back to the initials or empty box. */
  src?: string;
  /** Alt text for the image. Required when `src` is set and the image carries standalone meaning; empty string when the avatar is decorative inside a labeled context. */
  alt?: string;
  /** Person's name. Drives the auto-derived initials fallback when `src` is missing or fails to load. */
  name?: string;
  /** Explicit initials override. When set, wins over the auto-derived "first letter of first + last whitespace-split token" rule. */
  initials?: string;
  /** Outer corner shape. Default is `circle` via the CSS layer (absence-of-attr). */
  shape?: AvatarShape;
  /** Semantic background color of the fallback (initials or empty) box. Default is `neutral` via the CSS layer. */
  color?: AvatarColor;
  children?: ReactNode;
  ref?: Ref<HTMLElementTagNameMap["span"]>;
};

export type AvatarProps = Readonly<
  AvatarOwnProps & Omit<ComponentProps<"span">, keyof AvatarOwnProps>
>;

/**
 * Image container with name/initials/icon fallback chain. Renders `<img>` when `src` is set and loads successfully; falls back to initials (when `name` is provided) or an empty muted box when nothing else fits. Atomic primitive.
 *
 * @example Image
 * ```tsx
 * <Avatar src="/img/avatar-jane.jpg" alt="Jane Doe" name="Jane Doe">Label</Avatar>
 * ```
 *
 * @example Initials
 * ```tsx
 * <Avatar name="Jane Doe">Label</Avatar>
 * ```
 *
 * @example Initials Single
 * ```tsx
 * <Avatar name="Madonna">Label</Avatar>
 * ```
 */
export function Avatar(props: AvatarProps) {
  const { size, src, alt, name, initials, shape, color, children, ref, className, ...rest } = props;

  const mergedClassName = mergeClass("t-avatar", className);
  const [imgErrored, setImgErrored] = useState<boolean>(false);

  return (
    <span
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("size", size)}
      data-shape={shape}
      data-color={color}
    >
      {src && !imgErrored ? (
        <img src={src} alt={alt} onError={() => setImgErrored(true)} />
      ) : name ? (
        <span>{deriveInitials(name, initials)}</span>
      ) : (
        <span />
      )}
    </span>
  );
}
