"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/badge.yaml

import "@teseor/css/components/badge.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type BadgeVariant = "solid" | "outline" | "ghost";

type BadgeIntent = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type BadgeSize = "sm" | "md" | "lg";

type BadgeShape = "rounded" | "pill";

type BadgeOwnProps = {
  /** Visual style. */
  variant?: BadgeVariant;
  /** Semantic color. */
  intent?: BadgeIntent;
  /** Size scale. */
  size?: Responsive<BadgeSize>;
  /** Corner shape. `rounded` is the default (token-controlled radius); `pill` fully rounds the inline ends for decorative chip-style badges. */
  shape?: BadgeShape;
  /** Decorative icon rendered before the label in the inline direction. Wrapped in a `<span data-badge-icon="">` element; the consumer's icon component carries any `aria-hidden` it needs. */
  icon?: ReactNode;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<span>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type BadgeProps = Readonly<
  BadgeOwnProps & Omit<ComponentProps<"span">, keyof BadgeOwnProps>
>;

/**
 * Small inline label for status, notification, or metadata. Renders `<span>` with token-driven color, variant, size, and shape. Decorative by default — consumers supply `aria-label` when the badge carries standalone meaning.
 *
 * @example Default
 * ```tsx
 * <Badge>Label</Badge>
 * ```
 *
 * @example Solid Success
 * ```tsx
 * <Badge intent="success">Label</Badge>
 * ```
 *
 * @example Outline Info
 * ```tsx
 * <Badge variant="outline" intent="info">Label</Badge>
 * ```
 */
export function Badge(props: BadgeProps) {
  const { variant, intent, size, shape, icon, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("span");
  const mergedClassName = mergeClass("t-badge", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      data-variant={variant}
      data-intent={intent}
      {...responsiveDataAttrs("size", size)}
      data-shape={shape}
    >
      {icon != null ? <span data-badge-icon="">{icon}</span> : null}
      {children}
    </Component>
  );
}
