"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/blockquote.yaml

import "@teseor/css/components/blockquote.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type BlockquoteVariant = "default" | "subtle";

type BlockquoteOwnProps = {
  /** Visual style. */
  variant?: BlockquoteVariant;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<blockquote>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type BlockquoteProps = Readonly<
  BlockquoteOwnProps & Omit<ComponentProps<"blockquote">, keyof BlockquoteOwnProps>
>;

/**
 * Quoted-text primitive — styled `<blockquote>` with accent border and prose spacing. Source attribution composes via a `<cite>` child; native `cite` HTML attr (URL) passes through the inherited type.
 *
 * @example Default
 * ```tsx
 * <Blockquote>Label</Blockquote>
 * ```
 *
 * @example Subtle
 * ```tsx
 * <Blockquote variant="subtle">Label</Blockquote>
 * ```
 */
export function Blockquote(props: BlockquoteProps) {
  const { variant, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("blockquote");
  const mergedClassName = mergeClass("t-blockquote", className);

  return (
    <Component {...rest} ref={ref} className={mergedClassName} data-variant={variant}>
      {children}
    </Component>
  );
}
