"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/button.yaml

import "@teseor/css/components/button.css";
import type { ComponentProps, ElementType, ReactNode, Ref } from "react";
import { dataAttrs } from "./_runtime.ts";

type ButtonVariant = "solid" | "outline" | "ghost" | "link";

type ButtonIntent = "primary" | "neutral" | "success" | "warning" | "danger";

type ButtonSize = "sm" | "md" | "lg";

type ButtonOwnProps = {
  /** Visual style. */
  variant?: ButtonVariant;
  /** Semantic color. */
  intent?: ButtonIntent;
  /** Size scale. */
  size?: ButtonSize | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", ButtonSize>>;
  /** Polymorphic root element. Defaults to `button`; set to `a` for link-shaped triggers (paired with `variant: link`). */
  as?: ElementType;
  /** Disables interaction and applies the disabled visual state. Mapped to the native `disabled` attribute on `button`, `aria-disabled="true"` otherwise. */
  disabled?: boolean;
  /** Shows a spinner in place of the label and disables interaction. The original label stays in the accessibility tree. */
  loading?: boolean;
  /** Icon rendered before the label in the inline direction. Slot size scales with `size`. Accepts any node (icon component, SVG, etc.). */
  iconStart?: ReactNode;
  /** Icon rendered after the label in the inline direction. Accepts any node. */
  iconEnd?: ReactNode;
  /** Stretches the button to the inline-size of its container. Responsive so layouts can pin block-width on mobile and shrink to content above. */
  block?: boolean | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", boolean>>;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type ButtonProps = Readonly<
  ButtonOwnProps & Omit<ComponentProps<"button">, keyof ButtonOwnProps>
>;

/**
 * A trigger that performs an action when activated.
 *
 * @example Solid Primary
 * ```tsx
 * <Button variant="solid" intent="primary">Label</Button>
 * ```
 *
 * @example Solid Danger Md
 * ```tsx
 * <Button variant="solid" intent="danger" size="md">Label</Button>
 * ```
 *
 * @example Outline Neutral
 * ```tsx
 * <Button variant="outline" intent="neutral">Label</Button>
 * ```
 */
export function Button(props: ButtonProps) {
  const {
    variant,
    intent,
    size,
    as,
    disabled,
    loading,
    iconStart,
    iconEnd,
    block,
    children,
    ref,
    className,
    ...rest
  } = props;

  const Component = as ?? "button";
  const isButton = Component === "button";
  const inactive = disabled === true || loading === true;
  const mergedClassName = className ? `t-button ${className}` : "t-button";

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      data-variant={variant}
      data-intent={intent}
      {...dataAttrs("size", size)}
      {...dataAttrs("block", block)}
      data-loading={loading === true ? "true" : undefined}
      disabled={isButton ? inactive : undefined}
      aria-disabled={!isButton && inactive ? "true" : undefined}
      aria-busy={loading === true ? "true" : undefined}
    >
      {iconStart != null ? (
        <span data-button-icon="" data-position="start">
          {iconStart}
        </span>
      ) : null}
      <span data-button-label="">{children}</span>
      {iconEnd != null ? (
        <span data-button-icon="" data-position="end">
          {iconEnd}
        </span>
      ) : null}
      <span data-button-spinner="" aria-hidden="true" />
    </Component>
  );
}
