"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/center.yaml

import "@teseor/css/components/center.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type CenterMinHeight = "screen";

type CenterOwnProps = {
  /** Minimum block size. `screen` maps to 100dvh (splash-screen / hero pattern). Leave unset to center inside the parent's flow. Custom values: override `--t-center-min-height` on the element. */
  minHeight?: Responsive<CenterMinHeight>;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type CenterProps = Readonly<
  CenterOwnProps & Omit<ComponentProps<"div">, keyof CenterOwnProps>
>;

/**
 * A layout primitive that centers a single child on both axes. Pure CSS, no children styling. `minHeight` is unset by default — the centered box hugs its child; pass `screen` for splash-screen / hero patterns or override `--t-center-min-height` for custom values.
 *
 * @example Default
 * ```tsx
 * <Center>Label</Center>
 * ```
 *
 * @example Screen
 * ```tsx
 * <Center minHeight="screen">Label</Center>
 * ```
 *
 * @example Responsive
 * ```tsx
 * <Center minHeight={{"md":"screen"}}>Label</Center>
 * ```
 */
export function Center(props: CenterProps) {
  const { minHeight, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("div");
  const mergedClassName = mergeClass("t-center", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("min-height", minHeight)}
    >
      {children}
    </Component>
  );
}
