"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/cluster.yaml

import "@teseor/css/components/cluster.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { responsiveDataAttrs } from "./_runtime.ts";

type ClusterOwnProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
  /** Block-axis alignment of children. One of `start`, `center`, `end`, `stretch`, `baseline`. */
  align?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
  /** Inline-axis distribution. One of `start`, `center`, `end`, `between`, `around`. */
  justify?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
  children?: ReactNode;
  ref?: Ref<HTMLElementTagNameMap["div"]>;
};

export type ClusterProps = Readonly<
  ClusterOwnProps & Omit<ComponentProps<"div">, keyof ClusterOwnProps>
>;

/**
 * A horizontal layout primitive. Wraps children on the inline axis with consistent spacing.
 *
 * @example Gap 3
 * ```tsx
 * <Cluster gap="3">Label</Cluster>
 * ```
 *
 * @example Gap 0
 * ```tsx
 * <Cluster gap="0">Label</Cluster>
 * ```
 *
 * @example Justify Between
 * ```tsx
 * <Cluster gap="3" justify="between">Label</Cluster>
 * ```
 */
export function Cluster(props: ClusterProps) {
  const { gap, align, justify, children, ref, className, ...rest } = props;

  const mergedClassName = className ? `t-cluster ${className}` : "t-cluster";

  return (
    <div
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("gap", gap)}
      {...responsiveDataAttrs("align", align)}
      {...responsiveDataAttrs("justify", justify)}
    >
      {children}
    </div>
  );
}
