"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/code.yaml

import "@teseor/css/components/code.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { mergeClass } from "./_runtime.ts";

type CodeOwnProps = {
  children?: ReactNode;
  ref?: Ref<HTMLElementTagNameMap["code"]>;
};

export type CodeProps = Readonly<CodeOwnProps & Omit<ComponentProps<"code">, keyof CodeOwnProps>>;

/**
 * Inline monospace fragment for short code spans in prose.
 *
 * @example Default
 * ```tsx
 * <Code>Label</Code>
 * ```
 */
export function Code(props: CodeProps) {
  const { children, ref, className, ...rest } = props;

  const mergedClassName = mergeClass("t-code", className);

  return (
    <code {...rest} ref={ref} className={mergedClassName}>
      {children}
    </code>
  );
}
