"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/codeblock.yaml

import "@teseor/css/components/codeblock.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { mergeClass } from "./_runtime.ts";

type CodeblockOwnProps = {
  children?: ReactNode;
  ref?: Ref<HTMLElementTagNameMap["pre"]>;
};

export type CodeblockProps = Readonly<
  CodeblockOwnProps & Omit<ComponentProps<"pre">, keyof CodeblockOwnProps>
>;

/**
 * Block container for multi-line code with monospace font and horizontal overflow scroll.
 *
 * @example Default
 * ```tsx
 * <Codeblock>Label</Codeblock>
 * ```
 */
export function Codeblock(props: CodeblockProps) {
  const { children, ref, className, ...rest } = props;

  const mergedClassName = mergeClass("t-codeblock", className);

  return (
    <pre {...rest} ref={ref} className={mergedClassName}>
      <code>{children}</code>
    </pre>
  );
}
