"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/divider.yaml

import "@teseor/css/components/divider.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type DividerOrientation = "horizontal" | "vertical";

type DividerOwnProps = {
  /** Axis of the rule. Absence-of-attr selects `horizontal` — codegen falls back to the first map key and the `<hr>` carries the native horizontal orientation. Pass `vertical` to render a `<div>` with explicit `role="separator"` + `aria-orientation="vertical"`. */
  orientation?: DividerOrientation;
  /** Removes the divider from the accessibility tree (`role="none"` + `aria-hidden="true"`). Use when the rule is purely visual and not announcing a structural boundary. */
  decorative?: boolean;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type DividerProps = Readonly<
  DividerOwnProps & Omit<ComponentProps<"div">, keyof DividerOwnProps>
>;

/**
 * Horizontal-or-vertical visual rule. Renders `<hr>` for the horizontal orientation (native `role="separator"`) and `<div role="separator" aria-orientation="vertical">` for the vertical one. The `decorative` prop hides the element from the accessibility tree (`role="none"` + `aria-hidden="true"`).
 *
 * @example Default
 * ```tsx
 * <Divider>Label</Divider>
 * ```
 *
 * @example Vertical
 * ```tsx
 * <Divider orientation="vertical">Label</Divider>
 * ```
 *
 * @example Decorative
 * ```tsx
 * <Divider decorative>Label</Divider>
 * ```
 */
export function Divider(props: DividerProps) {
  const { orientation, decorative, asChild, children, ref, className, ...rest } = props;

  const tagMap = { horizontal: "hr", vertical: "div" } as const;
  const resolvedTag = tagMap[orientation ?? "horizontal"];
  const isVoidResolved = resolvedTag === "hr";
  const Component = asChild && !isVoidResolved ? Slot : asElement(resolvedTag);
  const mergedClassName = mergeClass("t-divider", className);

  return isVoidResolved ? (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      role={decorative === true ? "none" : "separator"}
      aria-orientation={orientation}
      aria-hidden={decorative === true ? "true" : undefined}
      data-decorative={decorative === true ? "true" : undefined}
    />
  ) : (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      role={decorative === true ? "none" : "separator"}
      aria-orientation={orientation}
      aria-hidden={decorative === true ? "true" : undefined}
      data-decorative={decorative === true ? "true" : undefined}
    >
      {children}
    </Component>
  );
}
