"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/heading.yaml

import "@teseor/css/components/heading.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type HeadingSize = "xs" | "sm" | "md" | "lg" | "xl";

type HeadingLevel = "1" | "2" | "3" | "4" | "5" | "6";

type HeadingOwnProps = {
  /** Size scale. */
  size?: Responsive<HeadingSize>;
  /** Outline level. Drives the rendered tag and the default visual size. */
  level?: HeadingLevel;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type HeadingProps = Readonly<
  HeadingOwnProps & Omit<ComponentProps<"div">, keyof HeadingOwnProps>
>;

/**
 * Semantic prose heading. The rendered tag switches with `level` so outline tools and screen readers read native `<h1>`–`<h6>` structure.
 *
 * @example Default
 * ```tsx
 * <Heading level="2">Label</Heading>
 * ```
 *
 * @example H1 Display
 * ```tsx
 * <Heading level="1">Label</Heading>
 * ```
 *
 * @example H2 As Md Size
 * ```tsx
 * <Heading level="2" size="md">Label</Heading>
 * ```
 */
export function Heading(props: HeadingProps) {
  const { size, level, asChild, children, ref, className, ...rest } = props;

  const tagMap = { "1": "h1", "2": "h2", "3": "h3", "4": "h4", "5": "h5", "6": "h6" } as const;
  const Component = asChild ? Slot : asElement(tagMap[level ?? "2"]);
  const mergedClassName = mergeClass("t-heading", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("size", size)}
    >
      {children}
    </Component>
  );
}
