"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/icon.yaml

import "@teseor/css/components/icon.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type IconSize = "sm" | "md" | "lg";

type IconColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type IconOwnProps = {
  /** Size scale. */
  size?: Responsive<IconSize>;
  /** Semantic color override. Absence-of-attr keeps the SVG on `currentColor` (inherits from the parent's text color); setting a value swaps the `--t-icon-fg` slot to the matching semantic token. */
  color?: IconColor;
  /** Accessible name. When set, the wrapper carries `aria-label={label}` and drops `aria-hidden`. When unset, the wrapper carries `aria-hidden="true"` and is invisible to assistive tech — the common case for icons inside a labeled `<button>`. */
  label?: string;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<span>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type IconProps = Readonly<IconOwnProps & Omit<ComponentProps<"span">, keyof IconOwnProps>>;

/**
 * Wrapper for caller-supplied SVG glyphs. Sizes the box and lets the SVG inherit color via `currentColor`. Decorative by default — supply `label` to make the icon meaningful. Does not ship an icon set; the consumer chooses their library (Lucide, Tabler, Heroicons, custom).
 *
 * @example Default
 * ```tsx
 * <Icon>Label</Icon>
 * ```
 *
 * @example Small
 * ```tsx
 * <Icon size="sm">Label</Icon>
 * ```
 *
 * @example Large
 * ```tsx
 * <Icon size="lg">Label</Icon>
 * ```
 */
export function Icon(props: IconProps) {
  const { size, color, label, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("span");
  const mergedClassName = mergeClass("t-icon", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      aria-label={label}
      aria-hidden={label === undefined ? "true" : undefined}
      {...responsiveDataAttrs("size", size)}
      data-color={color}
    >
      {children}
    </Component>
  );
}
