"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/image.yaml

import "@teseor/css/components/image.css";
import type { ComponentProps, Ref } from "react";
import { mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type ImageFit = "cover" | "contain" | "fill" | "none" | "scale-down";

type ImageOwnProps = {
  /** Maps to `object-fit`. Absence-of-attr leaves the default (`fill`). Responsive form (`{ base, sm, md, … }`) emits per-breakpoint `data-fit-{bp}` attrs for art-direction without `<picture>`. */
  fit?: Responsive<ImageFit>;
  children?: never;
  ref?: Ref<HTMLElementTagNameMap["img"]>;
};

export type ImageProps = Readonly<ImageOwnProps & Omit<ComponentProps<"img">, keyof ImageOwnProps>>;

/**
 * Image primitive — styled `<img>` with token-driven defaults (rounded corners, loading-state background, optional `object-fit`). Native HTML attrs (`src`, `alt`, `width`, `height`, `loading`, `decoding`, `srcset`, `sizes`) pass through the inherited type.
 *
 * @example Default
 * ```tsx
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" width={600} height={448} />
 * ```
 *
 * @example Fit Cover
 * ```tsx
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" fit="cover" width={300} height={224} />
 * ```
 *
 * @example Fit Contain
 * ```tsx
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" fit="contain" width={300} height={224} />
 * ```
 */
export function Image(props: ImageProps) {
  const { fit, children: _children, ref, className, ...rest } = props;

  const mergedClassName = mergeClass("t-image", className);

  return (
    // biome-ignore lint/a11y/useAltText: alt is forwarded via {...rest}
    <img {...rest} ref={ref} className={mergedClassName} {...responsiveDataAttrs("fit", fit)} />
  );
}
