"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/kbd.yaml

import "@teseor/css/components/kbd.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type KbdSize = "sm" | "md" | "lg";

type KbdOwnProps = {
  /** Size scale. */
  size?: Responsive<KbdSize>;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<kbd>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type KbdProps = Readonly<KbdOwnProps & Omit<ComponentProps<"kbd">, keyof KbdOwnProps>>;

/**
 * Keyboard-key primitive — styled `<kbd>` with token-driven monospace, raised-key visual, and subtle border. Single key per element; combos compose via children (`<Kbd>Cmd</Kbd>+<Kbd>K</Kbd>`).
 *
 * @example Default
 * ```tsx
 * <Kbd>Label</Kbd>
 * ```
 *
 * @example Small
 * ```tsx
 * <Kbd size="sm">Label</Kbd>
 * ```
 *
 * @example Large
 * ```tsx
 * <Kbd size="lg">Label</Kbd>
 * ```
 */
export function Kbd(props: KbdProps) {
  const { size, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("kbd");
  const mergedClassName = mergeClass("t-kbd", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("size", size)}
    >
      {children}
    </Component>
  );
}
