"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/link.yaml

import "@teseor/css/components/link.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type LinkVariant = "default" | "subtle" | "plain";

type LinkOwnProps = {
  /** Visual style. */
  variant?: LinkVariant;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<a>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type LinkProps = Readonly<LinkOwnProps & Omit<ComponentProps<"a">, keyof LinkOwnProps>>;

/**
 * Anchor primitive — styled `<a>` with token-driven color, hover, and visited treatment. Composes with native HTML attrs (`href`, `target`, `rel`, …) via the inherited type.
 *
 * @example Default
 * ```tsx
 * <Link>Label</Link>
 * ```
 *
 * @example Subtle
 * ```tsx
 * <Link variant="subtle">Label</Link>
 * ```
 *
 * @example Plain
 * ```tsx
 * <Link variant="plain">Label</Link>
 * ```
 */
export function Link(props: LinkProps) {
  const { variant, asChild, children, ref, className, ...rest } = props;

  const Component = asChild ? Slot : asElement("a");
  const mergedClassName = mergeClass("t-link", className);

  return (
    <Component {...rest} ref={ref} className={mergedClassName} data-variant={variant}>
      {children}
    </Component>
  );
}
