"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/list.yaml

import "@teseor/css/components/list.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { asElement, mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";

type ListOrdered = "false" | "true";

type ListSpacing = "compact" | "comfortable";

type ListOwnProps = {
  /** Switches the rendered tag between `<ul>` (`false`) and `<ol>` (`true`). String-typed because the byProp root descriptor (`root: { kind: byProp, ... }`) accepts string-valued controlling props only. */
  ordered?: ListOrdered;
  /** Vertical rhythm between list items. `compact` suits dense in-app surfaces (nav rails, comment threads). Default (absence-of-attr) matches the prose-friendly `comfortable` spacing — cross-framework parity requires the empty state, since the Vue generator threads `default:` into `defineProps` but React does not. */
  spacing?: Responsive<ListSpacing>;
  /** Render directly on the consumer's child element via Slot (cloneElement) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLElement>;
};

export type ListProps = Readonly<ListOwnProps & Omit<ComponentProps<"div">, keyof ListOwnProps>>;

/**
 * Ordered / unordered list primitive. Renders `<ul>` or `<ol>` based on `ordered`; styles bare `<li>` children with grid-rhythm spacing and prose-friendly markers.
 *
 * @example Default
 * ```tsx
 * <List>Label</List>
 * ```
 *
 * @example Ordered
 * ```tsx
 * <List ordered="true">Label</List>
 * ```
 *
 * @example Compact
 * ```tsx
 * <List spacing="compact">Label</List>
 * ```
 */
export function List(props: ListProps) {
  const { ordered, spacing, asChild, children, ref, className, ...rest } = props;

  const tagMap = { false: "ul", true: "ol" } as const;
  const Component = asChild ? Slot : asElement(tagMap[ordered ?? "false"]);
  const mergedClassName = mergeClass("t-list", className);

  return (
    <Component
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("spacing", spacing)}
    >
      {children}
    </Component>
  );
}
