"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/modal.yaml

import "@teseor/css/components/modal.css";
import { type CSSProperties, type ReactNode, useMemo } from "react";
import { createPortal } from "react-dom";
import { Slot } from "./components/Slot.tsx";
import { type OverlayInteraction, useOverlay } from "./hooks/useOverlay.ts";

type ModalOwnProps = {
  /** Open state. Uncontrolled by default; pass `open` and optionally `onOpenChange` to drive it from the consumer. */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Fires when the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Modal content. Plain text or rich children via slot. */
  title?: string;
  /** Render the trigger directly on the consumer's child element (`cloneElement`)
   *  instead of wrapping in a `<span>`. Single-child invariant: `children` must
   *  be a single React element. `aria-describedby`, the anchor binding, and
   *  event handlers land on that element. */
  asChild?: boolean;
  children?: ReactNode;
};

export type ModalProps = Readonly<ModalOwnProps>;

/**
 * A modal overlay that traps focus and inerts the rest of the page until dismissed.
 *
 * @example Default
 * ```tsx
 * <Modal title="Are you sure?">Label</Modal>
 * ```
 */
export function Modal(props: ModalProps) {
  const { open: openProp, defaultOpen, onOpenChange, title, children, asChild } = props;

  const interactions = useMemo<OverlayInteraction[]>(
    () => [{ on: { event: "click", target: "trigger" }, do: "toggle" }],
    [],
  );

  const overlay = useOverlay<HTMLElementTagNameMap["div"]>({
    open: openProp,
    defaultOpen,
    onOpenChange,
    anchorVar: "--t-modal-anchor",
    popoverMode: "manual",
    interactions,
    modal: true,
  });

  // `asChild` mode sets `anchor-name` directly on the consumer's element via
  // inline style (no wrapper class to read `--_anchor`). The default wrapper
  // path reads the custom property through the trigger CSS rule.
  const triggerStyle: CSSProperties = asChild
    ? ({ [overlay.anchorVar]: overlay.anchorName, anchorName: overlay.anchorName } as CSSProperties)
    : { [overlay.anchorVar]: overlay.anchorName };
  const hasContent = title != null;

  return (
    <>
      {asChild ? (
        <Slot
          style={triggerStyle}
          data-state={overlay.state}
          aria-describedby={hasContent ? overlay.popoverId : undefined}
          {...overlay.triggerHandlers}
        >
          {children}
        </Slot>
      ) : (
        <span
          className="t-modal-trigger"
          style={triggerStyle}
          data-state={overlay.state}
          aria-describedby={hasContent ? overlay.popoverId : undefined}
          {...overlay.triggerHandlers}
        >
          {children}
        </span>
      )}
      {hasContent &&
        typeof document !== "undefined" &&
        createPortal(
          <div
            ref={overlay.contentRef}
            id={overlay.popoverId}
            role="dialog"
            className="t-modal"
            popover={overlay.popoverMode}
            data-state={overlay.state}
            style={{ [overlay.anchorVar]: overlay.anchorName } satisfies CSSProperties}
          >
            {title}
          </div>,
          document.body,
        )}
    </>
  );
}
