"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/stack.yaml

import "@teseor/css/components/stack.css";
import type { ComponentProps, ReactNode, Ref } from "react";
import { responsiveDataAttrs } from "./_runtime.ts";

type StackAlign = "start" | "center" | "end" | "stretch";

type StackOwnProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
  /** Inline-axis alignment of children. */
  align?: StackAlign | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", StackAlign>>;
  children?: ReactNode;
  ref?: Ref<HTMLElementTagNameMap["div"]>;
};

export type StackProps = Readonly<StackOwnProps & Omit<ComponentProps<"div">, keyof StackOwnProps>>;

/**
 * A vertical layout primitive. Stacks children on the block axis with consistent spacing.
 *
 * @example Gap 3
 * ```tsx
 * <Stack gap="3">Label</Stack>
 * ```
 *
 * @example Gap 0
 * ```tsx
 * <Stack gap="0">Label</Stack>
 * ```
 *
 * @example Align Center
 * ```tsx
 * <Stack gap="4" align="center">Label</Stack>
 * ```
 */
export function Stack(props: StackProps) {
  const { gap, align, children, ref, className, ...rest } = props;

  const mergedClassName = className ? `t-stack ${className}` : "t-stack";

  return (
    <div
      {...rest}
      ref={ref}
      className={mergedClassName}
      {...responsiveDataAttrs("gap", gap)}
      {...responsiveDataAttrs("align", align)}
    >
      {children}
    </div>
  );
}
