"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/switch.yaml

import "@teseor/css/components/switch.css";
import type { ComponentProps, Ref } from "react";
import { mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type SwitchSize = "sm" | "md" | "lg";

type SwitchOwnProps = {
  /** Size scale. */
  size?: Responsive<SwitchSize>;
  children?: never;
  ref?: Ref<HTMLElementTagNameMap["input"]>;
};

export type SwitchProps = Readonly<
  SwitchOwnProps & Omit<ComponentProps<"input">, keyof SwitchOwnProps>
>;

/**
 * On/off toggle. Styled `<input type="checkbox" role="switch">` with a sliding thumb and three sizes. Native `checked` / `defaultChecked` / `onChange` pass through `ComponentProps<"input">`. Form-association attributes (`name`, `form`, `required`, `disabled`) come from the formControl shared contract; HTML ignores `readOnly` on checkbox inputs.
 *
 * @example Default
 * ```tsx
 * <Switch />
 * ```
 *
 * @example Checked
 * ```tsx
 * <Switch defaultChecked />
 * ```
 *
 * @example Size Sm
 * ```tsx
 * <Switch size="sm" />
 * ```
 */
export function Switch(props: SwitchProps) {
  const { size, children: _children, ref, className, ...rest } = props;

  const mergedClassName = mergeClass("t-switch", className);

  return (
    <input
      {...rest}
      ref={ref}
      className={mergedClassName}
      type="checkbox"
      // biome-ignore lint/a11y/useAriaPropsForRole: aria-checked is implicit from type="checkbox"
      role="switch"
      {...responsiveDataAttrs("size", size)}
    />
  );
}
