"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/tooltip.yaml

import "@teseor/css/components/tooltip.css";
import { type CSSProperties, type ReactNode, useMemo } from "react";
import {
  type OverlayInteraction,
  type Responsive,
  responsiveDataAttrs,
  useOverlay,
} from "./_runtime.ts";

type TooltipPlacement = "top" | "right" | "bottom" | "left";

type TooltipOwnProps = {
  /** Open state. Uncontrolled by default; pass `open` and optionally `onOpenChange` to drive it from the consumer (e.g. guided tours). */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Fires when the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Suppresses the tooltip entirely. Responsive so the tooltip can be hidden at narrow viewports (e.g. `disabled: { base: true, md: false }`). */
  disabled?: Responsive<boolean>;
  /** Milliseconds before the tooltip opens after hover or focus. Prevents flicker during cursor scanning. */
  openDelay?: number;
  /** Milliseconds before the tooltip closes after leave or blur. */
  closeDelay?: number;
  /** Tooltip content. Plain text; use Popover for interactive content. */
  text?: string;
  /** Preferred side relative to the trigger. CSS `position-try-fallbacks` auto-flips on overflow. */
  placement?: Responsive<TooltipPlacement>;
  children?: ReactNode;
};

export type TooltipProps = Readonly<TooltipOwnProps>;

/**
 * A non-interactive hint that appears when its trigger is hovered or focused.
 *
 * @example Default
 * ```tsx
 * <Tooltip text="Saves your changes.">Label</Tooltip>
 * ```
 *
 * @example Placement Right
 * ```tsx
 * <Tooltip text="Settings" placement="right">Label</Tooltip>
 * ```
 *
 * @example Placement Bottom
 * ```tsx
 * <Tooltip text="More options" placement="bottom">Label</Tooltip>
 * ```
 */
export function Tooltip(props: TooltipProps) {
  const {
    open: openProp,
    defaultOpen,
    onOpenChange,
    disabled,
    openDelay = 300,
    closeDelay = 0,
    text,
    placement,
    children,
  } = props;

  const interactions = useMemo<OverlayInteraction[]>(
    () => [
      { on: { event: "pointerenter", target: "trigger" }, do: "open", delayMs: openDelay },
      { on: { event: "focusin", target: "trigger" }, do: "open", delayMs: openDelay },
      { on: { event: "pointerleave", target: "trigger" }, do: "close", delayMs: closeDelay },
      { on: { event: "focusout", target: "trigger" }, do: "close", delayMs: closeDelay },
      { on: { event: "keydown", target: "document", key: "Escape" }, do: "close", when: "open" },
    ],
    [openDelay, closeDelay],
  );

  const overlay = useOverlay<HTMLElementTagNameMap["div"]>({
    open: openProp,
    defaultOpen,
    onOpenChange,
    anchorVar: "--t-tooltip-anchor",
    popoverMode: "manual",
    interactions,
    disabled,
  });

  const triggerStyle: CSSProperties = { [overlay.anchorVar]: overlay.anchorName };
  const hasContent = text != null;

  return (
    <>
      <span
        className="t-tooltip-trigger"
        style={triggerStyle}
        aria-describedby={hasContent ? overlay.popoverId : undefined}
        {...overlay.triggerHandlers}
      >
        {children}
      </span>
      <div
        ref={overlay.contentRef}
        id={overlay.popoverId}
        role="tooltip"
        className="t-tooltip"
        popover={overlay.popoverMode}
        style={{ [overlay.anchorVar]: overlay.anchorName } satisfies CSSProperties}
        {...responsiveDataAttrs("disabled", disabled)}
        {...responsiveDataAttrs("placement", placement)}
      >
        {text}
      </div>
    </>
  );
}
