"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/tooltip.yaml

import "@teseor/css/components/tooltip.css";
import { type CSSProperties, type ReactNode, type Ref, useMemo } from "react";
import { mergeRefs, type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.tsx";
import { type OverlayInteraction, useOverlay } from "./hooks/useOverlay.ts";

type TooltipPlacement = "top" | "right" | "bottom" | "left";

type TooltipOwnProps = {
  /** Open state. Uncontrolled by default; pass `open` and optionally `onOpenChange` to drive it from the consumer (e.g. guided tours). */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Fires when the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Suppresses the tooltip entirely. Responsive so the tooltip can be hidden at narrow viewports (e.g. `disabled: { base: true, md: false }`). */
  disabled?: Responsive<boolean>;
  /** Tooltip content. Plain text; use Popover for interactive content. */
  text?: string;
  /** Preferred side relative to the trigger. CSS `position-try-fallbacks` auto-flips on overflow. */
  placement?: Responsive<TooltipPlacement>;
  /** Milliseconds before the tooltip opens after hover or focus. Prevents flicker during cursor scanning. */
  openDelay?: number;
  /** Milliseconds before the tooltip closes after leave or blur. */
  closeDelay?: number;
  /** Render the trigger directly on the consumer's child element (`cloneElement`)
   *  instead of wrapping in a `<span>`. Single-child invariant: `children` must
   *  be a single React element. The wrapper's `style`, `data-state`, event handlers,
   *  and any ARIA attributes it applies (component-specific) land on that element. */
  asChild?: boolean;
  /** Forwarded ref to the popover content element. */
  ref?: Ref<HTMLElementTagNameMap["div"]>;
  children?: ReactNode;
};

export type TooltipProps = Readonly<TooltipOwnProps>;

/**
 * A non-interactive hint that appears when its trigger is hovered or focused.
 *
 * @example Default
 * ```tsx
 * <Tooltip text="Saves your changes.">Label</Tooltip>
 * ```
 *
 * @example Placement Right
 * ```tsx
 * <Tooltip text="Settings" placement="right">Label</Tooltip>
 * ```
 *
 * @example Placement Bottom
 * ```tsx
 * <Tooltip text="More options" placement="bottom">Label</Tooltip>
 * ```
 */
export function Tooltip(props: TooltipProps) {
  const {
    open: openProp,
    defaultOpen,
    onOpenChange,
    disabled,
    text,
    placement,
    openDelay = 300,
    closeDelay = 0,
    children,
    asChild,
    ref,
  } = props;

  const interactions = useMemo<OverlayInteraction[]>(
    () => [
      {
        on: { event: "pointerenter", target: "trigger" },
        do: "open",
        delayMs: openDelay,
        when: "!trigger.disabled",
      },
      { on: { event: "focusin", target: "trigger" }, do: "open", when: "!trigger.disabled" },
      { on: { event: "pointerleave", target: "trigger" }, do: "close", delayMs: closeDelay },
      { on: { event: "focusout", target: "trigger" }, do: "close" },
    ],
    [openDelay, closeDelay],
  );

  const overlay = useOverlay<HTMLElementTagNameMap["div"]>({
    open: openProp,
    defaultOpen,
    onOpenChange,
    anchorVar: "--t-tooltip-anchor",
    popoverMode: "manual",
    interactions,
    disabled,
  });

  // `asChild` mode sets `anchor-name` directly on the consumer's element via
  // inline style (no wrapper class to read `--_anchor`). The default wrapper
  // path reads the custom property through the trigger CSS rule.
  const triggerStyle: CSSProperties = asChild
    ? ({ [overlay.anchorVar]: overlay.anchorName, anchorName: overlay.anchorName } as CSSProperties)
    : { [overlay.anchorVar]: overlay.anchorName };
  // Memoized so React doesn't tear the ref down + back up each render.
  const mergedContentRef = useMemo(
    () => mergeRefs(ref, overlay.contentRef),
    [ref, overlay.contentRef],
  );
  const hasContent = text != null;

  return (
    <>
      {asChild ? (
        <Slot
          style={triggerStyle}
          data-state={overlay.state}
          aria-describedby={hasContent ? overlay.popoverId : undefined}
          {...overlay.triggerHandlers}
        >
          {children}
        </Slot>
      ) : (
        <span
          className="t-tooltip-trigger"
          style={triggerStyle}
          data-state={overlay.state}
          aria-describedby={hasContent ? overlay.popoverId : undefined}
          {...overlay.triggerHandlers}
        >
          {children}
        </span>
      )}
      {hasContent && (
        <div
          ref={mergedContentRef}
          id={overlay.popoverId}
          role="tooltip"
          className="t-tooltip"
          popover={overlay.popoverMode}
          data-state={overlay.state}
          style={{ [overlay.anchorVar]: overlay.anchorName } satisfies CSSProperties}
          {...responsiveDataAttrs("disabled", disabled)}
          {...responsiveDataAttrs("placement", placement)}
        >
          {text}
        </div>
      )}
    </>
  );
}
