import { describe, expect, test } from "vitest";
import type { FlatSpec } from "../../lib/flatten.ts";
import { renderContract } from "./per-spec.ts";

type SpecOverrides = Omit<Partial<FlatSpec>, "name"> & { name?: string };

function spec(overrides: SpecOverrides = {}): FlatSpec {
  return {
    name: "widget",
    kind: "atomic",
    props: {},
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderContract", () => {
  test("opens with the AUTOGENERATED banner and spec source line", () => {
    const out = renderContract(spec({ name: "widget" }));
    const lines = out.split("\n");
    expect(lines[0]).toBe("// AUTOGENERATED by gen-contract. Do not edit.");
    expect(lines[1]).toBe("// Source: specs/widget.yaml");
  });

  test("emits the empty Props alias for a spec with no props or unions", () => {
    const out = renderContract(spec({ name: "widget" }));
    expect(out).toContain("export type WidgetProps = Record<string, never>;");
  });

  test("emits a Variant union when `variants` is present", () => {
    const out = renderContract(
      spec({
        name: "btn",
        variants: { solid: { description: "" }, outline: { description: "" } },
      }),
    );
    expect(out).toContain('export type BtnVariant = "solid" | "outline";');
    expect(out).toContain("variant?: BtnVariant;");
  });

  test("only imports Responsive when at least one non-slot prop is responsive", () => {
    const responsiveOut = renderContract(
      spec({
        name: "stack",
        props: {
          gap: { type: "string", description: "Gap.", responsive: true, __part: "" },
        },
      }),
    );
    expect(responsiveOut).toContain('import type { Responsive } from "./_responsive.ts";');
    expect(responsiveOut).toContain("gap?: Responsive<string>;");

    const plainOut = renderContract(
      spec({
        name: "stack",
        props: { gap: { type: "string", description: "Gap.", __part: "" } },
      }),
    );
    expect(plainOut).not.toContain("import type { Responsive }");
  });

  test("expands a `controllable` boolean prop into the open/default/onChange triple", () => {
    const out = renderContract(
      spec({
        name: "modal",
        props: {
          open: {
            type: "boolean",
            pattern: "controllable",
            description: "Open state.",
            __part: "",
          },
        },
      }),
    );
    expect(out).toContain("open?: boolean;");
    expect(out).toContain("defaultOpen?: boolean;");
    expect(out).toContain("onOpenChange?: (open: boolean) => void;");
  });

  test("emits `unknown` for an atomic-root slot prop", () => {
    const out = renderContract(
      spec({
        name: "btn",
        props: {
          iconStart: { type: "string", description: "Leading icon.", slot: true, __part: "" },
        },
      }),
    );
    expect(out).toContain("iconStart?: unknown;");
  });

  test("emits the mapped primitive for a composite-part slot prop", () => {
    const out = renderContract(
      spec({
        name: "tooltip",
        props: {
          text: { type: "string", description: "Body text.", slot: true, __part: "content" },
        },
      }),
    );
    expect(out).toContain("text?: string;");
  });

  test("emits constraints as a JSDoc block above the Props alias", () => {
    const out = renderContract(
      spec({
        name: "btn",
        constraints: [
          { when: { variant: "outline" }, forbid: { intent: "danger" }, reason: "low contrast" },
        ],
      }),
    );
    expect(out).toContain("Runtime constraints (enforced in dev builds):");
    expect(out).toContain('when {"variant":"outline"} forbid {"intent":"danger"}');
    expect(out).toContain("low contrast");
  });

  test("merges parts sharing `groupKey:` into one Item type + one array prop", () => {
    const out = renderContract(
      spec({
        name: "tabs-list",
        kind: "composite",
        repeating: [
          {
            partName: "tab",
            propName: "items",
            element: "button",
            rootClass: "t-tabs-list-tab",
            groupKey: "items",
            itemProps: {
              label: { type: "string", slot: true, description: "Tab label." },
              active: { type: "boolean", description: "Active tab." },
            },
          },
          {
            partName: "tab-icon",
            propName: "items",
            element: "span",
            rootClass: "t-tabs-list-icon",
            groupKey: "items",
            itemProps: {
              icon: { type: "string", slot: true, description: "Tab icon." },
            },
          },
        ],
      }),
    );
    // Single shared item type, named off the singularized groupKey.
    expect(out).toContain("export type TabsListItem = {");
    expect(out).toContain("  id: string;");
    expect(out).toContain("  label?: string;");
    expect(out).toContain("  active?: boolean;");
    expect(out).toContain("  icon?: string;");
    // Single shared array prop named after the groupKey.
    expect(out).toContain("items?: ReadonlyArray<TabsListItem>;");
    // No per-part item type emitted.
    expect(out).not.toContain("TabsListTabItem");
    expect(out).not.toContain("TabsListTabIconItem");
  });

  test("emits an Item type and a ReadonlyArray prop for each repeating part", () => {
    const out = renderContract(
      spec({
        name: "pagination",
        kind: "composite",
        repeating: [
          {
            partName: "page",
            propName: "pages",
            element: "a",
            rootClass: "t-pagination-page",
            itemProps: {
              label: { type: "string", description: "Label." },
              current: { type: "boolean", description: "Active page." },
            },
          },
        ],
      }),
    );
    expect(out).toContain("export type PaginationPageItem = {");
    expect(out).toContain("id: string;");
    expect(out).toContain("label?: string;");
    expect(out).toContain("current?: boolean;");
    expect(out).toContain("pages?: ReadonlyArray<PaginationPageItem>;");
  });

  test("emits no event surface when events: is absent", () => {
    const out = renderContract(spec({ name: "btn" }));
    expect(out).not.toContain("BtnEvent");
    expect(out).not.toContain("onEvent");
  });

  test("emits per-event prop + discriminated union for a single declared event", () => {
    const out = renderContract(
      spec({
        name: "modal",
        events: {
          dismiss: {
            description: "Closed.",
            payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
          },
        },
      }),
    );
    expect(out).toContain("export type ModalEvent =");
    expect(out).toContain('| { type: "dismiss"; reason: "outside" | "escape" | "button" };');
    expect(out).toContain('onDismiss?: (e: { reason: "outside" | "escape" | "button" }) => void;');
    expect(out).toContain("onEvent?: (e: ModalEvent) => void;");
  });

  test("emits a parameterless signature for an empty-payload event", () => {
    const out = renderContract(
      spec({
        name: "search",
        events: {
          clear: { description: "Cleared.", payload: {} },
        },
      }),
    );
    expect(out).toContain('| { type: "clear" };');
    expect(out).toContain("onClear?: () => void;");
  });

  test("union includes one arm per controllable boolean mirror alongside declared events", () => {
    const out = renderContract(
      spec({
        name: "modal",
        events: {
          dismiss: { description: "Closed.", payload: {} },
        },
        props: {
          open: {
            type: "boolean",
            pattern: "controllable",
            description: "Open state.",
            __part: "",
          },
        },
      }),
    );
    expect(out).toContain('| { type: "dismiss" }');
    expect(out).toContain('| { type: "openChange"; value: boolean };');
    expect(out).toContain("onEvent?: (e: ModalEvent) => void;");
    // Existing controllable triple is still emitted.
    expect(out).toContain("onOpenChange?: (open: boolean) => void;");
  });

  test("parameterizes Props and Event with declared generics", () => {
    const out = renderContract(
      spec({
        name: "combobox",
        generics: [{ name: "Item", description: "One item." }],
        events: {
          select: {
            description: "Selected.",
            payload: {
              item: { type: "generic", ref: "Item" },
              index: { type: "number" },
            },
          },
        },
      }),
    );
    expect(out).toContain("export type ComboboxEvent<Item> =");
    expect(out).toContain('| { type: "select"; item: Item; index: number };');
    expect(out).toContain("export type ComboboxProps<Item> = {");
    expect(out).toContain("onSelect?: (e: { item: Item; index: number }) => void;");
    expect(out).toContain("onEvent?: (e: ComboboxEvent<Item>) => void;");
  });

  test("renders payload arrays, builtins, and nullable variants", () => {
    const out = renderContract(
      spec({
        name: "file-upload",
        events: {
          uploadError: {
            description: "Upload failed.",
            payload: {
              file: { type: "builtin", name: "File" },
              error: { type: "builtin", name: "Error", nullable: true },
              attempts: { type: "array", of: { type: "number" } },
            },
          },
        },
      }),
    );
    expect(out).toContain(
      "onUploadError?: (e: { file: File; error: Error | null; attempts: Array<number> }) => void;",
    );
    expect(out).toContain(
      '| { type: "uploadError"; file: File; error: Error | null; attempts: Array<number> };',
    );
  });

  test("emits multiple declared events as separate arms in the union", () => {
    const out = renderContract(
      spec({
        name: "combobox",
        events: {
          select: { description: "Selected.", payload: { value: { type: "string" } } },
          dismiss: {
            description: "Closed.",
            payload: { reason: { type: "enum", values: ["outside", "escape"] } },
          },
        },
      }),
    );
    expect(out).toContain('| { type: "select"; value: string }');
    expect(out).toContain('| { type: "dismiss"; reason: "outside" | "escape" };');
  });
});
