import { describe, expect, test } from "vitest";
import type { FlatSpec } from "../../lib/flatten.ts";
import { renderContract } from "./per-spec.ts";

type SpecOverrides = Omit<Partial<FlatSpec>, "name"> & { name?: string };

function spec(overrides: SpecOverrides = {}): FlatSpec {
  return {
    name: "widget",
    kind: "atomic",
    props: {},
    tokens: {},
    states: {},
    ...overrides,
  };
}

describe("renderContract", () => {
  test("opens with the AUTOGENERATED banner and spec source line", () => {
    const out = renderContract(spec({ name: "widget" }));
    const lines = out.split("\n");
    expect(lines[0]).toBe("// AUTOGENERATED by gen-contract. Do not edit.");
    expect(lines[1]).toBe("// Source: specs/widget.yaml");
  });

  test("emits the empty Props alias for a spec with no props or unions", () => {
    const out = renderContract(spec({ name: "widget" }));
    expect(out).toContain("export type WidgetProps = Record<string, never>;");
  });

  test("emits a Variant union when `variants` is present", () => {
    const out = renderContract(
      spec({
        name: "btn",
        variants: { solid: { description: "" }, outline: { description: "" } },
      }),
    );
    expect(out).toContain('export type BtnVariant = "solid" | "outline";');
    expect(out).toContain("variant?: BtnVariant;");
  });

  test("only imports Responsive when at least one non-slot prop is responsive", () => {
    const responsiveOut = renderContract(
      spec({
        name: "stack",
        props: {
          gap: { type: "string", description: "Gap.", responsive: true, __part: "" },
        },
      }),
    );
    expect(responsiveOut).toContain('import type { Responsive } from "./_responsive.ts";');
    expect(responsiveOut).toContain("gap?: Responsive<string>;");

    const plainOut = renderContract(
      spec({
        name: "stack",
        props: { gap: { type: "string", description: "Gap.", __part: "" } },
      }),
    );
    expect(plainOut).not.toContain("import type { Responsive }");
  });

  test("expands a `controllable` boolean prop into the open/default/onChange triple", () => {
    const out = renderContract(
      spec({
        name: "modal",
        props: {
          open: {
            type: "boolean",
            pattern: "controllable",
            description: "Open state.",
            __part: "",
          },
        },
      }),
    );
    expect(out).toContain("open?: boolean;");
    expect(out).toContain("defaultOpen?: boolean;");
    expect(out).toContain("onOpenChange?: (open: boolean) => void;");
  });

  test("emits `unknown` for an atomic-root slot prop", () => {
    const out = renderContract(
      spec({
        name: "btn",
        props: {
          iconStart: { type: "string", description: "Leading icon.", slot: true, __part: "" },
        },
      }),
    );
    expect(out).toContain("iconStart?: unknown;");
  });

  test("emits the mapped primitive for a composite-part slot prop", () => {
    const out = renderContract(
      spec({
        name: "tooltip",
        props: {
          text: { type: "string", description: "Body text.", slot: true, __part: "content" },
        },
      }),
    );
    expect(out).toContain("text?: string;");
  });

  test("emits constraints as a JSDoc block above the Props alias", () => {
    const out = renderContract(
      spec({
        name: "btn",
        constraints: [
          { when: { variant: "outline" }, forbid: { intent: "danger" }, reason: "low contrast" },
        ],
      }),
    );
    expect(out).toContain("Runtime constraints (enforced in dev builds):");
    expect(out).toContain('when {"variant":"outline"} forbid {"intent":"danger"}');
    expect(out).toContain("low contrast");
  });
});
