import { describe, expect, test } from "vitest";
import type { FlatSpec } from "../../lib/flatten.ts";
import { renderContract } from "./per-spec.ts";

type SpecOverrides = Omit<Partial<FlatSpec>, "name"> & { name?: string };

function spec(overrides: SpecOverrides = {}): FlatSpec {
  return {
    name: "widget",
    kind: "atomic",
    props: {},
    tokens: {},
    states: {},
    ...overrides,
  };
}

describe("renderContract", () => {
  test("opens with the AUTOGENERATED banner and spec source line", () => {
    const out = renderContract(spec({ name: "widget" }));
    const lines = out.split("\n");
    expect(lines[0]).toBe("// AUTOGENERATED by gen-contract. Do not edit.");
    expect(lines[1]).toBe("// Source: specs/widget.yaml");
  });

  test("emits the empty Props alias for a spec with no props or unions", () => {
    const out = renderContract(spec({ name: "widget" }));
    expect(out).toContain("export type WidgetProps = Record<string, never>;");
  });

  test("emits a Variant union when `variants` is present", () => {
    const out = renderContract(
      spec({
        name: "btn",
        variants: { solid: { description: "" }, outline: { description: "" } },
      }),
    );
    expect(out).toContain('export type BtnVariant = "solid" | "outline";');
    expect(out).toContain("variant?: BtnVariant;");
  });

  test("only imports Responsive when at least one non-slot prop is responsive", () => {
    const responsiveOut = renderContract(
      spec({
        name: "stack",
        props: {
          gap: { type: "string", description: "Gap.", responsive: true, __part: "" },
        },
      }),
    );
    expect(responsiveOut).toContain('import type { Responsive } from "./_responsive.ts";');
    expect(responsiveOut).toContain("gap?: Responsive<string>;");

    const plainOut = renderContract(
      spec({
        name: "stack",
        props: { gap: { type: "string", description: "Gap.", __part: "" } },
      }),
    );
    expect(plainOut).not.toContain("import type { Responsive }");
  });

  test("expands a `controllable` boolean prop into the open/default/onChange triple", () => {
    const out = renderContract(
      spec({
        name: "modal",
        props: {
          open: {
            type: "boolean",
            pattern: "controllable",
            description: "Open state.",
            __part: "",
          },
        },
      }),
    );
    expect(out).toContain("open?: boolean;");
    expect(out).toContain("defaultOpen?: boolean;");
    expect(out).toContain("onOpenChange?: (open: boolean) => void;");
  });

  test("emits `unknown` for an atomic-root slot prop", () => {
    const out = renderContract(
      spec({
        name: "btn",
        props: {
          iconStart: { type: "string", description: "Leading icon.", slot: true, __part: "" },
        },
      }),
    );
    expect(out).toContain("iconStart?: unknown;");
  });

  test("emits the mapped primitive for a composite-part slot prop", () => {
    const out = renderContract(
      spec({
        name: "tooltip",
        props: {
          text: { type: "string", description: "Body text.", slot: true, __part: "content" },
        },
      }),
    );
    expect(out).toContain("text?: string;");
  });

  test("emits constraints as a JSDoc block above the Props alias", () => {
    const out = renderContract(
      spec({
        name: "btn",
        constraints: [
          { when: { variant: "outline" }, forbid: { intent: "danger" }, reason: "low contrast" },
        ],
      }),
    );
    expect(out).toContain("Runtime constraints (enforced in dev builds):");
    expect(out).toContain('when {"variant":"outline"} forbid {"intent":"danger"}');
    expect(out).toContain("low contrast");
  });

  test("merges parts sharing `groupKey:` into one Item type + one array prop (RFC-0005)", () => {
    const out = renderContract(
      spec({
        name: "tabs-list",
        kind: "composite",
        repeating: [
          {
            partName: "tab",
            propName: "items",
            element: "button",
            rootClass: "t-tabs-list-tab",
            groupKey: "items",
            itemProps: {
              label: { type: "string", slot: true, description: "Tab label." },
              active: { type: "boolean", description: "Active tab." },
            },
          },
          {
            partName: "tab-icon",
            propName: "items",
            element: "span",
            rootClass: "t-tabs-list-icon",
            groupKey: "items",
            itemProps: {
              icon: { type: "string", slot: true, description: "Tab icon." },
            },
          },
        ],
      }),
    );
    // Single shared item type, named off the singularized groupKey.
    expect(out).toContain("export type TabsListItem = {");
    expect(out).toContain("  id: string;");
    expect(out).toContain("  label?: string;");
    expect(out).toContain("  active?: boolean;");
    expect(out).toContain("  icon?: string;");
    // Single shared array prop named after the groupKey.
    expect(out).toContain("items?: ReadonlyArray<TabsListItem>;");
    // No per-part item type emitted.
    expect(out).not.toContain("TabsListTabItem");
    expect(out).not.toContain("TabsListTabIconItem");
  });

  test("emits an Item type and a ReadonlyArray prop for each repeating part (RFC-0005)", () => {
    const out = renderContract(
      spec({
        name: "pagination",
        kind: "composite",
        repeating: [
          {
            partName: "page",
            propName: "pages",
            element: "a",
            rootClass: "t-pagination-page",
            itemProps: {
              label: { type: "string", description: "Label." },
              current: { type: "boolean", description: "Active page." },
            },
          },
        ],
      }),
    );
    expect(out).toContain("export type PaginationPageItem = {");
    expect(out).toContain("id: string;");
    expect(out).toContain("label?: string;");
    expect(out).toContain("current?: boolean;");
    expect(out).toContain("pages?: ReadonlyArray<PaginationPageItem>;");
  });
});
