// AUTOGENERATED by gen-vue. Do not edit.

import {
  computed,
  onBeforeUnmount,
  onMounted,
  type Ref,
  ref,
  type ShallowRef,
  shallowRef,
  useId,
  watch,
} from "vue";

const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;

type Breakpoint = (typeof RESPONSIVE_KEYS)[number];

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;

export function responsiveDataAttrs(
  name: string,
  value: unknown,
): Record<string, string | undefined> {
  if (value == null || value === false) return {};
  if (typeof value === "object") {
    // Responsive object: emit every declared breakpoint, including `false`.
    // The CSS for responsive overrides reads explicit `data-${name}-${bp}`
    // attributes (e.g. `[data-disabled-md="false"]` reverts the base
    // `[data-disabled="true"]` at md+); dropping `false` here breaks the
    // override and the base value sticks across every breakpoint.
    const obj = value as Record<string, unknown>;
    const out: Record<string, string | undefined> = {};
    for (const key of RESPONSIVE_KEYS) {
      const v = obj[key];
      if (v == null) continue;
      // Drop `false` only at the `base` slot — its CSS rule is "absence of
      // the attribute"; emitting `data-disabled="false"` would never match.
      if (key === "base" && v === false) continue;
      const attr = key === "base" ? `data-${name}` : `data-${name}-${key}`;
      out[attr] = v === true ? "true" : v === false ? "false" : String(v);
    }
    return out;
  }
  return { [`data-${name}`]: value === true ? "true" : String(value) };
}

// ── Overlay composable — used by composite overlay components ──────────────

type OverlayInteraction = {
  on: { event: string; target?: string; key?: string };
  do: "open" | "close" | "toggle";
  /** ms delay before the action fires. Function form lets the wrapper pass a
   *  reactive getter (e.g. `() => openDelay`) so the latest prop value is
   *  read on every fire; Vue's setup runs once so a plain number would
   *  capture the value at setup-time and miss later prop changes. */
  delayMs?: number | (() => number);
  when?: string;
};

type OverlayConfig = {
  /** Reactive getter for the controlled `open` prop. Passed as a function
   *  so the composable re-reads it via `config.open()` on every render —
   *  capturing the value at setup-time (Vue's setup runs once) would lose
   *  every later parent prop change. `undefined` means uncontrolled. */
  open?: () => boolean | undefined;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  anchorVar: string;
  popoverMode: "auto" | "manual" | "hint";
  interactions: ReadonlyArray<OverlayInteraction>;
  /** Reactive getter for plain-boolean `disabled`. When it returns `true`,
   *  every `schedule` call no-ops: state doesn't flip, `onOpenChange` doesn't
   *  fire. Responsive `disabled` is handled at the CSS layer via
   *  `data-disabled-bp` attributes. */
  disabled?: () => boolean;
};

type OverlayHandlers = Record<string, (event: Event) => void>;

type OverlayReturn = {
  open: Readonly<Ref<boolean>>;
  setOpen: (next: boolean) => void;
  anchorName: string;
  anchorVar: string;
  popoverId: string;
  popoverMode: "auto" | "manual" | "hint";
  /** Vue's template-ref machinery assigns the DOM element here; consumers
   *  bind via `ref="contentRef"` in their template. */
  contentRef: ShallowRef<HTMLElement | null>;
  triggerHandlers: OverlayHandlers;
};

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "");
}

/** Probe `:popover-open` once and reuse. Older browsers that ship Popover
 *  API but not the selector throw `SyntaxError` from `Element.matches`; the
 *  feature query lets us skip the call entirely on those engines.
 *  `undefined` means "selector unavailable, fall through and let
 *  `showPopover`/`hidePopover` decide". */
const SUPPORTS_POPOVER_OPEN_SELECTOR =
  typeof CSS !== "undefined" &&
  typeof CSS.supports === "function" &&
  CSS.supports("selector(:popover-open)");

function popoverIsOpen(node: HTMLElement): boolean | undefined {
  if (!SUPPORTS_POPOVER_OPEN_SELECTOR) return undefined;
  try {
    return node.matches(":popover-open");
  } catch {
    return undefined;
  }
}

/**
 * Drives the state machine, popover toggling, anchor binding, and event
 * wiring for composite overlay components in Vue. Mirror of `useOverlay` in
 * `@teseor/react`; both consume the same spec-derived config.
 */
export function useOverlay(config: OverlayConfig): OverlayReturn {
  const internalOpen = ref<boolean>(config.defaultOpen ?? false);
  // Re-evaluated each render via the getter pattern. When the consumer's
  // `open` prop changes, the computed re-runs and the popover state updates.
  const open = computed<boolean>(() => {
    const fromProp = config.open?.();
    return fromProp !== undefined ? fromProp : internalOpen.value;
  });

  const setOpen = (next: boolean) => {
    const fromProp = config.open?.();
    if (fromProp === undefined) internalOpen.value = next;
    config.onOpenChange?.(next);
  };

  const idCore = sanitizeId(useId());
  const anchorName = `--t-${idCore}`;
  const popoverId = `t-overlay-${idCore}`;

  const contentRef = shallowRef<HTMLElement | null>(null);

  let openTimer = 0;
  let closeTimer = 0;
  const clearTimers = () => {
    if (openTimer) window.clearTimeout(openTimer);
    if (closeTimer) window.clearTimeout(closeTimer);
    openTimer = 0;
    closeTimer = 0;
  };

  const schedule = (action: "open" | "close" | "toggle", delayMs: number) => {
    // No-op when the wrapper passed `disabled: () => true`. Reads the getter
    // each call so the latest prop value gates the state transition.
    if (config.disabled?.() === true) return;
    clearTimers();
    const next = action === "toggle" ? !open.value : action === "open";
    if (delayMs <= 0) {
      setOpen(next);
      return;
    }
    if (action === "close") {
      closeTimer = window.setTimeout(() => setOpen(next), delayMs);
    } else {
      openTimer = window.setTimeout(() => setOpen(next), delayMs);
    }
  };

  onBeforeUnmount(() => clearTimers());

  // Sync popover state with the reactive `open` value. `immediate: true`
  // ensures the initial `defaultOpen: true` / controlled `open: true` calls
  // `showPopover()` after the first mount instead of waiting for a change.
  // `flush: 'post'` defers each callback to after the DOM update, so the
  // popover element exists when we toggle it.
  // `popoverIsOpen` may return `undefined` on engines without
  // `:popover-open`; in that case we attempt the transition and let
  // `showPopover`/`hidePopover` throw harmlessly on invalid state.
  watch(
    open,
    (current) => {
      const node = contentRef.value;
      if (!node) return;
      const popoverState = popoverIsOpen(node);
      if (current && popoverState !== true) {
        try {
          node.showPopover();
        } catch {
          // Popover API unsupported, display:none, or already open — degrade silently.
        }
      } else if (!current && popoverState !== false) {
        try {
          node.hidePopover();
        } catch {
          // Popover API unsupported or already closed — degrade silently.
        }
      }
    },
    { immediate: true, flush: "post" },
  );

  // Resolve a rule's delay at fire-time so getter-form delays (the wrapper
  // passes `delayMs: () => openDelay`) pick up the latest prop value.
  const resolveDelay = (d: number | (() => number) | undefined): number => {
    if (d === undefined) return 0;
    return typeof d === "function" ? d() : d;
  };

  // Document/window-bound interactions. Listeners attach on mount and unmount.
  const cleanups: Array<() => void> = [];
  onMounted(() => {
    for (const rule of config.interactions) {
      const target = rule.on.target;
      if (target !== "document" && target !== "window") continue;
      const sink: EventTarget = target === "document" ? document : window;
      const handler = (event: Event) => {
        if (rule.when === "open" && !open.value) return;
        if (rule.on.key && event instanceof KeyboardEvent && event.key !== rule.on.key) return;
        schedule(rule.do, resolveDelay(rule.delayMs));
      };
      sink.addEventListener(rule.on.event, handler);
      cleanups.push(() => sink.removeEventListener(rule.on.event, handler));
    }
  });
  onBeforeUnmount(() => {
    for (const fn of cleanups) fn();
  });

  // Trigger-bound handlers spread via `v-on` onto the wrapper element.
  // Keys are bare event names (`pointerenter`, not `onPointerenter`); Vue's
  // v-on directive handles the listener registration. Each rule respects
  // its own `when` state guard and `on.key` filter — same semantics as the
  // document/window-bound branch above.
  const triggerHandlers: OverlayHandlers = {};
  for (const rule of config.interactions) {
    if (rule.on.target !== "trigger") continue;
    const eventName = rule.on.event;
    const previous = triggerHandlers[eventName];
    triggerHandlers[eventName] = (event: Event) => {
      previous?.(event);
      if (rule.when === "open" && !open.value) return;
      if (rule.on.key) {
        if (!(event instanceof KeyboardEvent) || event.key !== rule.on.key) return;
      }
      schedule(rule.do, resolveDelay(rule.delayMs));
    };
  }

  return {
    open,
    setOpen,
    anchorName,
    anchorVar: config.anchorVar,
    popoverId,
    popoverMode: config.popoverMode,
    contentRef,
    triggerHandlers,
  };
}
