// AUTOGENERATED by gen-vue. Do not edit.

import {
  computed,
  onBeforeUnmount,
  onMounted,
  type Ref,
  ref,
  type ShallowRef,
  shallowRef,
  useId,
  watch,
} from "vue";

const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;

type Breakpoint = (typeof RESPONSIVE_KEYS)[number];

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;

export function responsiveDataAttrs(
  name: string,
  value: unknown,
): Record<string, string | undefined> {
  if (value == null || value === false) return {};
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, string | undefined> = {};
    for (const key of RESPONSIVE_KEYS) {
      const v = obj[key];
      if (v == null || v === false) continue;
      const attr = key === "base" ? `data-${name}` : `data-${name}-${key}`;
      out[attr] = v === true ? "true" : String(v);
    }
    return out;
  }
  return { [`data-${name}`]: value === true ? "true" : String(value) };
}

// ── Overlay composable — used by composite overlay components ──────────────

type OverlayInteraction = {
  on: { event: string; target?: string; key?: string };
  do: "open" | "close" | "toggle";
  delayMs?: number;
  when?: string;
};

type OverlayConfig = {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  anchorVar: string;
  popoverMode: "auto" | "manual" | "hint";
  interactions: ReadonlyArray<OverlayInteraction>;
};

type OverlayHandlers = Record<string, (event: Event) => void>;

type OverlayReturn = {
  open: Readonly<Ref<boolean>>;
  setOpen: (next: boolean) => void;
  anchorName: string;
  anchorVar: string;
  popoverId: string;
  popoverMode: "auto" | "manual" | "hint";
  /** Vue's template-ref machinery assigns the DOM element here; consumers
   *  bind via `ref="contentRef"` in their template. */
  contentRef: ShallowRef<HTMLElement | null>;
  triggerHandlers: OverlayHandlers;
};

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "");
}

/**
 * Drives the state machine, popover toggling, anchor binding, and event
 * wiring for composite overlay components in Vue. Mirror of `useOverlay` in
 * `@teseor/react`; both consume the same spec-derived config.
 */
export function useOverlay(config: OverlayConfig): OverlayReturn {
  const controlled = config.open !== undefined;
  const internalOpen = ref<boolean>(config.defaultOpen ?? false);
  const open = computed<boolean>(() =>
    controlled ? Boolean(config.open) : internalOpen.value,
  );

  const setOpen = (next: boolean) => {
    if (!controlled) internalOpen.value = next;
    config.onOpenChange?.(next);
  };

  const idCore = sanitizeId(useId());
  const anchorName = `--t-${idCore}`;
  const popoverId = `t-overlay-${idCore}`;

  const contentRef = shallowRef<HTMLElement | null>(null);

  let openTimer = 0;
  let closeTimer = 0;
  const clearTimers = () => {
    if (openTimer) window.clearTimeout(openTimer);
    if (closeTimer) window.clearTimeout(closeTimer);
    openTimer = 0;
    closeTimer = 0;
  };

  const schedule = (action: "open" | "close" | "toggle", delayMs: number) => {
    clearTimers();
    const next = action === "toggle" ? !open.value : action === "open";
    if (delayMs <= 0) {
      setOpen(next);
      return;
    }
    if (action === "close") {
      closeTimer = window.setTimeout(() => setOpen(next), delayMs);
    } else {
      openTimer = window.setTimeout(() => setOpen(next), delayMs);
    }
  };

  onBeforeUnmount(() => clearTimers());

  // Sync popover state with the reactive `open` value.
  watch(open, (current) => {
    const node = contentRef.value;
    if (!node) return;
    if (current && !node.matches(":popover-open")) {
      try {
        node.showPopover();
      } catch {
        // Popover API unsupported or display:none — degrade silently.
      }
    } else if (!current && node.matches(":popover-open")) {
      try {
        node.hidePopover();
      } catch {
        // Popover API unsupported — degrade silently.
      }
    }
  });

  // Document/window-bound interactions. Listeners attach on mount and unmount.
  const cleanups: Array<() => void> = [];
  onMounted(() => {
    for (const rule of config.interactions) {
      const target = rule.on.target;
      if (target !== "document" && target !== "window") continue;
      const sink: EventTarget = target === "document" ? document : window;
      const handler = (event: Event) => {
        if (rule.when === "open" && !open.value) return;
        if (rule.on.key && event instanceof KeyboardEvent && event.key !== rule.on.key) return;
        schedule(rule.do, rule.delayMs ?? 0);
      };
      sink.addEventListener(rule.on.event, handler);
      cleanups.push(() => sink.removeEventListener(rule.on.event, handler));
    }
  });
  onBeforeUnmount(() => {
    for (const fn of cleanups) fn();
  });

  // Trigger-bound handlers spread via `v-on` onto the wrapper element.
  // Keys are bare event names (`pointerenter`, not `onPointerenter`); Vue's
  // v-on directive handles the listener registration.
  const triggerHandlers: OverlayHandlers = {};
  for (const rule of config.interactions) {
    if (rule.on.target !== "trigger") continue;
    const eventName = rule.on.event;
    const previous = triggerHandlers[eventName];
    const delayMs = rule.delayMs ?? 0;
    triggerHandlers[eventName] = (event: Event) => {
      previous?.(event);
      schedule(rule.do, delayMs);
    };
  }

  return {
    open,
    setOpen,
    anchorName,
    anchorVar: config.anchorVar,
    popoverId,
    popoverMode: config.popoverMode,
    contentRef,
    triggerHandlers,
  };
}
