<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/avatar.yaml -->
<script setup lang="ts">
/**
 * Image container with name/initials/icon fallback chain. Renders `<img>` when `src` is set and loads successfully; falls back to initials (when `name` is provided) or an empty muted box when nothing else fits. Atomic primitive.
 *
 * @example Image
 * ```vue
 * <Avatar src="/img/avatar-jane.jpg" alt="Jane Doe" name="Jane Doe">Label</Avatar>
 * ```
 *
 * @example Initials
 * ```vue
 * <Avatar name="Jane Doe">Label</Avatar>
 * ```
 *
 * @example Initials Single
 * ```vue
 * <Avatar name="Madonna">Label</Avatar>
 * ```
 */
import "@teseor/css/components/avatar.css";
import { computed, ref, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs, deriveInitials } from "./_runtime.ts";

type AvatarSize = "sm" | "md" | "lg";

type AvatarShape = "circle" | "square";

type AvatarColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type AvatarProps = {
  /** Size scale. */
  size?: Responsive<AvatarSize>;
  /** Image source URL. When set and the image loads, the avatar renders `<img>`. On `onError`, falls back to the initials or empty box. */
  src?: string;
  /** Alt text for the image. Required when `src` is set and the image carries standalone meaning; empty string when the avatar is decorative inside a labeled context. */
  alt?: string;
  /** Person's name. Drives the auto-derived initials fallback when `src` is missing or fails to load. */
  name?: string;
  /** Explicit initials override. When set, wins over the auto-derived "first letter of first + last whitespace-split token" rule. */
  initials?: string;
  /** Outer corner shape. Default is `circle` via the CSS layer (absence-of-attr). */
  shape?: AvatarShape;
  /** Semantic background color of the fallback (initials or empty) box. Default is `neutral` via the CSS layer. */
  color?: AvatarColor;
};

const {
  size,
  src,
  alt = "",
  name,
  initials,
  shape,
  color,
} = defineProps<AvatarProps>();

defineSlots<{
  default?(): VNode[];
}>();

const imgErrored = ref<boolean>(false);

const attrs = computed(() => ({
  ...responsiveDataAttrs("size", size),
  "data-shape": shape,
  "data-color": color,
}));
</script>

<template>
  <span class="t-avatar" v-bind="attrs">
    <img v-if="(src) && (!imgErrored)" :src="src" :alt="alt" @error="imgErrored = true" />
    <span v-else-if="name">{{ deriveInitials(name, initials) }}</span>
    <span v-else />
  </span>
</template>
