<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/blockquote.yaml -->
<script setup lang="ts">
/**
 * Quoted-text primitive — styled `<blockquote>` with accent border and prose spacing. Source attribution composes via a `<cite>` child; native `cite` HTML attr (URL) passes through the inherited type.
 *
 * @example Default
 * ```vue
 * <Blockquote>Label</Blockquote>
 * ```
 *
 * @example Subtle
 * ```vue
 * <Blockquote variant="subtle">Label</Blockquote>
 * ```
 */
import "@teseor/css/components/blockquote.css";
import { computed, type VNode } from "vue";
import { Slot } from "./components/Slot.ts";

type BlockquoteVariant = "default" | "subtle";

type BlockquoteProps = {
  /** Visual style. */
  variant?: BlockquoteVariant;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<blockquote>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  variant,
  asChild,
} = defineProps<BlockquoteProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  "data-variant": variant,
}));
</script>

<template>
  <component :is="asChild ? Slot : 'blockquote'" class="t-blockquote" v-bind="attrs">
    <slot />
  </component>
</template>
