<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/button.yaml -->
<script setup lang="ts">
/**
 * A trigger that performs an action when activated.
 *
 * @example Solid Primary
 * ```vue
 * <Button variant="solid" intent="primary">Label</Button>
 * ```
 *
 * @example Solid Danger Md
 * ```vue
 * <Button variant="solid" intent="danger" size="md">Label</Button>
 * ```
 *
 * @example Outline Neutral
 * ```vue
 * <Button variant="outline" intent="neutral">Label</Button>
 * ```
 */
import "@teseor/css/components/button.css";
import { computed } from "vue";
import { dataAttrs } from "./_runtime.ts";

type ButtonVariant = "solid" | "outline" | "ghost" | "link";

type ButtonIntent = "primary" | "neutral" | "success" | "warning" | "danger";

type ButtonSize = "sm" | "md" | "lg";

type ButtonProps = {
  /** Visual style. */
  variant?: ButtonVariant;
  /** Semantic color. */
  intent?: ButtonIntent;
  /** Size scale. */
  size?: ButtonSize | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", ButtonSize>>;
  /** Polymorphic root element. Defaults to `button`; set to `a` for link-shaped triggers (paired with `variant: link`). */
  as?: string;
  /** Disables interaction and applies the disabled visual state. Mapped to the native `disabled` attribute on `button`, `aria-disabled="true"` otherwise. */
  disabled?: boolean;
  /** Shows a spinner in place of the label and disables interaction. The original label stays in the accessibility tree. */
  loading?: boolean;
  /** Stretches the button to the inline-size of its container. Responsive so layouts can pin block-width on mobile and shrink to content above. */
  block?: boolean | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", boolean>>;
};

const {
  variant,
  intent,
  size,
  as = "button",
  disabled = false,
  loading = false,
  block = false,
} = defineProps<ButtonProps>();

defineSlots<{
  default?(): any;
  iconStart?(): any;
  iconEnd?(): any;
}>();

const isButton = computed(() => as === "button");
const inactive = computed(() => disabled || loading);

const attrs = computed(() => ({
  "data-variant": variant,
  "data-intent": intent,
  ...dataAttrs("size", size),
  ...dataAttrs("block", block),
  "data-loading": loading ? "true" : undefined,
  disabled: isButton.value ? inactive.value : undefined,
  "aria-disabled": !isButton.value && inactive.value ? "true" : undefined,
  "aria-busy": loading ? "true" : undefined,
}));
</script>

<template>
  <component :is="as" class="t-button" v-bind="attrs">
    <span v-if="$slots.iconStart" data-button-icon="" data-position="start">
      <slot name="iconStart" />
    </span>
    <span data-button-label=""><slot /></span>
    <span v-if="$slots.iconEnd" data-button-icon="" data-position="end">
      <slot name="iconEnd" />
    </span>
    <span data-button-spinner="" aria-hidden="true" />
  </component>
</template>
