<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/center.yaml -->
<script setup lang="ts">
/**
 * A layout primitive that centers a single child on both axes. Pure CSS, no children styling. `minHeight` is unset by default — the centered box hugs its child; pass `screen` for splash-screen / hero patterns or override `--t-center-min-height` for custom values.
 *
 * @example Default
 * ```vue
 * <Center>Label</Center>
 * ```
 *
 * @example Screen
 * ```vue
 * <Center minHeight="screen">Label</Center>
 * ```
 *
 * @example Responsive
 * ```vue
 * <Center :minHeight='{"md":"screen"}'>Label</Center>
 * ```
 */
import "@teseor/css/components/center.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type CenterMinHeight = "screen";

type CenterProps = {
  /** Minimum block size. `screen` maps to 100dvh (splash-screen / hero pattern). Leave unset to center inside the parent's flow. Custom values: override `--t-center-min-height` on the element. */
  minHeight?: Responsive<CenterMinHeight>;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  minHeight,
  asChild,
} = defineProps<CenterProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  ...responsiveDataAttrs("min-height", minHeight),
}));
</script>

<template>
  <component :is="asChild ? Slot : 'div'" class="t-center" v-bind="attrs">
    <slot />
  </component>
</template>
