<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/checkbox.yaml -->
<script setup lang="ts">
/**
 * Binary toggle (or tri-state via `indeterminate`). Styled `<input type="checkbox">` with a painted check / dash glyph and three sizes. Native `checked` / `defaultChecked` / `onChange` pass through `ComponentProps<"input">`. Form-association attributes (`name`, `form`, `required`, `disabled`) come from the formControl shared contract; HTML ignores `readOnly` on checkbox inputs.
 *
 * @example Default
 * ```vue
 * <Checkbox />
 * ```
 *
 * @example Checked
 * ```vue
 * <Checkbox defaultChecked />
 * ```
 *
 * @example Indeterminate
 * ```vue
 * <Checkbox indeterminate />
 * ```
 */
import "@teseor/css/components/checkbox.css";
import { computed, useTemplateRef, watch, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type CheckboxSize = "sm" | "md" | "lg";

type CheckboxProps = {
  /** Size scale. */
  size?: Responsive<CheckboxSize>;
  /** When true, displays the mixed (indeterminate) state. Native `<input>.indeterminate` has no HTML attribute; the wrapper sets it imperatively after mount. */
  indeterminate?: boolean;
};

const {
  size,
  indeterminate,
} = defineProps<CheckboxProps>();

defineSlots<{
}>();

const rootRef = useTemplateRef<HTMLElementTagNameMap['input']>("rootRef");
watch(() => indeterminate, (value) => {
  if (rootRef.value) rootRef.value.indeterminate = value ?? false;
}, { immediate: true, flush: "post" });

const attrs = computed(() => ({
  "type": "checkbox",
  ...responsiveDataAttrs("size", size),
}));
</script>

<template>
  <input class="t-checkbox" v-bind="attrs" ref="rootRef" />
</template>
