<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/cluster.yaml -->
<script setup lang="ts">
/**
 * A horizontal layout primitive. Wraps children on the inline axis with consistent spacing.
 *
 * @example Gap 3
 * ```vue
 * <Cluster gap="3">Label</Cluster>
 * ```
 *
 * @example Gap 0
 * ```vue
 * <Cluster gap="0">Label</Cluster>
 * ```
 *
 * @example Justify Between
 * ```vue
 * <Cluster gap="3" justify="between">Label</Cluster>
 * ```
 */
import "@teseor/css/components/cluster.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type ClusterAlign = "start" | "center" | "end" | "stretch" | "baseline";

type ClusterJustify = "start" | "center" | "end" | "between" | "around";

type ClusterProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: Responsive<string>;
  /** Block-axis alignment of children. */
  align?: Responsive<ClusterAlign>;
  /** Inline-axis distribution of children. */
  justify?: Responsive<ClusterJustify>;
};

const {
  gap,
  align,
  justify,
} = defineProps<ClusterProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  ...responsiveDataAttrs("gap", gap),
  ...responsiveDataAttrs("align", align),
  ...responsiveDataAttrs("justify", justify),
}));
</script>

<template>
  <div class="t-cluster" v-bind="attrs">
    <slot />
  </div>
</template>
