<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/codeblock.yaml -->
<script setup lang="ts">
/**
 * Block container for multi-line code with monospace font and horizontal overflow scroll.
 *
 * @example Default
 * ```vue
 * <Codeblock>Label</Codeblock>
 * ```
 */
import "@teseor/css/components/codeblock.css";
import { computed, type VNode } from "vue";


type CodeblockProps = {
};

defineProps<CodeblockProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({

}));
</script>

<template>
  <pre class="t-codeblock" v-bind="attrs">
  <code>
    <slot />
  </code>
  </pre>
</template>
