<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/code.yaml -->
<script setup lang="ts">
/**
 * Inline monospace fragment for short code spans in prose.
 *
 * @example Default
 * ```vue
 * <Code>Label</Code>
 * ```
 */
import "@teseor/css/components/code.css";
import { computed, type VNode } from "vue";


type CodeProps = {
};

defineProps<CodeProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({

}));
</script>

<template>
  <code class="t-code" v-bind="attrs">
    <slot />
  </code>
</template>
