<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/divider.yaml -->
<script setup lang="ts">
/**
 * Horizontal-or-vertical visual rule. Renders `<hr>` for the horizontal orientation (native `role="separator"`) and `<div role="separator" aria-orientation="vertical">` for the vertical one. The `decorative` prop hides the element from the accessibility tree (`role="none"` + `aria-hidden="true"`).
 *
 * @example Default
 * ```vue
 * <Divider>Label</Divider>
 * ```
 *
 * @example Vertical
 * ```vue
 * <Divider orientation="vertical">Label</Divider>
 * ```
 *
 * @example Decorative
 * ```vue
 * <Divider decorative>Label</Divider>
 * ```
 */
import "@teseor/css/components/divider.css";
import { computed, type VNode } from "vue";
import { Slot } from "./components/Slot.ts";

type DividerOrientation = "horizontal" | "vertical";

type DividerProps = {
  /** Axis of the rule. Absence-of-attr selects `horizontal` — codegen falls back to the first map key and the `<hr>` carries the native horizontal orientation. Pass `vertical` to render a `<div>` with explicit `role="separator"` + `aria-orientation="vertical"`. */
  orientation?: DividerOrientation;
  /** Removes the divider from the accessibility tree (`role="none"` + `aria-hidden="true"`). Use when the rule is purely visual and not announcing a structural boundary. */
  decorative?: boolean;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  orientation,
  decorative,
  asChild,
} = defineProps<DividerProps>();

defineSlots<{
  default?(): VNode[];
}>();

const tagMap = { "horizontal": "hr", "vertical": "div" } as const;
const resolvedTag = computed(() => tagMap[orientation ?? 'horizontal']);
const isVoidResolved = computed(() => resolvedTag.value === 'hr');

const attrs = computed(() => ({
  role: decorative ? "none" : "separator",
  "aria-orientation": orientation,
  "aria-hidden": decorative ? "true" : undefined,
  "data-decorative": decorative ? "true" : undefined,
}));
</script>

<template>
  <template v-if="isVoidResolved">
    <component :is="asChild && !isVoidResolved ? Slot : resolvedTag" class="t-divider" v-bind="attrs" />
  </template>
  <template v-else>
    <component :is="asChild && !isVoidResolved ? Slot : resolvedTag" class="t-divider" v-bind="attrs">
    <slot />
    </component>
  </template>
</template>
