<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/dot.yaml -->
<script setup lang="ts">
/**
 * Single-color presence indicator. Decorative by default — emits `role="none"` and `aria-hidden="true"`. Supply `label` to make the dot meaningful (`role="img"` + `aria-label`). Pair with adjacent text or an Avatar for status overlays.
 *
 * @example Default
 * ```vue
 * <Dot>Label</Dot>
 * ```
 *
 * @example Success
 * ```vue
 * <Dot color="success">Label</Dot>
 * ```
 *
 * @example Small
 * ```vue
 * <Dot size="sm">Label</Dot>
 * ```
 */
import "@teseor/css/components/dot.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type DotSize = "sm" | "md";

type DotColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type DotStatus = "online" | "offline" | "away" | "busy" | "idle";

type DotProps = {
  /** Size scale. */
  size?: Responsive<DotSize>;
  /** Semantic color. Absence-of-attr renders the neutral base styling. */
  color?: DotColor;
  /** Sugar prop for common presence states. Emits `data-status` so status-driven styling can override `color`. Independent of `color` — the two compose. */
  status?: DotStatus;
  /** Accessible label. When set, the dot becomes meaningful (`role="img"` + `aria-label={label}`); when unset, the dot is decorative (`role="none"` + `aria-hidden="true"`). */
  label?: string;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<span>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  size,
  color,
  status,
  label,
  asChild,
} = defineProps<DotProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  role: label === undefined ? "none" : "img",
  "aria-label": label,
  "aria-hidden": label === undefined ? "true" : undefined,
  ...responsiveDataAttrs("size", size),
  "data-color": color,
  "data-status": status,
}));
</script>

<template>
  <component :is="asChild ? Slot : 'span'" class="t-dot" v-bind="attrs">
    <slot />
  </component>
</template>
