<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/icon.yaml -->
<script setup lang="ts">
/**
 * Wrapper for caller-supplied SVG glyphs. Sizes the box and lets the SVG inherit color via `currentColor`. Decorative by default — supply `label` to make the icon meaningful. Does not ship an icon set; the consumer chooses their library (Lucide, Tabler, Heroicons, custom).
 *
 * @example Default
 * ```vue
 * <Icon>Label</Icon>
 * ```
 *
 * @example Small
 * ```vue
 * <Icon size="sm">Label</Icon>
 * ```
 *
 * @example Large
 * ```vue
 * <Icon size="lg">Label</Icon>
 * ```
 */
import "@teseor/css/components/icon.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type IconSize = "sm" | "md" | "lg";

type IconColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

type IconProps = {
  /** Size scale. */
  size?: Responsive<IconSize>;
  /** Semantic color override. Absence-of-attr keeps the SVG on `currentColor` (inherits from the parent's text color); setting a value swaps the `--t-icon-fg` slot to the matching semantic token. */
  color?: IconColor;
  /** Accessible name. When set, the wrapper carries `aria-label={label}` and drops `aria-hidden`. When unset, the wrapper carries `aria-hidden="true"` and is invisible to assistive tech — the common case for icons inside a labeled `<button>`. */
  label?: string;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<span>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  size,
  color,
  label,
  asChild,
} = defineProps<IconProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  "aria-label": label,
  "aria-hidden": label === undefined ? "true" : undefined,
  ...responsiveDataAttrs("size", size),
  "data-color": color,
}));
</script>

<template>
  <component :is="asChild ? Slot : 'span'" class="t-icon" v-bind="attrs">
    <slot />
  </component>
</template>
