<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/image.yaml -->
<script setup lang="ts">
/**
 * Image primitive — styled `<img>` with token-driven defaults (rounded corners, loading-state background, optional `object-fit`). Native HTML attrs (`src`, `alt`, `width`, `height`, `loading`, `decoding`, `srcset`, `sizes`) pass through the inherited type.
 *
 * @example Default
 * ```vue
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" />
 * ```
 *
 * @example Fit Cover
 * ```vue
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" fit="cover" :width='320' :height='180' />
 * ```
 *
 * @example Fit Contain
 * ```vue
 * <Image src="/img/sample-landscape.jpg" alt="Minimalist landscape of layered hills under a warm sky" fit="contain" :width='320' :height='180' />
 * ```
 */
import "@teseor/css/components/image.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type ImageFit = "cover" | "contain" | "fill" | "none" | "scale-down";

type ImageProps = {
  /** Maps to `object-fit`. Absence-of-attr leaves the default (`fill`). Responsive form (`{ base, sm, md, … }`) emits per-breakpoint `data-fit-{bp}` attrs for art-direction without `<picture>`. */
  fit?: Responsive<ImageFit>;
};

const {
  fit,
} = defineProps<ImageProps>();

defineSlots<{
}>();



const attrs = computed(() => ({
  ...responsiveDataAttrs("fit", fit),
}));
</script>

<template>
  <img class="t-image" v-bind="attrs" />
</template>
