<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/input.yaml -->
<script setup lang="ts">
/**
 * Single-line text input. Styled `<input>` with token-driven defaults and outline / subtle / plain visual variants. The native `type` attribute (`text`, `email`, `number`, `tel`, `url`, `search`, `password`) passes through `ComponentProps<"input">`. Form-association attributes (`name`, `form`, `required`, `readOnly`, `disabled`) come from the formControl shared contract.
 *
 * @example Default
 * ```vue
 * <Input placeholder="Your name" />
 * ```
 *
 * @example Variant Outline
 * ```vue
 * <Input variant="outline" placeholder="Email" />
 * ```
 *
 * @example Variant Subtle
 * ```vue
 * <Input variant="subtle" placeholder="Email" />
 * ```
 */
import "@teseor/css/components/input.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type InputVariant = "outline" | "subtle" | "plain";

type InputSize = "sm" | "md" | "lg";

type InputProps = {
  /** Visual style. */
  variant?: InputVariant;
  /** Size scale. */
  size?: Responsive<InputSize>;
  /** Marks the field as invalid for styling. Emits `data-invalid="true"` on the root. ARIA wiring (`aria-invalid`) is consumer-supplied or comes from the Field composite (tracked under #692). */
  invalid?: boolean;
};

const {
  variant,
  size,
  invalid,
} = defineProps<InputProps>();

defineSlots<{
}>();



const attrs = computed(() => ({
  "data-variant": variant,
  ...responsiveDataAttrs("size", size),
  "data-invalid": invalid ? "true" : undefined,
}));
</script>

<template>
  <input class="t-input" v-bind="attrs" />
</template>
