<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/kbd.yaml -->
<script setup lang="ts">
/**
 * Keyboard-key primitive — styled `<kbd>` with token-driven monospace, raised-key visual, and subtle border. Single key per element; combos compose via children (`<Kbd>Cmd</Kbd>+<Kbd>K</Kbd>`).
 *
 * @example Default
 * ```vue
 * <Kbd>Label</Kbd>
 * ```
 *
 * @example Small
 * ```vue
 * <Kbd size="sm">Label</Kbd>
 * ```
 *
 * @example Large
 * ```vue
 * <Kbd size="lg">Label</Kbd>
 * ```
 */
import "@teseor/css/components/kbd.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type KbdSize = "sm" | "md" | "lg";

type KbdProps = {
  /** Size scale. */
  size?: Responsive<KbdSize>;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<kbd>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  size,
  asChild,
} = defineProps<KbdProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  ...responsiveDataAttrs("size", size),
}));
</script>

<template>
  <component :is="asChild ? Slot : 'kbd'" class="t-kbd" v-bind="attrs">
    <slot />
  </component>
</template>
