<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/link.yaml -->
<script setup lang="ts">
/**
 * Anchor primitive — styled `<a>` with token-driven color, hover, and visited treatment. Composes with native HTML attrs (`href`, `target`, `rel`, …) via the inherited type.
 *
 * @example Default
 * ```vue
 * <Link>Label</Link>
 * ```
 *
 * @example Subtle
 * ```vue
 * <Link variant="subtle">Label</Link>
 * ```
 *
 * @example Plain
 * ```vue
 * <Link variant="plain">Label</Link>
 * ```
 */
import "@teseor/css/components/link.css";
import { computed, type VNode } from "vue";
import { Slot } from "./components/Slot.ts";

type LinkVariant = "default" | "subtle" | "plain";

type LinkProps = {
  /** Visual style. */
  variant?: LinkVariant;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<a>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  variant,
  asChild,
} = defineProps<LinkProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  "data-variant": variant,
}));
</script>

<template>
  <component :is="asChild ? Slot : 'a'" class="t-link" v-bind="attrs">
    <slot />
  </component>
</template>
