<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/list.yaml -->
<script setup lang="ts">
/**
 * Ordered / unordered list primitive. Renders `<ul>` or `<ol>` based on `ordered`; styles bare `<li>` children with grid-rhythm spacing and prose-friendly markers.
 *
 * @example Default
 * ```vue
 * <List>Label</List>
 * ```
 *
 * @example Ordered
 * ```vue
 * <List ordered="true">Label</List>
 * ```
 *
 * @example Compact
 * ```vue
 * <List spacing="compact">Label</List>
 * ```
 */
import "@teseor/css/components/list.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type ListOrdered = "false" | "true";

type ListSpacing = "compact" | "comfortable";

type ListProps = {
  /** Switches the rendered tag between `<ul>` (`false`) and `<ol>` (`true`). String-typed because `elementByProp` v1 accepts string-valued controlling props only. */
  ordered?: ListOrdered;
  /** Vertical rhythm between list items. `comfortable` matches prose defaults; `compact` suits dense in-app surfaces (nav rails, comment threads). */
  spacing?: Responsive<ListSpacing>;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  ordered = "false",
  spacing = "comfortable",
  asChild,
} = defineProps<ListProps>();

defineSlots<{
  default?(): VNode[];
}>();

const tagMap = { "false": "ul", "true": "ol" } as const;

const attrs = computed(() => ({
  ...responsiveDataAttrs("spacing", spacing),
}));
</script>

<template>
  <component :is="asChild ? Slot : tagMap[ordered ?? 'false']" class="t-list" v-bind="attrs">
    <slot />
  </component>
</template>
