<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/pagination.yaml -->
<script setup lang="ts">
/**
 * A static page-link list. Renders one item per entry in the `pages` array. Phase-1 stub for RFC-0005; real navigation lands with phase 3.
 *
 * @example Three Pages
 * ```vue
 * <Pagination :pages='[{"id":"1","label":"1"},{"id":"2","label":"2","current":true},{"id":"3","label":"3"}]'>Label</Pagination>
 * ```
 *
 * @example Five Pages Last Active
 * ```vue
 * <Pagination :pages='[{"id":"1","label":"1"},{"id":"2","label":"2"},{"id":"3","label":"3"},{"id":"4","label":"4"},{"id":"5","label":"5","current":true}]'>Label</Pagination>
 * ```
 *
 * @example Empty
 * ```vue
 * <Pagination :pages='[]'>Label</Pagination>
 * ```
 */
import "@teseor/css/components/pagination.css";

export type PaginationPageItem = {
  /** Stable item identity; required. */
  id: string;
  /** Page label rendered as the item text. */
  label?: string;
  /** Marks the active page; exposed as `data-current`. */
  current?: boolean;
};

type PaginationProps = {
  /** Items rendered by the repeating `page` part. */
  pages?: ReadonlyArray<PaginationPageItem>;
};

const {
  pages = [],
} = defineProps<PaginationProps>();
</script>

<template>
  <nav class="t-pagination">
    <span
      v-for="item in pages"
      :key="item.id"
      class="t-pagination-page"
      :data-id="item.id"
      :data-current="item.current || undefined"
    >{{ item.label }}</span>
  </nav>
</template>
