<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/radio.yaml -->
<script setup lang="ts">
/**
 * Single radio button. Styled `<input type="radio">` with a painted dot and three sizes. Group exclusivity is consumer-owned via shared `name` (browsers handle it natively). Native `checked` / `defaultChecked` / `onChange` pass through `ComponentProps<"input">`. Form-association attributes (`name`, `form`, `required`, `disabled`) come from the formControl shared contract; HTML ignores `readOnly` on radio inputs.
 *
 * @example Default
 * ```vue
 * <Radio />
 * ```
 *
 * @example Checked
 * ```vue
 * <Radio defaultChecked />
 * ```
 *
 * @example Size Sm
 * ```vue
 * <Radio size="sm" />
 * ```
 */
import "@teseor/css/components/radio.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type RadioSize = "sm" | "md" | "lg";

type RadioProps = {
  /** Size scale. */
  size?: Responsive<RadioSize>;
};

const {
  size,
} = defineProps<RadioProps>();

defineSlots<{
}>();



const attrs = computed(() => ({
  "type": "radio",
  ...responsiveDataAttrs("size", size),
}));
</script>

<template>
  <input class="t-radio" v-bind="attrs" />
</template>
