<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/stack.yaml -->
<script setup lang="ts">
/**
 * A vertical layout primitive. Stacks children on the block axis with consistent spacing.
 *
 * @example Gap 3
 * ```vue
 * <Stack gap="3">Label</Stack>
 * ```
 *
 * @example Gap 0
 * ```vue
 * <Stack gap="0">Label</Stack>
 * ```
 *
 * @example Align Center
 * ```vue
 * <Stack gap="4" align="center">Label</Stack>
 * ```
 */
import "@teseor/css/components/stack.css";
import { computed, type VNode } from "vue";
import { responsiveDataAttrs } from "./_runtime.ts";


type StackProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
  /** Inline-axis alignment of children. One of `start`, `center`, `end`, `stretch`. */
  align?: string | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", string>>;
};

const {
  gap,
  align,
} = defineProps<StackProps>();

defineSlots<{
  default?(): VNode[];
}>();



const attrs = computed(() => ({
  ...responsiveDataAttrs("gap", gap),
  ...responsiveDataAttrs("align", align),
}));
</script>

<template>
  <div class="t-stack" v-bind="attrs">
    <slot />
  </div>
</template>
