<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/switch.yaml -->
<script setup lang="ts">
/**
 * On/off toggle. Styled `<input type="checkbox" role="switch">` with a sliding thumb and three sizes. Native `checked` / `defaultChecked` / `onChange` pass through `ComponentProps<"input">`. Form-association attributes (`name`, `form`, `required`, `disabled`) come from the formControl shared contract; HTML ignores `readOnly` on checkbox inputs.
 *
 * @example Default
 * ```vue
 * <Switch />
 * ```
 *
 * @example Checked
 * ```vue
 * <Switch defaultChecked />
 * ```
 *
 * @example Size Sm
 * ```vue
 * <Switch size="sm" />
 * ```
 */
import "@teseor/css/components/switch.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type SwitchSize = "sm" | "md" | "lg";

type SwitchProps = {
  /** Size scale. */
  size?: Responsive<SwitchSize>;
};

const {
  size,
} = defineProps<SwitchProps>();

defineSlots<{
}>();



const attrs = computed(() => ({
  "type": "checkbox",
  role: "switch",
  ...responsiveDataAttrs("size", size),
}));
</script>

<template>
  <input class="t-switch" v-bind="attrs" />
</template>
