<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/tablist.yaml -->
<script lang="ts">
export type TablistItem = {
  /** Stable item identity; required. */
  id: string;
  /** Tab label rendered as the button's text. */
  label?: string;
  /** Marks the active tab; exposed as `data-active`. */
  active?: boolean;
  /** Optional icon character or symbol shown next to the tab. */
  icon?: string;
};
</script>

<script setup lang="ts">
/**
 * A non-interactive tab bar. Renders one tab button + an optional adjacent icon per item, interleaved via a shared groupKey. Selection is visual-only — pass `active: true` per item; real interactive Tabs ships with #690 (events) + #692 (a11y).
 *
 * @example Three Tabs Middle Active
 * ```vue
 * <Tablist :items='[{"id":"overview","label":"Overview"},{"id":"details","label":"Details","active":true,"icon":"✱"},{"id":"activity","label":"Activity"}]' />
 * ```
 *
 * @example Five Tabs With Icons
 * ```vue
 * <Tablist :items='[{"id":"1","label":"Home","icon":"⌂"},{"id":"2","label":"Inbox","icon":"✉","active":true},{"id":"3","label":"Calendar","icon":"▣"},{"id":"4","label":"Files","icon":"▤"},{"id":"5","label":"Settings","icon":"✦"}]' />
 * ```
 *
 * @example Empty
 * ```vue
 * <Tablist :items='[]' />
 * ```
 */
import "@teseor/css/components/tablist.css";

type TablistProps = {
  /** Items rendered by the repeating `tab` + `tab-icon` parts. */
  items?: ReadonlyArray<TablistItem>;
};

const {
  items = [],
} = defineProps<TablistProps>();
</script>

<template>
  <div class="t-tablist">
    <template v-for="item in items" :key="item.id">
    <button
      type="button"
      class="t-tablist-tab"
      :data-id="item.id"
      :data-active="item.active || undefined"
    >{{ item.label }}</button>
    <span
      class="t-tablist-icon"
      :data-id="item.id"
    >{{ item.icon }}</span>
    </template>
  </div>
</template>
