<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/text.yaml -->
<script setup lang="ts">
/**
 * Typography primitive for non-heading prose. Folds the legacy `Paragraph` — one component covers both inline (`<span>`) and block (`<p>`) cases via the `as` prop.
 *
 * @example Default
 * ```vue
 * <Text as="span">Label</Text>
 * ```
 *
 * @example Paragraph
 * ```vue
 * <Text as="p">Label</Text>
 * ```
 *
 * @example Muted Small
 * ```vue
 * <Text as="span" variant="muted" size="sm">Label</Text>
 * ```
 */
import "@teseor/css/components/text.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";
import { Slot } from "./components/Slot.ts";

type TextVariant = "default" | "muted" | "highlight";

type TextSize = "xs" | "sm" | "md" | "lg" | "xl";

type TextAs = "span" | "p" | "em" | "strong" | "small";

type TextProps = {
  /** Visual style. */
  variant?: TextVariant;
  /** Size scale. */
  size?: Responsive<TextSize>;
  /** Rendered HTML tag. `span` is inline (no margin); `p` is a prose block (margin-block applies); `em`/`strong`/`small` carry implicit emphasis / strong-importance / small-print semantics. */
  as?: TextAs;
  /** Render directly on the consumer's child VNode via Slot (cloneVNode) instead of wrapping in a `<div>`. Single-child invariant. */
  asChild?: boolean;
};

const {
  variant,
  size,
  as = "span",
  asChild,
} = defineProps<TextProps>();

defineSlots<{
  default?(): VNode[];
}>();

const tagMap = { "span": "span", "p": "p", "em": "em", "strong": "strong", "small": "small" } as const;

const attrs = computed(() => ({
  "data-variant": variant,
  ...responsiveDataAttrs("size", size),
}));
</script>

<template>
  <component :is="asChild ? Slot : tagMap[as ?? 'span']" class="t-text" v-bind="attrs">
    <slot />
  </component>
</template>
