<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/textarea.yaml -->
<script setup lang="ts">
/**
 * Multi-line text input. Styled `<textarea>` with token-driven defaults and outline / subtle / plain visual variants. Native attributes (`rows`, `cols`, `placeholder`, `value`, `defaultValue`, `maxLength`, etc.) pass through `ComponentProps<"textarea">`. Form-association attributes (`name`, `form`, `required`, `readOnly`, `disabled`) come from the formControl shared contract.
 *
 * @example Default
 * ```vue
 * <Textarea placeholder="Your message" />
 * ```
 *
 * @example Variant Outline
 * ```vue
 * <Textarea variant="outline" placeholder="Comment" />
 * ```
 *
 * @example Variant Subtle
 * ```vue
 * <Textarea variant="subtle" placeholder="Comment" />
 * ```
 */
import "@teseor/css/components/textarea.css";
import { computed, type VNode } from "vue";
import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";

type TextareaVariant = "outline" | "subtle" | "plain";

type TextareaSize = "sm" | "md" | "lg";

type TextareaResize = "none" | "vertical" | "horizontal" | "both";

type TextareaProps = {
  /** Visual style. */
  variant?: TextareaVariant;
  /** Size scale. */
  size?: Responsive<TextareaSize>;
  /** Maps to CSS `resize`. Absence-of-attr leaves the base CSS default (`vertical`). Set to `none` for a fixed-height field, `both` for free resizing. */
  resize?: TextareaResize;
  /** Marks the field as invalid for styling. Emits `data-invalid="true"` on the root. ARIA wiring (`aria-invalid`) is consumer-supplied or comes from the Field composite (tracked under #692). */
  invalid?: boolean;
};

const {
  variant,
  size,
  resize,
  invalid,
} = defineProps<TextareaProps>();

defineSlots<{
}>();



const attrs = computed(() => ({
  "data-variant": variant,
  ...responsiveDataAttrs("size", size),
  "data-resize": resize,
  "data-invalid": invalid ? "true" : undefined,
}));
</script>

<template>
  <textarea class="t-textarea" v-bind="attrs" />
</template>
