import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderAtomicReactWrapper } from "./atomic.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

function atomicSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "button",
    kind: "atomic",
    props: {},
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderAtomicReactWrapper", () => {
  test("opens with the `use client` directive and the AUTOGENERATED banner", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out.startsWith(`"use client";\n`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/button.yaml");
  });

  test("imports the per-component CSS module", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out).toContain(`import "@teseor/css/components/button.css";`);
  });

  test("uses the spec's `element` for the root tag when no `as` prop exists", () => {
    const out = renderAtomicReactWrapper(atomicSpec({ element: "span" }), {});
    expect(out).toContain(`<span\n`);
    expect(out).toContain("</span>");
  });

  test("switches to a polymorphic `Component` when an `as` prop is declared", () => {
    const out = renderAtomicReactWrapper(
      atomicSpec({ props: { as: prop({ type: "string", default: "button" }) } }),
      {},
    );
    expect(out).toContain("const Component = asElement(");
    expect(out).toContain("<Component\n");
    expect(out).toContain("</Component>");
  });

  test("imports the responsive runtime helpers only when there's a responsive prop", () => {
    const noResp = renderAtomicReactWrapper(atomicSpec(), {});
    expect(noResp).not.toContain("responsiveDataAttrs");

    const withResp = renderAtomicReactWrapper(
      atomicSpec({ sizes: { md: { description: "" } } }),
      {},
    );
    expect(withResp).toContain(
      `import { mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";`,
    );
  });

  test("imports and calls mergeClass for the root className", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out).toContain(`import { mergeClass } from "./_runtime.ts";`);
    expect(out).toContain(`const mergedClassName = mergeClass("t-button", className);`);
  });

  test("wraps `{children}` in slotElement when set", () => {
    const out = renderAtomicReactWrapper(
      atomicSpec({ name: "codeblock", element: "pre", slotElement: "code" }),
      {},
    );
    expect(out).toContain("<pre");
    expect(out).toContain("<code>");
    expect(out).toContain("{children}");
    expect(out).toContain("</code>");
  });

  test("omits the slot wrapper when slotElement is unset", () => {
    const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
    expect(out).not.toContain("<code>");
  });

  describe("polymorphic: 'asChild'", () => {
    test("imports Slot, adds the asChild prop, and selects Component conditionally", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toContain(`import { Slot } from "./components/Slot.tsx";`);
      expect(out).toContain("asChild?: boolean;");
      expect(out).toContain(`const Component = asChild ? Slot : "div";`);
      expect(out).toContain("<Component\n");
      expect(out).toContain("</Component>");
    });

    test("widens the ref type to HTMLElement (consumer-chosen element)", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "p", polymorphic: "asChild" }),
        {},
      );
      expect(out).toContain("ref?: Ref<HTMLElement>;");
    });

    test("includes asChild in the destructure", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toMatch(/const\s*\{[^}]*\basChild\b[^}]*\}\s*=\s*props;/s);
    });

    test("omits Slot import and asChild prop when polymorphic is unset", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain(`import { Slot }`);
      expect(out).not.toContain("asChild?: boolean;");
    });
  });
});
