import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderAtomicReactWrapper } from "./atomic.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

function atomicSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "button",
    kind: "atomic",
    props: {},
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderAtomicReactWrapper", () => {
  test("opens with the `use client` directive and the AUTOGENERATED banner", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out.startsWith(`"use client";\n`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/button.yaml");
  });

  test("imports the per-component CSS module", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out).toContain(`import "@teseor/css/components/button.css";`);
  });

  test("uses the spec's `element` for the root tag when no `as` prop exists", () => {
    const out = renderAtomicReactWrapper(atomicSpec({ element: "span" }), {});
    expect(out).toContain(`<span\n`);
    expect(out).toContain("</span>");
  });

  test("switches to a polymorphic `Component` when an `as` prop is declared", () => {
    const out = renderAtomicReactWrapper(
      atomicSpec({ props: { as: prop({ type: "string", default: "button" }) } }),
      {},
    );
    expect(out).toContain("const Component = asElement(");
    expect(out).toContain("<Component\n");
    expect(out).toContain("</Component>");
  });

  test("imports the responsive runtime helpers only when there's a responsive prop", () => {
    const noResp = renderAtomicReactWrapper(atomicSpec(), {});
    expect(noResp).not.toContain("responsiveDataAttrs");

    const withResp = renderAtomicReactWrapper(
      atomicSpec({ sizes: { md: { description: "" } } }),
      {},
    );
    expect(withResp).toContain(
      `import { mergeClass, type Responsive, responsiveDataAttrs } from "./_runtime.ts";`,
    );
  });

  test("imports and calls mergeClass for the root className", () => {
    const out = renderAtomicReactWrapper(atomicSpec(), {});
    expect(out).toContain(`import { mergeClass } from "./_runtime.ts";`);
    expect(out).toContain(`const mergedClassName = mergeClass("t-button", className);`);
  });

  test("wraps `{children}` in slotElement when set", () => {
    const out = renderAtomicReactWrapper(
      atomicSpec({ name: "codeblock", element: "pre", slotElement: "code" }),
      {},
    );
    expect(out).toContain("<pre");
    expect(out).toContain("<code>");
    expect(out).toContain("{children}");
    expect(out).toContain("</code>");
  });

  test("omits the slot wrapper when slotElement is unset", () => {
    const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
    expect(out).not.toContain("<code>");
  });

  describe("polymorphic: 'asChild'", () => {
    test("imports Slot, adds the asChild prop, and selects Component conditionally", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toContain(`import { Slot } from "./components/Slot.tsx";`);
      expect(out).toContain("asChild?: boolean;");
      expect(out).toContain(`const Component = asChild ? Slot : asElement("div");`);
      expect(out).toContain("<Component\n");
      expect(out).toContain("</Component>");
    });

    test("widens the ref type to HTMLElement (consumer-chosen element)", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "p", polymorphic: "asChild" }),
        {},
      );
      expect(out).toContain("ref?: Ref<HTMLElement>;");
    });

    test("includes asChild in the destructure", () => {
      const out = renderAtomicReactWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toMatch(/const\s*\{[^}]*\basChild\b[^}]*\}\s*=\s*props;/s);
    });

    test("omits Slot import and asChild prop when polymorphic is unset", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain(`import { Slot }`);
      expect(out).not.toContain("asChild?: boolean;");
    });
  });

  describe("elementByProp", () => {
    function headingSpec(extra: Partial<Spec> = {}): Spec {
      return atomicSpec({
        name: "heading",
        elementByProp: {
          prop: "level",
          map: { "1": "h1", "2": "h2", "3": "h3" },
        },
        props: {
          level: prop({ type: "string", values: ["1", "2", "3"], default: "1" }),
        },
        ...extra,
      });
    }

    test("emits a tagMap constant and selects Component from the prop value", () => {
      const out = renderAtomicReactWrapper(headingSpec(), {});
      expect(out).toContain(`const tagMap = { "1": "h1", "2": "h2", "3": "h3" } as const;`);
      expect(out).toContain(`const Component = asElement(tagMap[level ?? "1"]);`);
      expect(out).toContain("<Component\n");
      expect(out).toContain("</Component>");
    });

    test("narrows the ref type to the union of map values when not polymorphic", () => {
      const out = renderAtomicReactWrapper(headingSpec(), {});
      expect(out).toContain(`ref?: Ref<HTMLElementTagNameMap["h1" | "h2" | "h3"]>;`);
    });

    test("imports asElement from the runtime when elementByProp is set", () => {
      const out = renderAtomicReactWrapper(headingSpec(), {});
      expect(out).toContain(`import type { ComponentProps, ReactNode, Ref } from "react";`);
      expect(out).toContain(`import { asElement, mergeClass`);
    });

    test("falls back to the first map key when the prop has no `default`", () => {
      const out = renderAtomicReactWrapper(
        headingSpec({
          props: {
            level: prop({ type: "string", values: ["1", "2", "3"] }),
          },
        }),
        {},
      );
      expect(out).toContain(`const Component = asElement(tagMap[level ?? "1"]);`);
    });

    test("composes with `polymorphic: 'asChild'` (asChild wins, else tag from prop)", () => {
      const out = renderAtomicReactWrapper(headingSpec({ polymorphic: "asChild" }), {});
      expect(out).toContain(`const tagMap =`);
      expect(out).toContain(`const Component = asChild ? Slot : asElement(tagMap[level ?? "1"]);`);
      // asChild accepts any consumer element — ref widens to HTMLElement so a
      // narrow tag-map union doesn't reject e.g. `<a ref={…}>`.
      expect(out).toContain(`ref?: Ref<HTMLElement>;`);
    });

    test("omits tagMap when elementByProp is unset", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain("const tagMap");
    });
  });

  describe("void elements", () => {
    test("emits a biome-ignore for useAltText above generated <img>", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ name: "image", element: "img" }), {});
      expect(out).toContain(
        "    // biome-ignore lint/a11y/useAltText: alt is forwarded via {...rest}\n    <img\n",
      );
    });

    test("does not emit a biome-ignore for void elements without a registered rule", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ name: "divider", element: "hr" }), {});
      expect(out).not.toContain("biome-ignore");
    });

    test("does not emit a biome-ignore for non-void elements", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain("biome-ignore");
    });

    test("declares children as `never` for void elements", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ name: "image", element: "img" }), {});
      expect(out).toContain("children?: never;");
      expect(out).not.toContain("children?: ReactNode;");
    });

    test("declares children as ReactNode for non-void elements", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ element: "div" }), {});
      expect(out).toContain("children?: ReactNode;");
      expect(out).not.toContain("children?: never;");
    });

    test("omits the ReactNode import for void elements", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ name: "image", element: "img" }), {});
      expect(out).toContain(`import type { ComponentProps, Ref } from "react";`);
      expect(out).not.toContain("ReactNode");
    });

    test("destructures children with a `_children` alias for void elements (strips from rest)", () => {
      const out = renderAtomicReactWrapper(atomicSpec({ name: "image", element: "img" }), {});
      expect(out).toContain("children: _children");
    });

    describe("mixed elementByProp.map (void + non-void)", () => {
      function dividerSpec(extra: Partial<Spec> = {}): Spec {
        return atomicSpec({
          name: "divider",
          elementByProp: {
            prop: "orientation",
            map: { horizontal: "hr", vertical: "div" },
          },
          props: {
            orientation: prop({
              type: "string",
              values: ["horizontal", "vertical"],
              default: "horizontal",
            }),
          },
          ...extra,
        });
      }

      test("emits resolvedTag + isVoidResolved locals derived from the tagMap", () => {
        const out = renderAtomicReactWrapper(dividerSpec(), {});
        expect(out).toContain(`const tagMap = { "horizontal": "hr", "vertical": "div" } as const;`);
        expect(out).toContain(`const resolvedTag = tagMap[orientation ?? "horizontal"];`);
        expect(out).toContain(`const isVoidResolved = resolvedTag === "hr";`);
      });

      test("Component widens via asElement(resolvedTag) when not polymorphic", () => {
        const out = renderAtomicReactWrapper(dividerSpec(), {});
        expect(out).toContain(`const Component = asElement(resolvedTag);`);
      });

      test("renders a ternary that self-closes the void branch and opens the non-void one", () => {
        const out = renderAtomicReactWrapper(dividerSpec(), {});
        expect(out).toMatch(/isVoidResolved\s*\?\s*\(/);
        expect(out).toContain("<Component\n");
        expect(out).toContain("/>");
        expect(out).toContain(">\n");
        expect(out).toContain("</Component>");
      });

      test("keeps children as ReactNode (non-void branch may consume them)", () => {
        const out = renderAtomicReactWrapper(dividerSpec(), {});
        expect(out).toContain("children?: ReactNode;");
        expect(out).not.toContain("children?: never;");
        expect(out).not.toContain("children: _children");
      });

      test("guards asChild on the non-void branch so Slot never wraps a void tag", () => {
        const out = renderAtomicReactWrapper(dividerSpec({ polymorphic: "asChild" }), {});
        expect(out).toContain(
          `const Component = asChild && !isVoidResolved ? Slot : asElement(resolvedTag);`,
        );
      });
    });

    describe("boolean state props", () => {
      test("emits a `data-{name}` flag on the root for each boolean state prop", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            element: "div",
            props: {
              decorative: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).toContain(`data-decorative={decorative === true ? "true" : undefined}`);
      });

      test("does not emit a data-* flag for the elementByProp controlling prop", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            elementByProp: {
              prop: "ordered",
              map: { false: "ul", true: "ol" },
            },
            props: {
              ordered: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).not.toContain("data-ordered=");
      });

      test("does not emit data-* for disabled / loading / responsive booleans", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            element: "button",
            props: {
              disabled: prop({ type: "boolean" }),
              loading: prop({ type: "boolean" }),
              compact: prop({ type: "boolean", responsive: true }),
            },
          }),
          {},
        );
        expect(out).not.toContain("data-disabled=");
        expect(out).not.toContain(`data-compact={compact === true ?`);
      });
    });

    describe("htmlAttrs", () => {
      test("emits each entry as a static JSX attribute after the spread", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({ name: "switch", element: "input", htmlAttrs: { type: "checkbox" } }),
          {},
        );
        const spreadIdx = out.indexOf("{...rest}");
        const typeIdx = out.indexOf(`type="checkbox"`);
        expect(typeIdx).toBeGreaterThan(spreadIdx);
      });

      test("emits no static attribute lines when htmlAttrs is unset", () => {
        const out = renderAtomicReactWrapper(atomicSpec({ name: "input", element: "input" }), {});
        expect(out).not.toContain(`type="checkbox"`);
      });

      test("emits multiple entries on separate lines", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            name: "image",
            element: "img",
            htmlAttrs: { loading: "lazy", decoding: "async" },
          }),
          {},
        );
        expect(out).toContain(`loading="lazy"`);
        expect(out).toContain(`decoding="async"`);
      });
    });

    describe("role + biome-ignore", () => {
      test('emits an inline biome-ignore above role="switch" for <input>', () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            name: "switch",
            element: "input",
            htmlAttrs: { type: "checkbox" },
            a11y: { role: "switch" },
          }),
          {},
        );
        expect(out).toContain(
          `// biome-ignore lint/a11y/useAriaPropsForRole: aria-checked is implicit from type="checkbox"\n      role="switch"`,
        );
      });

      test("does not emit a role biome-ignore for unmatched role + element combos", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({ element: "div", a11y: { role: "separator" } }),
          {},
        );
        expect(out).not.toContain("useAriaPropsForRole");
      });
    });

    describe("a11y emission", () => {
      test("emits a static role on the root from spec.a11y.role", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({ element: "div", a11y: { role: "separator" } }),
          {},
        );
        expect(out).toContain(`role="separator"`);
      });

      test("forwards each ariaProps entry as `aria-{prop}={prop}`", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            element: "div",
            props: {
              orientation: prop({
                type: "string",
                values: ["horizontal", "vertical"],
                responsive: false,
                description: "",
              }),
            },
            a11y: { ariaProps: ["orientation"] },
          }),
          {},
        );
        expect(out).toContain(`aria-orientation={orientation}`);
      });

      test("toggles role to none and adds aria-hidden when decorativeProp is set", () => {
        const out = renderAtomicReactWrapper(
          atomicSpec({
            element: "div",
            props: { decorative: prop({ type: "boolean", description: "" }) },
            a11y: { role: "separator", decorativeProp: "decorative" },
          }),
          {},
        );
        expect(out).toContain(`role={decorative === true ? "none" : "separator"}`);
        expect(out).toContain(`aria-hidden={decorative === true ? "true" : undefined}`);
      });
    });
  });
});
