import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderCompositeOverlayReactWrapper } from "./composite-overlay.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

function tooltipSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "tooltip",
    kind: "composite",
    description: "Floating panel.",
    overlay: {
      anchor: "trigger",
      floating: "content",
      anchorVar: "--t-anchor",
      mode: "manual",
      modal: false,
    },
    parts: {
      trigger: { fromChildren: true },
      content: { element: "div", a11y: { role: "tooltip" } },
    },
    props: {
      open: prop({ type: "boolean", pattern: "controllable" }),
      text: prop({ type: "string", slot: true, __part: "content" }),
    },
    tokens: {},
    states: {},
    ...overrides,
  };
}

describe("renderCompositeOverlayReactWrapper", () => {
  test("opens with the `use client` directive and the AUTOGENERATED banner", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out.startsWith(`"use client";\n`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/tooltip.yaml");
  });

  test("wires the useOverlay hook with the controllable prop name", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).toContain("const overlay = useOverlay<");
    expect(out).toContain("open: openProp,");
    expect(out).toContain("defaultOpen,");
    expect(out).toContain("onOpenChange,");
  });

  test("throws when no `pattern: controllable` boolean prop is declared", () => {
    const spec = tooltipSpec({
      props: { text: prop({ type: "string", slot: true, __part: "content" }) },
    });
    expect(() => renderCompositeOverlayReactWrapper(spec, {})).toThrow(/pattern: controllable/);
  });

  test("uses the trigger part's rootClass when declared", () => {
    const spec = tooltipSpec({
      parts: {
        trigger: { fromChildren: true, rootClass: "custom-trigger" },
        content: { element: "div", a11y: { role: "tooltip" } },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain(`className="custom-trigger"`);
  });

  test("accepts a forwarded `ref` typed against the content element", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).toContain('import { mergeRefs } from "./_runtime.ts";');
    expect(out).toContain(
      'import { type CSSProperties, type ReactNode, type Ref, useMemo } from "react";',
    );
    expect(out).toContain('ref?: Ref<HTMLElementTagNameMap["div"]>;');
    expect(out).toContain("    ref,\n  } = props;");
    expect(out).toContain("ref={mergeRefs(ref, overlay.contentRef)}");
    expect(out).not.toContain("ref={overlay.contentRef}");
  });

  test("renders a body-level portal and aria-modal for modal dialogs", () => {
    const spec = tooltipSpec({
      overlay: {
        anchor: "trigger",
        floating: "content",
        anchorVar: "--t-anchor",
        mode: "manual",
        modal: true,
      },
      parts: {
        trigger: { fromChildren: true },
        content: { element: "div", a11y: { role: "dialog" } },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain(`import { createPortal } from "react-dom";`);
    expect(out).toContain("createPortal(");
    expect(out).toContain(`aria-modal="true"`);
  });
});
