import { describe, expect, test } from "vitest";
import type { Spec } from "../../gen-contract.ts";
import { renderCompositeListReactWrapper } from "./composite-list.ts";

function paginationFixture(): Spec {
  return {
    name: "pagination",
    kind: "composite",
    props: {},
    tokens: {},
    states: {},
    parts: {
      root: { element: "nav", rootClass: "t-pagination" },
      page: {
        repeating: true,
        element: "a",
        rootClass: "t-pagination-page",
        props: {
          label: { type: "string", slot: true, description: "Page label." },
          current: { type: "boolean", description: "Active page." },
          href: { type: "string", description: "Target URL (data-attr in phase 1)." },
        },
      },
    },
    repeating: [
      {
        partName: "page",
        propName: "pages",
        element: "a",
        rootClass: "t-pagination-page",
        itemProps: {
          label: { type: "string", slot: true, description: "Page label." },
          current: { type: "boolean", description: "Active page." },
          href: { type: "string", description: "Target URL (data-attr in phase 1)." },
        },
      },
    ],
  };
}

describe("renderCompositeListReactWrapper (RFC-0005)", () => {
  test("opens with `use client` + AUTOGENERATED banner", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out.startsWith(`"use client";`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/pagination.yaml");
  });

  test("imports the per-component CSS", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain(`import "@teseor/css/components/pagination.css";`);
  });

  test("declares an Item type per repeating part with required `id: string`", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("export type PaginationPageItem = {");
    expect(out).toContain("  id: string;");
    expect(out).toContain("  label?: string;");
    expect(out).toContain("  current?: boolean;");
  });

  test("emits a ReadonlyArray prop for the synthesized array", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("pages?: ReadonlyArray<PaginationPageItem>;");
  });

  test("renders the wrapper element from the non-repeating part", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("<nav {...rest} ref={ref} className={mergedClassName}>");
    expect(out).toContain('mergeClass("t-pagination", className)');
  });

  test("emits a .map() over the array prop with key={item.id}", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("pages.map((item) =>");
    expect(out).toContain("key={item.id}");
  });

  test("slot-marked string prop renders as child content", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("{item.label}");
  });

  test("non-slot string prop renders as data-* attribute", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("data-href={item.href}");
  });

  test("boolean prop renders as `data-x={item.x || undefined}`", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("data-current={item.current || undefined}");
  });

  test("throws when no non-repeating wrapper part is declared", () => {
    expect(() =>
      renderCompositeListReactWrapper({
        name: "broken",
        kind: "composite",
        props: {},
        tokens: {},
        states: {},
        parts: {
          only: { repeating: true, element: "div" },
        },
        repeating: [
          {
            partName: "only",
            propName: "items",
            element: "div",
            itemProps: { label: { type: "string", description: "" } },
          },
        ],
      }),
    ).toThrow(/wrapper/);
  });
});
