import { describe, expect, test } from "vitest";
import type { Spec } from "../../gen-contract.ts";
import { renderCompositeListReactWrapper } from "./composite-list.ts";

function paginationFixture(): Spec {
  return {
    name: "pagination",
    kind: "composite",
    props: {},
    tokens: {},
    states: {},
    parts: {
      root: { element: "nav", rootClass: "t-pagination" },
      page: {
        repeating: true,
        element: "a",
        rootClass: "t-pagination-page",
        props: {
          label: { type: "string", slot: true, description: "Page label." },
          current: { type: "boolean", description: "Active page." },
          href: { type: "string", description: "Target URL (data-attr in phase 1)." },
        },
      },
    },
    repeating: [
      {
        partName: "page",
        propName: "pages",
        element: "a",
        rootClass: "t-pagination-page",
        itemProps: {
          label: { type: "string", slot: true, description: "Page label." },
          current: { type: "boolean", description: "Active page." },
          href: { type: "string", description: "Target URL (data-attr in phase 1)." },
        },
      },
    ],
  };
}

describe("renderCompositeListReactWrapper (RFC-0005)", () => {
  test("opens with `use client` + AUTOGENERATED banner", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out.startsWith(`"use client";`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/pagination.yaml");
  });

  test("imports the per-component CSS", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain(`import "@teseor/css/components/pagination.css";`);
  });

  test("declares an Item type per repeating part with required `id: string`", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("export type PaginationPageItem = {");
    expect(out).toContain("  id: string;");
    expect(out).toContain("  label?: string;");
    expect(out).toContain("  current?: boolean;");
  });

  test("emits a ReadonlyArray prop for the synthesized array", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("pages?: ReadonlyArray<PaginationPageItem>;");
  });

  test("blocks children at the type level (children?: never + Omit children)", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("children?: never;");
    expect(out).toContain(
      `Omit<ComponentProps<"nav">, keyof PaginationOwnProps | "ref" | "children">`,
    );
  });

  test("wraps the props intersection in `Readonly<...>`", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("export type PaginationProps = Readonly<");
  });

  test("renders the wrapper element from the non-repeating part", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("<nav {...rest} ref={ref} className={mergedClassName}>");
    expect(out).toContain('mergeClass("t-pagination", className)');
  });

  test("emits a .map() over the array prop with key={item.id}", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("pages.map((item) =>");
    expect(out).toContain("key={item.id}");
  });

  test("slot-marked string prop renders as child content", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("{item.label}");
  });

  test("non-slot string prop renders as data-* attribute", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("data-href={item.href}");
  });

  test("boolean prop renders as `data-x={item.x || undefined}`", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("data-current={item.current || undefined}");
  });

  function tabsListFixture(): Spec {
    return {
      name: "tabs-list",
      kind: "composite",
      props: {},
      tokens: {},
      states: {},
      parts: {
        list: { element: "div", rootClass: "t-tabs-list" },
        tab: {
          repeating: true,
          groupKey: "items",
          element: "button",
          rootClass: "t-tabs-list-tab",
          props: {
            label: { type: "string", slot: true, description: "Tab label." },
            active: { type: "boolean", description: "Active tab." },
          },
        },
        "tab-icon": {
          repeating: true,
          groupKey: "items",
          element: "span",
          rootClass: "t-tabs-list-icon",
          props: {
            icon: { type: "string", slot: true, description: "Tab icon." },
          },
        },
      },
      repeating: [
        {
          partName: "tab",
          propName: "items",
          element: "button",
          rootClass: "t-tabs-list-tab",
          groupKey: "items",
          itemProps: {
            label: { type: "string", slot: true, description: "Tab label." },
            active: { type: "boolean", description: "Active tab." },
          },
        },
        {
          partName: "tab-icon",
          propName: "items",
          element: "span",
          rootClass: "t-tabs-list-icon",
          groupKey: "items",
          itemProps: {
            icon: { type: "string", slot: true, description: "Tab icon." },
          },
        },
      ],
    };
  }

  test("groupKey siblings: emits ONE shared item type with merged props", () => {
    const out = renderCompositeListReactWrapper(tabsListFixture());
    expect(out).toContain("export type TabsListItem = {");
    expect(out).toContain("  label?: string;");
    expect(out).toContain("  active?: boolean;");
    expect(out).toContain("  icon?: string;");
    // No per-part item types.
    expect(out).not.toContain("TabsListTabItem");
    expect(out).not.toContain("TabsListTabIconItem");
  });

  test("groupKey siblings: emits ONE array prop named after the groupKey", () => {
    const out = renderCompositeListReactWrapper(tabsListFixture());
    expect(out).toContain("items?: ReadonlyArray<TabsListItem>;");
  });

  test("groupKey siblings: emits ONE interleaved .map() loop wrapped in keyed Fragment", () => {
    const out = renderCompositeListReactWrapper(tabsListFixture());
    expect(out).toMatch(/items\.map\(\(item\)/);
    // Only one .map() call total, not two.
    expect(out.match(/items\.map\(/g) ?? []).toHaveLength(1);
    expect(out).toContain("<Fragment key={item.id}>");
    expect(out).toContain("</Fragment>");
    // Both elements rendered inside the Fragment.
    expect(out).toMatch(/<button[\s\S]*<span/);
  });

  test("groupKey siblings: imports Fragment from react", () => {
    const out = renderCompositeListReactWrapper(tabsListFixture());
    expect(out).toContain("Fragment");
    expect(out).toContain('import { type ComponentProps, type Ref, Fragment } from "react"');
  });

  test("group-level scalar props on the wrapper part are typed in OwnProps", () => {
    const out = renderCompositeListReactWrapper({
      ...tabsListFixture(),
      props: {
        label: { type: "string", description: "Accessible label.", __part: "list" },
      },
    });
    expect(out).toContain("label?: string;");
  });

  test("ungrouped repeating parts still emit per-part item types (regression of phase-1 behavior)", () => {
    const out = renderCompositeListReactWrapper(paginationFixture());
    expect(out).toContain("export type PaginationPageItem = {");
  });

  test("throws when no non-repeating wrapper part is declared", () => {
    expect(() =>
      renderCompositeListReactWrapper({
        name: "broken",
        kind: "composite",
        props: {},
        tokens: {},
        states: {},
        parts: {
          only: { repeating: true, element: "div" },
        },
        repeating: [
          {
            partName: "only",
            propName: "items",
            element: "div",
            itemProps: { label: { type: "string", description: "" } },
          },
        ],
      }),
    ).toThrow(/wrapper/);
  });
});
