import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderCompositeOverlayReactWrapper } from "./composite-overlay.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

const OVERLAY = {
  anchor: "trigger",
  anchorVar: "--t-anchor",
  mode: "manual" as const,
  modal: false,
};

function tooltipSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "tooltip",
    kind: "composite",
    description: "Floating panel.",
    parts: {
      trigger: { fromChildren: true },
      content: { element: "div", a11y: { role: "tooltip" }, overlay: OVERLAY },
    },
    props: {
      open: prop({ type: "boolean", pattern: "controllable" }),
      text: prop({ type: "string", slot: true, __part: "content" }),
    },
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderCompositeOverlayReactWrapper", () => {
  test("opens with the `use client` directive and the AUTOGENERATED banner", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out.startsWith(`"use client";\n`)).toBe(true);
    expect(out).toContain("// AUTOGENERATED by gen-react. Do not edit.");
    expect(out).toContain("// Source: specs/tooltip.yaml");
  });

  test("wires the useOverlay hook with the controllable prop name", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).toContain("const overlay = useOverlay<");
    expect(out).toContain("open: openProp,");
    expect(out).toContain("defaultOpen,");
    expect(out).toContain("onOpenChange,");
  });

  test("throws when no `pattern: controllable` boolean prop is declared", () => {
    const spec = tooltipSpec({
      props: { text: prop({ type: "string", slot: true, __part: "content" }) },
    });
    expect(() => renderCompositeOverlayReactWrapper(spec, {})).toThrow(/pattern: controllable/);
  });

  test("uses the trigger part's rootClass when declared", () => {
    const spec = tooltipSpec({
      parts: {
        trigger: { fromChildren: true, rootClass: "custom-trigger" },
        content: { element: "div", a11y: { role: "tooltip" } },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain(`className="custom-trigger"`);
  });

  test("accepts a forwarded `ref` typed against the content element", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).toContain('import { mergeRefs } from "./_runtime.ts";');
    expect(out).toContain(
      'import { type CSSProperties, type ReactNode, type Ref, useMemo } from "react";',
    );
    expect(out).toContain('ref?: Ref<HTMLElementTagNameMap["div"]>;');
    expect(out).toContain("    ref,\n  } = props;");
    expect(out).toContain("const mergedContentRef = useMemo(");
    expect(out).toContain("() => mergeRefs(ref, overlay.contentRef),");
    expect(out).toContain("[ref, overlay.contentRef],");
    expect(out).toContain("ref={mergedContentRef}");
    expect(out).not.toContain("ref={overlay.contentRef}");
  });

  test("renders a body-level portal and aria-modal for modal dialogs", () => {
    const spec = tooltipSpec({
      parts: {
        trigger: { fromChildren: true },
        content: {
          element: "div",
          a11y: { role: "dialog" },
          overlay: { ...OVERLAY, modal: true },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain(`import { createPortal } from "react-dom";`);
    expect(out).toContain("createPortal(");
    expect(out).toContain(`aria-modal="true"`);
  });

  test("emits no event surface when events: is absent", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).not.toContain("onEvent?:");
    expect(out).not.toContain("handleDismiss");
    expect(out).not.toContain("handleOpenChange");
    expect(out).not.toContain(`from "@teseor/contract"`);
    expect(out).not.toContain("useCallback");
    // The hook still gets the consumer's `onOpenChange` directly when no
    // events are declared — the wrapping closure exists only to thread the
    // channel emit through.
    expect(out).toContain("onOpenChange,");
    expect(out).not.toContain("onOpenChange: handleOpenChange");
  });

  test("emits per-event prop + onEvent channel when events: is declared", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: {
          description: "Closed by the user.",
          payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain(`import type { ModalEvent } from "@teseor/contract";`);
    expect(out).toContain("/** Closed by the user. */");
    expect(out).toContain(`onDismiss?: (e: { reason: "outside" | "escape" | "button" }) => void;`);
    expect(out).toContain("onEvent?: (e: ModalEvent) => void;");
    expect(out).toContain("Aggregated event channel");
  });

  test("destructures the per-event handler props and onEvent from props", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: {
          description: "Closed.",
          payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain("    onDismiss,\n");
    expect(out).toContain("    onEvent,\n");
  });

  test("wraps onDismiss to fire consumer per-event then channel in spec-declared order", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: {
          description: "Closed.",
          payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain("const handleDismiss = useCallback(");
    expect(out).toContain(`(reason: "outside" | "escape" | "button") => {`);
    // Per-event handler MUST fire before the channel emission.
    expect(out).toMatch(
      /onDismiss\?\.\(\{ reason \}\);\s*\n\s*onEvent\?\.\(\{ type: "dismiss", reason \}\);/,
    );
    expect(out).toContain("onDismiss: handleDismiss,");
  });

  test("wraps onOpenChange to fire consumer callback then openChange channel arm", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: {
          description: "Closed.",
          payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    expect(out).toContain("const handleOpenChange = useCallback(");
    expect(out).toMatch(
      /onOpenChange\?\.\(value\);\s*\n\s*onEvent\?\.\(\{ type: "openChange", value \}\);/,
    );
    expect(out).toContain("onOpenChange: handleOpenChange,");
  });

  test("declares handleDismiss before handleOpenChange so per-emission ordering matches declaration order", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: {
          description: "Closed.",
          payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
        },
      },
    });
    const out = renderCompositeOverlayReactWrapper(spec, {});
    const dismissIdx = out.indexOf("const handleDismiss = useCallback(");
    const openChangeIdx = out.indexOf("const handleOpenChange = useCallback(");
    expect(dismissIdx).toBeGreaterThan(-1);
    expect(openChangeIdx).toBeGreaterThan(-1);
    expect(dismissIdx).toBeLessThan(openChangeIdx);
  });

  test("imports useCallback only when events: is declared", () => {
    const out = renderCompositeOverlayReactWrapper(tooltipSpec(), {});
    expect(out).not.toContain("useCallback");
    const withEvents = renderCompositeOverlayReactWrapper(
      tooltipSpec({
        name: "modal",
        events: {
          dismiss: {
            description: "Closed.",
            payload: { reason: { type: "enum", values: ["outside", "escape", "button"] } },
          },
        },
      }),
      {},
    );
    expect(withEvents).toContain("useCallback");
  });

  test("throws when events.dismiss lacks an enum 'reason' payload — runtime adapter cannot type itself", () => {
    const spec = tooltipSpec({
      name: "modal",
      events: {
        dismiss: { description: "Closed.", payload: {} },
      },
    });
    expect(() => renderCompositeOverlayReactWrapper(spec, {})).toThrow(/reason/);
  });
});
