import type { FlatItemProp } from "../../../lib/flatten.ts";
import { reactJsDocFlavor, renderComponentJsDoc } from "../../../lib/jsdoc-shape.ts";
import { pascalCase } from "../../../lib/pascal-case.ts";
import type { Spec } from "../../gen-contract.ts";
import { quote } from "../_shared/type-printer.ts";

/**
 * Emits a React wrapper for a composite spec that uses repeating parts
 * (RFC-0005, phase 1) and has no `overlay:` block. The phase-1 shape is
 * one non-repeating wrapper part + one or more repeating parts rendered
 * as its direct children.
 *
 * Pagination is the phase-1 stub. Future Breadcrumb / RadioGroup share
 * this shape once the per-item events block (#690) lands.
 */
export function renderCompositeListReactWrapper(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const partsMap = spec.parts ?? {};
  const partEntries = Object.entries(partsMap);
  const wrapperEntry = partEntries.find(([, p]) => p.repeating !== true);
  if (!wrapperEntry) {
    throw new Error(
      `composite-list spec '${spec.name}' must declare exactly one non-repeating wrapper part`,
    );
  }
  const [, wrapperPart] = wrapperEntry;
  const wrapperElement = wrapperPart.element ?? "div";
  const wrapperClass = wrapperPart.rootClass ?? `t-${spec.name}`;
  const repeating = spec.repeating ?? [];

  const itemTypeBlocks = repeating.map((r) => {
    const ItemName = `${Name}${pascalCase(r.partName)}Item`;
    const fields = [
      `  /** Stable item identity; required. */`,
      `  id: string;`,
      ...Object.entries(r.itemProps).flatMap(([n, d]) => [
        ...(d.description ? [`  /** ${d.description} */`] : []),
        `  ${n}?: ${mapItemPropType(d)};`,
      ]),
    ].join("\n");
    return `export type ${ItemName} = {\n${fields}\n};`;
  });

  const ownPropLines = repeating.map((r) => {
    return `  /** Items rendered by the repeating \`${r.partName}\` part. */\n  ${r.propName}?: ReadonlyArray<${Name}${pascalCase(r.partName)}Item>;`;
  });

  const iterationBlocks = repeating.map((r) => renderIterationBlock(Name, r));

  return `"use client";

// AUTOGENERATED by gen-react. Do not edit.
// Source: specs/${spec.name}.yaml

import "@teseor/css/components/${spec.name}.css";
import type { ComponentProps, Ref } from "react";
import { mergeClass } from "./_runtime.ts";

${itemTypeBlocks.join("\n\n")}

type ${Name}OwnProps = {
${ownPropLines.join("\n")}
  /** Forwarded ref to the wrapper element. */
  ref?: Ref<HTMLElementTagNameMap[${quote(wrapperElement)}]>;
  /** List composites render only from their array prop — children are not accepted. */
  children?: never;
};

export type ${Name}Props = ${Name}OwnProps &
  Omit<ComponentProps<${quote(wrapperElement)}>, keyof ${Name}OwnProps | "ref" | "children">;

${renderComponentJsDoc(spec, Name, reactJsDocFlavor)}export function ${Name}(props: ${Name}Props) {
  const { ${repeating.map((r) => `${r.propName} = []`).join(", ")}, className, ref, ...rest } = props;
  const mergedClassName = mergeClass(${quote(wrapperClass)}, className);
  return (
    <${wrapperElement} {...rest} ref={ref} className={mergedClassName}>
${iterationBlocks.join("\n")}
    </${wrapperElement}>
  );
}
`;
}

function mapItemPropType(def: FlatItemProp): string {
  const values = def.values ?? [];
  if (values.length > 0) return values.map(quote).join(" | ");
  switch (def.type) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function renderIterationBlock(
  Name: string,
  r: {
    partName: string;
    propName: string;
    element?: string;
    rootClass?: string;
    itemProps: Record<string, FlatItemProp>;
  },
): string {
  const itemElement = r.element ?? "div";
  const itemClass = r.rootClass ?? `t-${Name.toLowerCase()}-${r.partName}`;
  const slotEntries = Object.entries(r.itemProps).filter(([, d]) => d.slot === true);
  const attrLines: string[] = [
    `          key={item.id}`,
    `          className=${quote(itemClass)}`,
    `          data-id={item.id}`,
  ];
  for (const [n, d] of Object.entries(r.itemProps)) {
    if (d.slot === true) continue;
    if (d.type === "boolean") {
      attrLines.push(`          data-${n}={item.${n} || undefined}`);
    } else {
      attrLines.push(`          data-${n}={item.${n}}`);
    }
  }
  const body =
    slotEntries.length > 0 ? slotEntries.map(([n]) => `          {item.${n}}`).join("\n") : null;
  if (body === null) {
    return `      {${r.propName}.map((item) => (\n        <${itemElement}\n${attrLines.join("\n")}\n        />\n      ))}`;
  }
  return `      {${r.propName}.map((item) => (\n        <${itemElement}\n${attrLines.join("\n")}\n        >\n${body}\n        </${itemElement}>\n      ))}`;
}
