// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/avatar.yaml

import { h, type VNode } from "vue";
import { Avatar } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "image": () => h(Avatar, { "src": "/img/avatar-jane.jpg", "alt": "Jane Doe", "name": "Jane Doe" }, { default: LABEL }),
  "initials": () => h(Avatar, { "name": "Jane Doe" }, { default: LABEL }),
  "initials-single": () => h(Avatar, { "name": "Madonna" }, { default: LABEL }),
  "empty-fallback": () => h(Avatar, {}, { default: LABEL }),
  "size-sm": () => h(Avatar, { "name": "Jane Doe", "size": "sm" }, { default: LABEL }),
  "size-lg": () => h(Avatar, { "name": "Jane Doe", "size": "lg" }, { default: LABEL }),
  "square": () => h(Avatar, { "name": "Jane Doe", "shape": "square" }, { default: LABEL }),
  "color-primary": () => h(Avatar, { "name": "Jane Doe", "color": "primary" }, { default: LABEL }),
};
