// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/badge.yaml

import { Badge } from "@teseor/react";
import type { ReactNode } from "react";

const SLOT = (name: string): ReactNode => <span data-fixture-slot={name} />;
const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Badge>{LABEL}</Badge>,
  "solid-success": () => <Badge intent="success">{LABEL}</Badge>,
  "outline-info": () => <Badge variant="outline" intent="info">{LABEL}</Badge>,
  "ghost-danger": () => <Badge variant="ghost" intent="danger">{LABEL}</Badge>,
  "pill": () => <Badge shape="pill" intent="primary">{LABEL}</Badge>,
  "with-icon": () => <Badge intent="success" icon={SLOT("dot")}>{LABEL}</Badge>,
  "small": () => <Badge size="sm">{LABEL}</Badge>,
  "large": () => <Badge size="lg" intent="warning">{LABEL}</Badge>,
};
