// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/badge.yaml

import { h, type VNode } from "vue";
import { Badge } from "@teseor/vue";

const SLOT = (name: string) => () => h("span", { "data-fixture-slot": name });
const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Badge, {}, { default: LABEL }),
  "solid-success": () => h(Badge, { "intent": "success" }, { default: LABEL }),
  "outline-info": () => h(Badge, { "variant": "outline", "intent": "info" }, { default: LABEL }),
  "ghost-danger": () => h(Badge, { "variant": "ghost", "intent": "danger" }, { default: LABEL }),
  "pill": () => h(Badge, { "shape": "pill", "intent": "primary" }, { default: LABEL }),
  "with-icon": () => h(Badge, { "intent": "success" }, { default: LABEL, icon: SLOT("dot") }),
  "small": () => h(Badge, { "size": "sm" }, { default: LABEL }),
  "large": () => h(Badge, { "size": "lg", "intent": "warning" }, { default: LABEL }),
};
