// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/blockquote.yaml

import { Blockquote } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Blockquote>{LABEL}</Blockquote>,
  "subtle": () => <Blockquote variant="subtle">{LABEL}</Blockquote>,
};
