// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/blockquote.yaml

import { h, type VNode } from "vue";
import { Blockquote } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Blockquote, {}, { default: LABEL }),
  "subtle": () => h(Blockquote, { "variant": "subtle" }, { default: LABEL }),
};
