// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/button.yaml

import { Button } from "@teseor/react";
import type { ReactNode } from "react";

const SLOT = (name: string): ReactNode => <span data-fixture-slot={name} />;
const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "solid-primary": () => <Button variant="solid" intent="primary">{LABEL}</Button>,
  "solid-danger-md": () => <Button variant="solid" intent="danger" size="md">{LABEL}</Button>,
  "outline-neutral": () => <Button variant="outline" intent="neutral">{LABEL}</Button>,
  "ghost-with-icon": () => <Button variant="ghost" intent="neutral" iconStart={SLOT("arrow-left")}>{LABEL}</Button>,
  "link-primary": () => <Button variant="link" intent="primary" as="a">{LABEL}</Button>,
  "loading": () => <Button variant="solid" intent="primary" loading>{LABEL}</Button>,
  "block-mobile": () => <Button variant="solid" intent="primary" block size="lg">{LABEL}</Button>,
};
