// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/button.yaml

import { h, type VNode } from "vue";
import { Button } from "@teseor/vue";

const SLOT = (name: string) => () => h("span", { "data-fixture-slot": name });
const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "solid-primary": () => h(Button, { "variant": "solid", "intent": "primary" }, { default: LABEL }),
  "solid-danger-md": () => h(Button, { "variant": "solid", "intent": "danger", "size": "md" }, { default: LABEL }),
  "outline-neutral": () => h(Button, { "variant": "outline", "intent": "neutral" }, { default: LABEL }),
  "ghost-with-icon": () => h(Button, { "variant": "ghost", "intent": "neutral" }, { default: LABEL, iconStart: SLOT("arrow-left") }),
  "link-primary": () => h(Button, { "variant": "link", "intent": "primary", "as": "a" }, { default: LABEL }),
  "loading": () => h(Button, { "variant": "solid", "intent": "primary", "loading": true }, { default: LABEL }),
  "block-mobile": () => h(Button, { "variant": "solid", "intent": "primary", "block": true, "size": "lg" }, { default: LABEL }),
  "m-ghost-danger-lg": () => h(Button, { "variant": "ghost", "intent": "danger", "size": "lg" }, { default: LABEL }),
  "m-outline-danger-md": () => h(Button, { "variant": "outline", "intent": "danger", "size": "md" }, { default: LABEL }),
  "m-solid-danger-sm": () => h(Button, { "variant": "solid", "intent": "danger", "size": "sm" }, { default: LABEL }),
  "m-link-neutral-lg": () => h(Button, { "variant": "link", "intent": "neutral", "size": "lg" }, { default: LABEL }),
  "m-solid-neutral-lg": () => h(Button, { "variant": "solid", "intent": "neutral", "size": "lg" }, { default: LABEL }),
  "m-ghost-neutral-md": () => h(Button, { "variant": "ghost", "intent": "neutral", "size": "md" }, { default: LABEL }),
  "m-link-neutral-sm": () => h(Button, { "variant": "link", "intent": "neutral", "size": "sm" }, { default: LABEL }),
  "m-outline-neutral-sm": () => h(Button, { "variant": "outline", "intent": "neutral", "size": "sm" }, { default: LABEL }),
  "m-outline-primary-lg": () => h(Button, { "variant": "outline", "intent": "primary", "size": "lg" }, { default: LABEL }),
  "m-solid-primary-lg": () => h(Button, { "variant": "solid", "intent": "primary", "size": "lg" }, { default: LABEL }),
  "m-link-primary-md": () => h(Button, { "variant": "link", "intent": "primary", "size": "md" }, { default: LABEL }),
  "m-ghost-primary-sm": () => h(Button, { "variant": "ghost", "intent": "primary", "size": "sm" }, { default: LABEL }),
  "m-solid-success-lg": () => h(Button, { "variant": "solid", "intent": "success", "size": "lg" }, { default: LABEL }),
  "m-ghost-success-md": () => h(Button, { "variant": "ghost", "intent": "success", "size": "md" }, { default: LABEL }),
  "m-outline-success-sm": () => h(Button, { "variant": "outline", "intent": "success", "size": "sm" }, { default: LABEL }),
  "m-ghost-warning-lg": () => h(Button, { "variant": "ghost", "intent": "warning", "size": "lg" }, { default: LABEL }),
  "m-solid-warning-md": () => h(Button, { "variant": "solid", "intent": "warning", "size": "md" }, { default: LABEL }),
  "m-outline-warning-sm": () => h(Button, { "variant": "outline", "intent": "warning", "size": "sm" }, { default: LABEL }),
};
