// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/center.yaml

import { h, type VNode } from "vue";
import { Center } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Center, {}, { default: LABEL }),
  "screen": () => h(Center, { "minHeight": "screen" }, { default: LABEL }),
  "responsive": () => h(Center, { "minHeight": { "md": "screen" } }, { default: LABEL }),
};
