// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/checkbox.yaml

import { Checkbox } from "@teseor/react";
import type { ReactNode } from "react";


export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Checkbox />,
  "checked": () => <Checkbox defaultChecked />,
  "indeterminate": () => <Checkbox indeterminate />,
  "size-sm": () => <Checkbox size="sm" />,
  "size-lg": () => <Checkbox size="lg" />,
  "size-lg-checked": () => <Checkbox size="lg" defaultChecked />,
  "disabled": () => <Checkbox disabled />,
  "disabled-checked": () => <Checkbox disabled defaultChecked />,
  "form-control": () => <Checkbox name="terms" form="signup" required />,
};
