// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/checkbox.yaml

import { h, type VNode } from "vue";
import { Checkbox } from "@teseor/vue";


export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Checkbox, {}),
  "checked": () => h(Checkbox, { "defaultChecked": true }),
  "indeterminate": () => h(Checkbox, { "indeterminate": true }),
  "size-sm": () => h(Checkbox, { "size": "sm" }),
  "size-lg": () => h(Checkbox, { "size": "lg" }),
  "size-lg-checked": () => h(Checkbox, { "size": "lg", "defaultChecked": true }),
  "disabled": () => h(Checkbox, { "disabled": true }),
  "disabled-checked": () => h(Checkbox, { "disabled": true, "defaultChecked": true }),
  "form-control": () => h(Checkbox, { "name": "terms", "form": "signup", "required": true }),
};
