// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { Cluster } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "gap-3": () => <Cluster gap="3">{LABEL}</Cluster>,
  "gap-0": () => <Cluster gap="0">{LABEL}</Cluster>,
  "justify-between": () => <Cluster gap="3" justify="between">{LABEL}</Cluster>,
  "justify-around": () => <Cluster gap="2" justify="around">{LABEL}</Cluster>,
  "align-center": () => <Cluster gap="3" align="center">{LABEL}</Cluster>,
  "align-baseline": () => <Cluster gap="2" align="baseline">{LABEL}</Cluster>,
  "responsive-gap": () => <Cluster gap={{ "base": "2", "md": "4" }}>{LABEL}</Cluster>,
  "responsive-justify": () => <Cluster gap="3" justify={{ "base": "start", "md": "between" }}>{LABEL}</Cluster>,
};
