// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { Cluster } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "gap-3": () => <Cluster gap="3">{LABEL}</Cluster>,
  "gap-0": () => <Cluster gap="0">{LABEL}</Cluster>,
  "justify-between": () => <Cluster gap="3" justify="between">{LABEL}</Cluster>,
  "justify-around": () => <Cluster gap="2" justify="around">{LABEL}</Cluster>,
  "align-center": () => <Cluster gap="3" align="center">{LABEL}</Cluster>,
  "align-baseline": () => <Cluster gap="2" align="baseline">{LABEL}</Cluster>,
  "responsive-gap": () => <Cluster gap={{ "base": "2", "md": "4" }}>{LABEL}</Cluster>,
  "responsive-justify": () => <Cluster gap="3" justify={{ "base": "start", "md": "between" }}>{LABEL}</Cluster>,
  "cov-baseline-around": () => <Cluster align="baseline" justify="around">{LABEL}</Cluster>,
  "cov-baseline-between": () => <Cluster align="baseline" justify="between">{LABEL}</Cluster>,
  "cov-baseline-center": () => <Cluster align="baseline" justify="center">{LABEL}</Cluster>,
  "cov-baseline-end": () => <Cluster align="baseline" justify="end">{LABEL}</Cluster>,
  "cov-baseline-start": () => <Cluster align="baseline" justify="start">{LABEL}</Cluster>,
  "cov-center-around": () => <Cluster align="center" justify="around">{LABEL}</Cluster>,
  "cov-center-between": () => <Cluster align="center" justify="between">{LABEL}</Cluster>,
  "cov-center-center": () => <Cluster align="center" justify="center">{LABEL}</Cluster>,
  "cov-center-end": () => <Cluster align="center" justify="end">{LABEL}</Cluster>,
  "cov-center-start": () => <Cluster align="center" justify="start">{LABEL}</Cluster>,
  "cov-end-around": () => <Cluster align="end" justify="around">{LABEL}</Cluster>,
  "cov-end-between": () => <Cluster align="end" justify="between">{LABEL}</Cluster>,
  "cov-end-center": () => <Cluster align="end" justify="center">{LABEL}</Cluster>,
  "cov-end-end": () => <Cluster align="end" justify="end">{LABEL}</Cluster>,
  "cov-end-start": () => <Cluster align="end" justify="start">{LABEL}</Cluster>,
  "cov-start-around": () => <Cluster align="start" justify="around">{LABEL}</Cluster>,
  "cov-start-between": () => <Cluster align="start" justify="between">{LABEL}</Cluster>,
  "cov-start-center": () => <Cluster align="start" justify="center">{LABEL}</Cluster>,
  "cov-start-end": () => <Cluster align="start" justify="end">{LABEL}</Cluster>,
  "cov-start-start": () => <Cluster align="start" justify="start">{LABEL}</Cluster>,
  "cov-stretch-around": () => <Cluster align="stretch" justify="around">{LABEL}</Cluster>,
  "cov-stretch-between": () => <Cluster align="stretch" justify="between">{LABEL}</Cluster>,
  "cov-stretch-center": () => <Cluster align="stretch" justify="center">{LABEL}</Cluster>,
  "cov-stretch-end": () => <Cluster align="stretch" justify="end">{LABEL}</Cluster>,
  "cov-stretch-start": () => <Cluster align="stretch" justify="start">{LABEL}</Cluster>,
};
