// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/cluster.yaml

import { h, type VNode } from "vue";
import { Cluster } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "gap-3": () => h(Cluster, { "gap": "3" }, { default: LABEL }),
  "gap-0": () => h(Cluster, { "gap": "0" }, { default: LABEL }),
  "justify-between": () => h(Cluster, { "gap": "3", "justify": "between" }, { default: LABEL }),
  "justify-around": () => h(Cluster, { "gap": "2", "justify": "around" }, { default: LABEL }),
  "align-center": () => h(Cluster, { "gap": "3", "align": "center" }, { default: LABEL }),
  "align-baseline": () => h(Cluster, { "gap": "2", "align": "baseline" }, { default: LABEL }),
  "responsive-gap": () => h(Cluster, { "gap": { "base": "2", "md": "4" } }, { default: LABEL }),
  "responsive-justify": () => h(Cluster, { "gap": "3", "justify": { "base": "start", "md": "between" } }, { default: LABEL }),
  "cov-baseline-around": () => h(Cluster, { "align": "baseline", "justify": "around" }, { default: LABEL }),
  "cov-baseline-between": () => h(Cluster, { "align": "baseline", "justify": "between" }, { default: LABEL }),
  "cov-baseline-center": () => h(Cluster, { "align": "baseline", "justify": "center" }, { default: LABEL }),
  "cov-baseline-end": () => h(Cluster, { "align": "baseline", "justify": "end" }, { default: LABEL }),
  "cov-baseline-start": () => h(Cluster, { "align": "baseline", "justify": "start" }, { default: LABEL }),
  "cov-center-around": () => h(Cluster, { "align": "center", "justify": "around" }, { default: LABEL }),
  "cov-center-between": () => h(Cluster, { "align": "center", "justify": "between" }, { default: LABEL }),
  "cov-center-center": () => h(Cluster, { "align": "center", "justify": "center" }, { default: LABEL }),
  "cov-center-end": () => h(Cluster, { "align": "center", "justify": "end" }, { default: LABEL }),
  "cov-center-start": () => h(Cluster, { "align": "center", "justify": "start" }, { default: LABEL }),
  "cov-end-around": () => h(Cluster, { "align": "end", "justify": "around" }, { default: LABEL }),
  "cov-end-between": () => h(Cluster, { "align": "end", "justify": "between" }, { default: LABEL }),
  "cov-end-center": () => h(Cluster, { "align": "end", "justify": "center" }, { default: LABEL }),
  "cov-end-end": () => h(Cluster, { "align": "end", "justify": "end" }, { default: LABEL }),
  "cov-end-start": () => h(Cluster, { "align": "end", "justify": "start" }, { default: LABEL }),
  "cov-start-around": () => h(Cluster, { "align": "start", "justify": "around" }, { default: LABEL }),
  "cov-start-between": () => h(Cluster, { "align": "start", "justify": "between" }, { default: LABEL }),
  "cov-start-center": () => h(Cluster, { "align": "start", "justify": "center" }, { default: LABEL }),
  "cov-start-end": () => h(Cluster, { "align": "start", "justify": "end" }, { default: LABEL }),
  "cov-start-start": () => h(Cluster, { "align": "start", "justify": "start" }, { default: LABEL }),
  "cov-stretch-around": () => h(Cluster, { "align": "stretch", "justify": "around" }, { default: LABEL }),
  "cov-stretch-between": () => h(Cluster, { "align": "stretch", "justify": "between" }, { default: LABEL }),
  "cov-stretch-center": () => h(Cluster, { "align": "stretch", "justify": "center" }, { default: LABEL }),
  "cov-stretch-end": () => h(Cluster, { "align": "stretch", "justify": "end" }, { default: LABEL }),
  "cov-stretch-start": () => h(Cluster, { "align": "stretch", "justify": "start" }, { default: LABEL }),
};
