// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/code.yaml

import { Code } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Code>{LABEL}</Code>,
};
