// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/code.yaml

import { h, type VNode } from "vue";
import { Code } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Code, {}, { default: LABEL }),
};
