// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/codeblock.yaml

import { h, type VNode } from "vue";
import { Codeblock } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Codeblock, {}, { default: LABEL }),
};
