// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/divider.yaml

import { Divider } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Divider>{LABEL}</Divider>,
  "vertical": () => <Divider orientation="vertical">{LABEL}</Divider>,
  "decorative": () => <Divider decorative>{LABEL}</Divider>,
};
