// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/dot.yaml

import { Dot } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Dot>{LABEL}</Dot>,
  "success": () => <Dot color="success">{LABEL}</Dot>,
  "small": () => <Dot size="sm">{LABEL}</Dot>,
  "status-online": () => <Dot status="online">{LABEL}</Dot>,
  "status-busy": () => <Dot status="busy">{LABEL}</Dot>,
  "labeled": () => <Dot label="Online">{LABEL}</Dot>,
};
