// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/icon.yaml

import { Icon } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Icon>{LABEL}</Icon>,
  "small": () => <Icon size="sm">{LABEL}</Icon>,
  "large": () => <Icon size="lg">{LABEL}</Icon>,
  "colored-success": () => <Icon color="success">{LABEL}</Icon>,
  "labeled": () => <Icon label="Settings">{LABEL}</Icon>,
};
