// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/icon.yaml

import { h, type VNode } from "vue";
import { Icon } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Icon, {}, { default: LABEL }),
  "small": () => h(Icon, { "size": "sm" }, { default: LABEL }),
  "large": () => h(Icon, { "size": "lg" }, { default: LABEL }),
  "colored-success": () => h(Icon, { "color": "success" }, { default: LABEL }),
  "labeled": () => h(Icon, { "label": "Settings" }, { default: LABEL }),
};
