// AUTOGENERATED by gen-tests. Do not edit.

import type { ReactNode } from "react";
import { fixtures as blockquoteFixtures } from "./Blockquote.react.tsx";
import { fixtures as buttonFixtures } from "./Button.react.tsx";
import { fixtures as checkboxFixtures } from "./Checkbox.react.tsx";
import { fixtures as clusterFixtures } from "./Cluster.react.tsx";
import { fixtures as codeFixtures } from "./Code.react.tsx";
import { fixtures as codeblockFixtures } from "./Codeblock.react.tsx";
import { fixtures as dividerFixtures } from "./Divider.react.tsx";
import { fixtures as headingFixtures } from "./Heading.react.tsx";
import { fixtures as imageFixtures } from "./Image.react.tsx";
import { fixtures as inputFixtures } from "./Input.react.tsx";
import { fixtures as kbdFixtures } from "./Kbd.react.tsx";
import { fixtures as linkFixtures } from "./Link.react.tsx";
import { fixtures as listFixtures } from "./List.react.tsx";
import { fixtures as radioFixtures } from "./Radio.react.tsx";
import { fixtures as selectFixtures } from "./Select.react.tsx";
import { fixtures as stackFixtures } from "./Stack.react.tsx";
import { fixtures as switchFixtures } from "./Switch.react.tsx";
import { fixtures as textFixtures } from "./Text.react.tsx";
import { fixtures as textareaFixtures } from "./Textarea.react.tsx";

export const reactFixtures: Record<string, Record<string, () => ReactNode>> = {
  blockquote: blockquoteFixtures,
  button: buttonFixtures,
  checkbox: checkboxFixtures,
  cluster: clusterFixtures,
  code: codeFixtures,
  codeblock: codeblockFixtures,
  divider: dividerFixtures,
  heading: headingFixtures,
  image: imageFixtures,
  input: inputFixtures,
  kbd: kbdFixtures,
  link: linkFixtures,
  list: listFixtures,
  radio: radioFixtures,
  select: selectFixtures,
  stack: stackFixtures,
  switch: switchFixtures,
  text: textFixtures,
  textarea: textareaFixtures,
};
