// AUTOGENERATED by gen-tests. Do not edit.

import type { VNode } from "vue";
import { fixtures as buttonFixtures } from "./Button.vue.ts";
import { fixtures as clusterFixtures } from "./Cluster.vue.ts";
import { fixtures as stackFixtures } from "./Stack.vue.ts";

export const vueFixtures: Record<string, Record<string, () => VNode>> = {
  button: buttonFixtures,
  cluster: clusterFixtures,
  stack: stackFixtures,
};
