// AUTOGENERATED by gen-tests. Do not edit.

import type { ReactNode } from "react";
import { fixtures as blockquoteFixtures } from "./Blockquote.react.tsx";
import { fixtures as buttonFixtures } from "./Button.react.tsx";
import { fixtures as clusterFixtures } from "./Cluster.react.tsx";
import { fixtures as codeFixtures } from "./Code.react.tsx";
import { fixtures as codeblockFixtures } from "./Codeblock.react.tsx";
import { fixtures as headingFixtures } from "./Heading.react.tsx";
import { fixtures as imageFixtures } from "./Image.react.tsx";
import { fixtures as kbdFixtures } from "./Kbd.react.tsx";
import { fixtures as linkFixtures } from "./Link.react.tsx";
import { fixtures as listFixtures } from "./List.react.tsx";
import { fixtures as stackFixtures } from "./Stack.react.tsx";
import { fixtures as textFixtures } from "./Text.react.tsx";

export const reactFixtures: Record<string, Record<string, () => ReactNode>> = {
  blockquote: blockquoteFixtures,
  button: buttonFixtures,
  cluster: clusterFixtures,
  code: codeFixtures,
  codeblock: codeblockFixtures,
  heading: headingFixtures,
  image: imageFixtures,
  kbd: kbdFixtures,
  link: linkFixtures,
  list: listFixtures,
  stack: stackFixtures,
  text: textFixtures,
};
