// AUTOGENERATED by gen-tests. Do not edit.

import type { VNode } from "vue";
import { fixtures as buttonFixtures } from "./Button.vue.ts";
import { fixtures as clusterFixtures } from "./Cluster.vue.ts";
import { fixtures as codeFixtures } from "./Code.vue.ts";
import { fixtures as codeblockFixtures } from "./Codeblock.vue.ts";
import { fixtures as headingFixtures } from "./Heading.vue.ts";
import { fixtures as listFixtures } from "./List.vue.ts";
import { fixtures as stackFixtures } from "./Stack.vue.ts";
import { fixtures as textFixtures } from "./Text.vue.ts";

export const vueFixtures: Record<string, Record<string, () => VNode>> = {
  button: buttonFixtures,
  cluster: clusterFixtures,
  code: codeFixtures,
  codeblock: codeblockFixtures,
  heading: headingFixtures,
  list: listFixtures,
  stack: stackFixtures,
  text: textFixtures,
};
