// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/kbd.yaml

import { Kbd } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Kbd>{LABEL}</Kbd>,
  "small": () => <Kbd size="sm">{LABEL}</Kbd>,
  "large": () => <Kbd size="lg">{LABEL}</Kbd>,
};
