// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/kbd.yaml

import { h, type VNode } from "vue";
import { Kbd } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Kbd, {}, { default: LABEL }),
  "small": () => h(Kbd, { "size": "sm" }, { default: LABEL }),
  "large": () => h(Kbd, { "size": "lg" }, { default: LABEL }),
};
