// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/link.yaml

import { Link } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Link>{LABEL}</Link>,
  "subtle": () => <Link variant="subtle">{LABEL}</Link>,
  "plain": () => <Link variant="plain">{LABEL}</Link>,
};
