// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/link.yaml

import { h, type VNode } from "vue";
import { Link } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Link, {}, { default: LABEL }),
  "subtle": () => h(Link, { "variant": "subtle" }, { default: LABEL }),
  "plain": () => h(Link, { "variant": "plain" }, { default: LABEL }),
};
