// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/radio.yaml

import { Radio } from "@teseor/react";
import type { ReactNode } from "react";


export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Radio />,
  "checked": () => <Radio defaultChecked />,
  "size-sm": () => <Radio size="sm" />,
  "size-lg": () => <Radio size="lg" />,
  "size-lg-checked": () => <Radio size="lg" defaultChecked />,
  "disabled": () => <Radio disabled />,
  "disabled-checked": () => <Radio disabled defaultChecked />,
  "form-control": () => <Radio name="plan" form="signup" required />,
};
