// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/radio.yaml

import { h, type VNode } from "vue";
import { Radio } from "@teseor/vue";


export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Radio, {}),
  "checked": () => h(Radio, { "defaultChecked": true }),
  "size-sm": () => h(Radio, { "size": "sm" }),
  "size-lg": () => h(Radio, { "size": "lg" }),
  "size-lg-checked": () => h(Radio, { "size": "lg", "defaultChecked": true }),
  "disabled": () => h(Radio, { "disabled": true }),
  "disabled-checked": () => h(Radio, { "disabled": true, "defaultChecked": true }),
  "form-control": () => h(Radio, { "name": "plan", "form": "signup", "required": true }),
};
