// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/select.yaml

import { Select } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Select>{LABEL}</Select>,
  "variant-outline": () => <Select variant="outline">{LABEL}</Select>,
  "variant-subtle": () => <Select variant="subtle">{LABEL}</Select>,
  "variant-plain": () => <Select variant="plain">{LABEL}</Select>,
  "size-sm": () => <Select size="sm">{LABEL}</Select>,
  "size-lg": () => <Select size="lg">{LABEL}</Select>,
  "multiple": () => <Select multiple>{LABEL}</Select>,
  "invalid": () => <Select invalid>{LABEL}</Select>,
  "disabled": () => <Select disabled>{LABEL}</Select>,
  "form-control": () => <Select name="country" form="contact" required>{LABEL}</Select>,
};
