// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/select.yaml

import { Select } from "@teseor/react";
import type { ReactNode } from "react";


export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Select><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "variant-outline": () => <Select variant="outline"><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "variant-subtle": () => <Select variant="subtle"><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "variant-plain": () => <Select variant="plain"><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "size-sm": () => <Select size="sm"><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "size-lg": () => <Select size="lg"><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "multiple": () => <Select multiple><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "invalid": () => <Select invalid><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "disabled": () => <Select disabled><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
  "form-control": () => <Select name="country" form="contact" required><option value="us">United States</option><option value="br">Brazil</option><option value="jp">Japan</option></Select>,
};
