// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/stack.yaml

import { Stack } from "@teseor/react";
import type { ReactNode } from "react";

const SLOT = (name: string): ReactNode => <span data-fixture-slot={name} />;
const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "gap-3": () => <Stack gap="3">{LABEL}</Stack>,
  "gap-0": () => <Stack gap="0">{LABEL}</Stack>,
  "align-center": () => <Stack gap="4" align="center">{LABEL}</Stack>,
  "align-stretch": () => <Stack gap="2" align="stretch">{LABEL}</Stack>,
  "responsive-gap": () => <Stack gap={{ "base": "2", "md": "4", "lg": "6" }}>{LABEL}</Stack>,
  "responsive-align": () => <Stack gap="3" align={{ "base": "start", "md": "center" }}>{LABEL}</Stack>,
  "gap-and-align": () => <Stack gap="5" align="end">{LABEL}</Stack>,
};
