// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/stack.yaml

import { h, type VNode } from "vue";
import { Stack } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "gap-3": () => h(Stack, { "gap": "3" }, { default: LABEL }),
  "gap-0": () => h(Stack, { "gap": "0" }, { default: LABEL }),
  "align-center": () => h(Stack, { "gap": "4", "align": "center" }, { default: LABEL }),
  "align-stretch": () => h(Stack, { "gap": "2", "align": "stretch" }, { default: LABEL }),
  "responsive-gap": () => h(Stack, { "gap": { "base": "2", "md": "4", "lg": "6" } }, { default: LABEL }),
  "responsive-align": () => h(Stack, { "gap": "3", "align": { "base": "start", "md": "center" } }, { default: LABEL }),
  "gap-and-align": () => h(Stack, { "gap": "5", "align": "end" }, { default: LABEL }),
  "cov-center": () => h(Stack, { "align": "center" }, { default: LABEL }),
  "cov-end": () => h(Stack, { "align": "end" }, { default: LABEL }),
  "cov-start": () => h(Stack, { "align": "start" }, { default: LABEL }),
  "cov-stretch": () => h(Stack, { "align": "stretch" }, { default: LABEL }),
};
