// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/switch.yaml

import { Switch } from "@teseor/react";
import type { ReactNode } from "react";


export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Switch />,
  "checked": () => <Switch defaultChecked />,
  "size-sm": () => <Switch size="sm" />,
  "size-lg": () => <Switch size="lg" />,
  "size-lg-checked": () => <Switch size="lg" defaultChecked />,
  "disabled": () => <Switch disabled />,
  "disabled-checked": () => <Switch disabled defaultChecked />,
  "form-control": () => <Switch name="notifications" form="settings" required defaultChecked />,
};
