// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/text.yaml

import { h, type VNode } from "vue";
import { Text } from "@teseor/vue";

const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Text, { "as": "span" }, { default: LABEL }),
  "paragraph": () => h(Text, { "as": "p" }, { default: LABEL }),
  "muted-small": () => h(Text, { "as": "span", "variant": "muted", "size": "sm" }, { default: LABEL }),
  "highlight-strong": () => h(Text, { "as": "strong", "variant": "highlight" }, { default: LABEL }),
  "lead-paragraph": () => h(Text, { "as": "p", "size": "lg" }, { default: LABEL }),
};
