// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/textarea.yaml

import { h, type VNode } from "vue";
import { Textarea } from "@teseor/vue";


export const fixtures: Record<string, () => VNode> = {
  "default": () => h(Textarea, { "placeholder": "Your message" }),
  "variant-outline": () => h(Textarea, { "variant": "outline", "placeholder": "Comment" }),
  "variant-subtle": () => h(Textarea, { "variant": "subtle", "placeholder": "Comment" }),
  "variant-plain": () => h(Textarea, { "variant": "plain", "placeholder": "Comment" }),
  "size-sm": () => h(Textarea, { "size": "sm", "placeholder": "Compact" }),
  "size-lg": () => h(Textarea, { "size": "lg", "placeholder": "Emphatic" }),
  "rows-2": () => h(Textarea, { "rows": 2, "placeholder": "Two rows" }),
  "rows-6": () => h(Textarea, { "rows": 6, "placeholder": "Six rows" }),
  "resize-none": () => h(Textarea, { "resize": "none", "placeholder": "Fixed height" }),
  "resize-both": () => h(Textarea, { "resize": "both", "placeholder": "Resize both directions" }),
  "invalid": () => h(Textarea, { "invalid": true, "placeholder": "Required" }),
  "disabled": () => h(Textarea, { "disabled": true, "placeholder": "Disabled" }),
  "form-control": () => h(Textarea, { "name": "comment", "form": "contact", "required": true, "readOnly": true, "placeholder": "Form-control attributes pass-through" }),
};
