// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/text.yaml

import { Text } from "@teseor/react";
import type { ReactNode } from "react";

const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
  "default": () => <Text as="span">{LABEL}</Text>,
  "paragraph": () => <Text as="p">{LABEL}</Text>,
  "muted-small": () => <Text as="span" variant="muted" size="sm">{LABEL}</Text>,
  "highlight-strong": () => <Text as="strong" variant="highlight">{LABEL}</Text>,
  "lead-paragraph": () => <Text as="p" size="lg">{LABEL}</Text>,
};
