import { pascalCase } from "../../../lib/pascal-case.ts";
import type { Spec } from "../../gen-contract.ts";
import { coverageFixtures, type TestsSpec } from "../_shared/coverage.ts";
import { renderVueFixtureBody } from "../_shared/fixture-bodies.ts";
import { hasSlotProps, quote } from "../_shared/printers.ts";

export function renderVueFixtureFile(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const examples = spec.examples ?? [];
  const coverage = coverageFixtures(spec as TestsSpec);
  const exampleEntries = examples
    .filter((e): e is { id: string; props?: Record<string, unknown> } => typeof e.id === "string")
    .map((e) => `  ${quote(e.id)}: () => ${renderVueFixtureBody(spec, Name, e.props ?? {})},`);
  const coverageEntries = coverage.map(
    (m) => `  ${quote(m.id)}: () => ${renderVueFixtureBody(spec, Name, m.props)},`,
  );
  const entries = [...exampleEntries, ...coverageEntries].join("\n");
  const slotHelper = hasSlotProps(spec)
    ? `const SLOT = (name: string) => () => h("span", { "data-fixture-slot": name });\n`
    : "";
  const labelHelper = entries.includes("default: LABEL") ? `const LABEL = () => "Label";\n` : "";
  return `// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/${spec.name}.yaml

import { h, type VNode } from "vue";
import { ${Name} } from "@teseor/vue";

${slotHelper}${labelHelper}
export const fixtures: Record<string, () => VNode> = {
${entries}
};
`;
}
