// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/avatar.yaml

export type AvatarSize = "sm" | "md" | "lg";

export type AvatarShape = "circle" | "square";

export type AvatarColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

export type AvatarProps = {
  size?: AvatarSize;
  /** Image source URL. When set and the image loads, the avatar renders `<img>`. On `onError`, falls back to the initials or empty box. */
  src?: string;
  /** Alt text for the image. Required when `src` is set and the image carries standalone meaning; empty string when the avatar is decorative inside a labeled context. */
  alt?: string;
  /** Person's name. Drives the auto-derived initials fallback when `src` is missing or fails to load. */
  name?: string;
  /** Explicit initials override. When set, wins over the auto-derived "first letter of first + last whitespace-split token" rule. */
  initials?: string;
  /** Outer corner shape. Default is `circle` via the CSS layer (absence-of-attr). */
  shape?: AvatarShape;
  /** Semantic background color of the fallback (initials or empty) box. Default is `neutral` via the CSS layer. */
  color?: AvatarColor;
};
