// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/badge.yaml

export type BadgeVariant = "solid" | "outline" | "ghost";

export type BadgeIntent = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

export type BadgeSize = "sm" | "md" | "lg";

export type BadgeShape = "rounded" | "pill";

export type BadgeProps = {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  /** Corner shape. `rounded` is the default (token-controlled radius); `pill` fully rounds the inline ends for decorative chip-style badges. */
  shape?: BadgeShape;
  /** Decorative icon rendered before the label in the inline direction. Wrapped in a `<span data-badge-icon="">` element; the consumer's icon component carries any `aria-hidden` it needs. */
  icon?: unknown;
};
