// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/blockquote.yaml

export type BlockquoteVariant = "default" | "subtle";

export type BlockquoteProps = {
  variant?: BlockquoteVariant;
};
