// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/button.yaml

import type { Responsive } from "./_responsive.ts";

export type ButtonVariant = "solid" | "outline" | "ghost" | "link";

export type ButtonIntent = "primary" | "neutral" | "success" | "warning" | "danger" | "info";

export type ButtonSize = "sm" | "md" | "lg";

export type ButtonAs = "button" | "a";

/**
 * Runtime constraints (enforced in dev builds):
 *   when {"variant":"link"} forbid {"intent":["danger","warning","success"]}
 *     Link variant is text-colored; non-neutral intent fills have no surface to apply to.
 *   when {"loading":true} forbid {"disabled":true}
 *     Loading already disables interaction; disabling on top is redundant.
 */
export type ButtonProps = {
  variant?: ButtonVariant;
  intent?: ButtonIntent;
  size?: ButtonSize;
  /** Polymorphic root element. Defaults to `button`; set to `a` for link-shaped triggers (paired with `variant: link`). */
  as?: ButtonAs;
  /** Disables interaction and applies the disabled visual state. Mapped to the native `disabled` attribute on `button`, `aria-disabled="true"` otherwise. */
  disabled?: boolean;
  /** Shows a spinner in place of the label and disables interaction. The original label stays in the accessibility tree. */
  loading?: boolean;
  /** Icon rendered before the label in the inline direction. Slot size scales with `size`. Accepts any node (icon component, SVG, etc.). */
  iconStart?: unknown;
  /** Icon rendered after the label in the inline direction. Accepts any node. */
  iconEnd?: unknown;
  /** Stretches the button to the inline-size of its container. Responsive so layouts can pin block-width on mobile and shrink to content above. */
  block?: Responsive<boolean>;
};
