// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/cluster.yaml

export type ClusterAlign = "start" | "center" | "end" | "stretch" | "baseline";

export type ClusterJustify = "start" | "center" | "end" | "between" | "around";

export type ClusterProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string;
  /** Block-axis alignment of children. */
  align?: ClusterAlign;
  /** Inline-axis distribution of children. */
  justify?: ClusterJustify;
};
