// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/cluster.yaml

export type ClusterProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string;
  /** Block-axis alignment of children. One of `start`, `center`, `end`, `stretch`, `baseline`. */
  align?: string;
  /** Inline-axis distribution. One of `start`, `center`, `end`, `between`, `around`. */
  justify?: string;
};
