// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/divider.yaml

export type DividerOrientation = "horizontal" | "vertical";

export type DividerProps = {
  /** Axis of the rule. Absence-of-attr selects `horizontal` — codegen falls back to the first map key and the `<hr>` carries the native horizontal orientation. Pass `vertical` to render a `<div>` with explicit `role="separator"` + `aria-orientation="vertical"`. */
  orientation?: DividerOrientation;
  /** Removes the divider from the accessibility tree (`role="none"` + `aria-hidden="true"`). Use when the rule is purely visual and not announcing a structural boundary. */
  decorative?: boolean;
};
