// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/dot.yaml

export type DotSize = "sm" | "md";

export type DotColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

export type DotStatus = "online" | "offline" | "away" | "busy" | "idle";

export type DotProps = {
  size?: DotSize;
  /** Semantic color. Absence-of-attr renders the neutral base styling. */
  color?: DotColor;
  /** Sugar prop for common presence states. Emits `data-status` so status-driven styling can override `color`. Independent of `color` — the two compose. */
  status?: DotStatus;
  /** Accessible label. When set, the dot becomes meaningful (`role="img"` + `aria-label={label}`); when unset, the dot is decorative (`role="none"` + `aria-hidden="true"`). */
  label?: string;
};
