// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/icon.yaml

export type IconSize = "sm" | "md" | "lg";

export type IconColor = "neutral" | "primary" | "success" | "warning" | "danger" | "info";

export type IconProps = {
  size?: IconSize;
  /** Semantic color override. Absence-of-attr keeps the SVG on `currentColor` (inherits from the parent's text color); setting a value swaps the `--t-icon-fg` slot to the matching semantic token. */
  color?: IconColor;
  /** Accessible name. When set, the wrapper carries `aria-label={label}` and drops `aria-hidden`. When unset, the wrapper carries `aria-hidden="true"` and is invisible to assistive tech — the common case for icons inside a labeled `<button>`. */
  label?: string;
};
