// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/image.yaml

import type { Responsive } from "./_responsive.ts";

export type ImageFit = "cover" | "contain" | "fill" | "none" | "scale-down";

export type ImageProps = {
  /** Maps to `object-fit`. Absence-of-attr leaves the default (`fill`). Responsive form (`{ base, sm, md, … }`) emits per-breakpoint `data-fit-{bp}` attrs for art-direction without `<picture>`. */
  fit?: Responsive<ImageFit>;
};
