// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/input.yaml

export type InputVariant = "outline" | "subtle" | "plain";

export type InputSize = "sm" | "md" | "lg";

export type InputProps = {
  variant?: InputVariant;
  size?: InputSize;
  /** Marks the field as invalid for styling. Emits `data-invalid="true"` on the root. ARIA wiring (`aria-invalid`) is consumer-supplied or comes from the Field composite (tracked under #692). */
  invalid?: boolean;
};
