// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/modal.yaml

export type ModalProps = {
  /** Open state. Uncontrolled by default; pass `open` and optionally `onOpenChange` to drive it from the consumer. */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Fires when the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Modal content. Plain text or rich children via slot. */
  title?: string;
};
