// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/modal.yaml

export type ModalProps = {
  /** Open state. Uncontrolled by default; pass `open` and optionally `onOpenChange` to drive it from the consumer. */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Fires when the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Modal body text. Plain string only; rich content support lands when the spec grows a real content slot. */
  title?: string;
};
