// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/pagination.yaml

export type PaginationPageItem = {
  /** Stable item identity; required. */
  id: string;
  /** Page label rendered as the item text. */
  label?: string;
  /** Marks the active page; exposed as `data-current`. */
  current?: boolean;
};

export type PaginationProps = {
  /** Items rendered by the repeating `page` part. */
  pages?: ReadonlyArray<PaginationPageItem>;
};
