// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/select.yaml

export type SelectVariant = "outline" | "subtle" | "plain";

export type SelectSize = "sm" | "md" | "lg";

export type SelectProps = {
  variant?: SelectVariant;
  size?: SelectSize;
  /** Marks the field as invalid for styling. Emits `data-invalid="true"` on the root. ARIA wiring (`aria-invalid`) is consumer-supplied or comes from the Field composite (tracked under #692). */
  invalid?: boolean;
};
