// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/stack.yaml

export type StackAlign = "start" | "center" | "end" | "stretch";

export type StackProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string;
  /** Inline-axis alignment of children. */
  align?: StackAlign;
};
