// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/stack.yaml

import type { Responsive } from "./_responsive.ts";

export type StackAlign = "start" | "center" | "end" | "stretch";

export type StackProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: Responsive<string>;
  /** Inline-axis alignment of children. */
  align?: Responsive<StackAlign>;
};
