// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/stack.yaml

export type StackProps = {
  /** Spacing between children. Accepts a token suffix from the `--t-space-*` scale (`0`–`8`). */
  gap?: string;
  /** Inline-axis alignment of children. One of `start`, `center`, `end`, `stretch`. */
  align?: string;
};
