// AUTOGENERATED by gen-contract. Do not edit.
// Source: specs/textarea.yaml

export type TextareaVariant = "outline" | "subtle" | "plain";

export type TextareaSize = "sm" | "md" | "lg";

export type TextareaResize = "none" | "vertical" | "horizontal" | "both";

export type TextareaProps = {
  variant?: TextareaVariant;
  size?: TextareaSize;
  /** Maps to CSS `resize`. Absence-of-attr leaves the base CSS default (`vertical`). Set to `none` for a fixed-height field, `both` for free resizing. */
  resize?: TextareaResize;
  /** Marks the field as invalid for styling. Emits `data-invalid="true"` on the root. ARIA wiring (`aria-invalid`) is consumer-supplied or comes from the Field composite (tracked under #692). */
  invalid?: boolean;
};
