import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import type { GeneratorContext, GeneratorReport } from "../registry.ts";
import { registerGenerator } from "../registry.ts";
import type { Spec } from "./gen-contract.ts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const SPECS_DIR = resolve(REPO_ROOT, "specs");
const REACT_SRC_DIR = resolve(REPO_ROOT, "packages", "react", "src");

const RESPONSIVE_ENUM_PROPS = new Set(["size"]);

function pascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((part) => (part.length === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function mapPropType(specType: string): string {
  switch (specType) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function responsiveType(baseType: string): string {
  return `${baseType} | Partial<Record<"base" | "md" | "lg" | "xl" | "2xl", ${baseType}>>`;
}

function renderWrapper(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const rootClass = spec.rootClass ?? `t-${spec.name}`;

  const responsiveProps: { name: string; isBool: boolean }[] = [];

  const lines: string[] = [];
  lines.push(`"use client";`);
  lines.push("");
  lines.push(`// AUTOGENERATED by gen-react. Do not edit.`);
  lines.push(`// Source: specs/${spec.name}.yaml`);
  lines.push("");
  lines.push(`import "@teseor/css/components/${spec.name}.css";`);
  lines.push(
    `import { type ComponentProps, type ElementType, type ReactNode, type Ref } from "react";`,
  );
  lines.push(`import { dataAttrs } from "./_runtime.ts";`);
  lines.push("");

  if (spec.variants && Object.keys(spec.variants).length > 0) {
    const values = Object.keys(spec.variants).map(quote).join(" | ");
    lines.push(`type ${Name}Variant = ${values};`);
    lines.push("");
  }
  if (spec.intents && Object.keys(spec.intents).length > 0) {
    const values = Object.keys(spec.intents).map(quote).join(" | ");
    lines.push(`type ${Name}Intent = ${values};`);
    lines.push("");
  }
  let sizeIsResponsive = false;
  if (spec.sizes && Object.keys(spec.sizes).length > 0) {
    const values = Object.keys(spec.sizes).map(quote).join(" | ");
    lines.push(`type ${Name}Size = ${values};`);
    lines.push("");
    if (RESPONSIVE_ENUM_PROPS.has("size")) {
      sizeIsResponsive = true;
      responsiveProps.push({ name: "size", isBool: false });
    }
  }

  lines.push(`type ${Name}OwnProps = {`);
  if (spec.variants) lines.push(`  variant?: ${Name}Variant;`);
  if (spec.intents) lines.push(`  intent?: ${Name}Intent;`);
  if (spec.sizes) {
    const sizeType = sizeIsResponsive ? responsiveType(`${Name}Size`) : `${Name}Size`;
    lines.push(`  size?: ${sizeType};`);
  }
  if (spec.props) {
    for (const [propName, propDef] of Object.entries(spec.props)) {
      let baseType: string;
      if (propName === "as") {
        baseType = "ElementType";
      } else if (propDef.slot === true) {
        baseType = "ReactNode";
      } else {
        baseType = mapPropType(propDef.type);
      }
      const isResponsive = propDef.responsive === true;
      const tsType = isResponsive ? responsiveType(baseType) : baseType;
      if (propDef.description) {
        lines.push(`  /** ${propDef.description} */`);
      }
      lines.push(`  ${propName}?: ${tsType};`);
      if (isResponsive) {
        responsiveProps.push({ name: propName, isBool: propDef.type === "boolean" });
      }
    }
  }
  lines.push(`  children?: ReactNode;`);
  lines.push(`  ref?: Ref<HTMLElement>;`);
  lines.push(`};`);
  lines.push("");

  lines.push(`export type ${Name}Props = Readonly<`);
  lines.push(`  ${Name}OwnProps & Omit<ComponentProps<"button">, keyof ${Name}OwnProps>`);
  lines.push(`>;`);
  lines.push("");

  lines.push(`export function ${Name}(props: ${Name}Props) {`);
  lines.push(`  const {`);
  if (spec.variants) lines.push(`    variant,`);
  if (spec.intents) lines.push(`    intent,`);
  if (spec.sizes) lines.push(`    size,`);
  if (spec.props) {
    for (const propName of Object.keys(spec.props)) {
      lines.push(`    ${propName},`);
    }
  }
  lines.push(`    children,`);
  lines.push(`    ref,`);
  lines.push(`    className,`);
  lines.push(`    ...rest`);
  lines.push(`  } = props;`);
  lines.push("");
  lines.push(`  const Component = as ?? "button";`);
  lines.push(`  const isButton = Component === "button";`);
  lines.push(`  const inactive = disabled === true || loading === true;`);
  lines.push(
    `  const mergedClassName = className ? \`${rootClass} \${className}\` : "${rootClass}";`,
  );
  lines.push("");
  lines.push(`  return (`);
  lines.push(`    <Component`);
  lines.push(`      {...rest}`);
  lines.push(`      ref={ref}`);
  lines.push(`      className={mergedClassName}`);
  if (spec.variants) lines.push(`      data-variant={variant}`);
  if (spec.intents) lines.push(`      data-intent={intent}`);
  for (const rp of responsiveProps) {
    lines.push(`      {...dataAttrs("${rp.name}", ${rp.name})}`);
  }
  lines.push(`      data-loading={loading === true ? "true" : undefined}`);
  lines.push(`      disabled={isButton ? inactive : undefined}`);
  lines.push(`      aria-disabled={!isButton && inactive ? "true" : undefined}`);
  lines.push(`      aria-busy={loading === true ? "true" : undefined}`);
  lines.push(`    >`);
  lines.push(`      {iconStart != null ? (`);
  lines.push(`        <span data-button-icon="" data-position="start">`);
  lines.push(`          {iconStart}`);
  lines.push(`        </span>`);
  lines.push(`      ) : null}`);
  lines.push(`      <span data-button-label="">{children}</span>`);
  lines.push(`      {iconEnd != null ? (`);
  lines.push(`        <span data-button-icon="" data-position="end">`);
  lines.push(`          {iconEnd}`);
  lines.push(`        </span>`);
  lines.push(`      ) : null}`);
  lines.push(`      <span data-button-spinner="" aria-hidden="true" />`);
  lines.push(`    </Component>`);
  lines.push(`  );`);
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

function renderRuntime(): string {
  const lines: string[] = [];
  lines.push(`// AUTOGENERATED by gen-react. Do not edit.`);
  lines.push("");
  lines.push(`const RESPONSIVE_KEYS = ["base", "md", "lg", "xl", "2xl"] as const;`);
  lines.push("");
  lines.push(`export function dataAttrs(`);
  lines.push(`  name: string,`);
  lines.push(`  value: unknown,`);
  lines.push(`): Record<string, string | undefined> {`);
  lines.push(`  if (value == null || value === false) return {};`);
  lines.push(`  if (typeof value === "object") {`);
  lines.push(`    const obj = value as Record<string, unknown>;`);
  lines.push(`    const out: Record<string, string | undefined> = {};`);
  lines.push(`    for (const key of RESPONSIVE_KEYS) {`);
  lines.push(`      const v = obj[key];`);
  lines.push(`      if (v == null || v === false) continue;`);
  lines.push(`      const attr = key === "base" ? \`data-\${name}\` : \`data-\${name}-\${key}\`;`);
  lines.push(`      out[attr] = v === true ? "true" : String(v);`);
  lines.push(`    }`);
  lines.push(`    return out;`);
  lines.push(`  }`);
  lines.push(`  return { [\`data-\${name}\`]: value === true ? "true" : String(value) };`);
  lines.push(`}`);
  lines.push("");
  return lines.join("\n");
}

function renderBarrel(names: string[]): string {
  const lines: string[] = [];
  lines.push(`// AUTOGENERATED by gen-react. Do not edit.`);
  lines.push("");
  for (const name of names) {
    const Name = pascalCase(name);
    lines.push(`export { ${Name}, type ${Name}Props } from "./${Name}.tsx";`);
  }
  lines.push("");
  return lines.join("\n");
}

async function loadSpec(name: string): Promise<Spec> {
  const path = resolve(SPECS_DIR, `${name}.yaml`);
  const raw = await readFile(path, "utf8");
  const parsed = parseYaml(raw) as Spec;
  if (parsed.name !== name) {
    throw new Error(`spec name "${parsed.name}" in ${name}.yaml does not match file basename`);
  }
  return parsed;
}

async function listSpecNames(): Promise<string[]> {
  const entries = await readdir(SPECS_DIR);
  return entries
    .filter((f) => f.endsWith(".yaml") && f !== "_vocabulary.yaml")
    .map((f) => f.slice(0, -5))
    .sort();
}

async function emitWrapper(name: string): Promise<string> {
  const spec = await loadSpec(name);
  const content = renderWrapper(spec);
  const outPath = resolve(REACT_SRC_DIR, `${pascalCase(name)}.tsx`);
  await mkdir(REACT_SRC_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitBarrel(names: string[]): Promise<string> {
  const content = renderBarrel(names);
  const outPath = resolve(REACT_SRC_DIR, `index.ts`);
  await mkdir(REACT_SRC_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitRuntime(): Promise<string> {
  const content = renderRuntime();
  const outPath = resolve(REACT_SRC_DIR, `_runtime.ts`);
  await mkdir(REACT_SRC_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function reactGenerator(ctx: GeneratorContext): Promise<GeneratorReport> {
  const requested = ctx.positionals[0];
  const allNames = await listSpecNames();
  const targets = requested ? [requested] : allNames;

  const filesWritten: string[] = [];
  const notes: string[] = [];
  for (const name of targets) {
    const path = await emitWrapper(name);
    filesWritten.push(path);
    notes.push(`react: ${name} -> ${path.replace(`${REPO_ROOT}/`, "")}`);
  }

  const runtimePath = await emitRuntime();
  filesWritten.push(runtimePath);
  notes.push(`react: runtime -> ${runtimePath.replace(`${REPO_ROOT}/`, "")}`);

  const barrelPath = await emitBarrel(allNames);
  filesWritten.push(barrelPath);
  notes.push(`react: barrel -> ${barrelPath.replace(`${REPO_ROOT}/`, "")}`);

  return { filesWritten, notes };
}

registerGenerator("react", reactGenerator);

export { renderBarrel, renderRuntime, renderWrapper };
