import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import { type FlatProp, type FlatSpec, flattenSpec } from "../lib/flatten.ts";
import type { GeneratorContext, GeneratorReport } from "../registry.ts";
import { registerGenerator } from "../registry.ts";
import { Spec as SpecSchema } from "../schema.ts";

/** Re-exported for downstream generators that imported the old atomic-only
 *  shape. The flat shape is a superset; existing usages still resolve. */
export type Spec = FlatSpec;
export type SpecProp = FlatProp;

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const SPECS_DIR = resolve(REPO_ROOT, "specs");
const CONTRACT_SRC_DIR = resolve(REPO_ROOT, "packages", "contract", "src");
const BREAKPOINTS_PATH = resolve(SPECS_DIR, "_breakpoints.yaml");

type BreakpointsConfig = { breakpoints: string[] };

let cachedBreakpoints: string[] | null = null;
async function loadBreakpoints(): Promise<string[]> {
  if (cachedBreakpoints) return cachedBreakpoints;
  const raw = await readFile(BREAKPOINTS_PATH, "utf8");
  const parsed = parseYaml(raw) as BreakpointsConfig;
  cachedBreakpoints = parsed.breakpoints;
  return cachedBreakpoints;
}

function pascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((part) => (part.length === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function mapPropType(specType: string): string {
  switch (specType) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function responsiveType(baseType: string): string {
  return `Responsive<${baseType}>`;
}

function renderContract(spec: FlatSpec): string {
  const Name = pascalCase(spec.name);
  const lines: string[] = [];

  lines.push(`// AUTOGENERATED by gen-contract. Do not edit.`);
  lines.push(`// Source: specs/${spec.name}.yaml`);
  lines.push("");

  const hasResponsive = Object.values(spec.props).some(
    (d) => d.responsive === true && d.slot !== true,
  );
  if (hasResponsive) {
    lines.push(`import type { Responsive } from "./_responsive.ts";`);
    lines.push("");
  }

  if (spec.variants && Object.keys(spec.variants).length > 0) {
    const values = Object.keys(spec.variants).map(quote).join(" | ");
    lines.push(`export type ${Name}Variant = ${values};`);
    lines.push("");
  }
  if (spec.intents && Object.keys(spec.intents).length > 0) {
    const values = Object.keys(spec.intents).map(quote).join(" | ");
    lines.push(`export type ${Name}Intent = ${values};`);
    lines.push("");
  }
  if (spec.sizes && Object.keys(spec.sizes).length > 0) {
    const values = Object.keys(spec.sizes).map(quote).join(" | ");
    lines.push(`export type ${Name}Size = ${values};`);
    lines.push("");
  }

  for (const [propName, propDef] of Object.entries(spec.props)) {
    const values = propDef.values ?? [];
    if (values.length > 0) {
      lines.push(`export type ${Name}${pascalCase(propName)} = ${values.map(quote).join(" | ")};`);
      lines.push("");
    }
  }

  const propLines: string[] = [];
  if (spec.variants) propLines.push(`  variant?: ${Name}Variant;`);
  if (spec.intents) propLines.push(`  intent?: ${Name}Intent;`);
  if (spec.sizes) propLines.push(`  size?: ${Name}Size;`);

  // Atomic specs declare `constraints` at the root; surface them in the
  // contract's JSDoc so consumers see the runtime invariants. Composite specs
  // don't carry constraints at the root.
  if (spec.constraints && spec.constraints.length > 0) {
    lines.push("/**");
    lines.push(" * Runtime constraints (enforced in dev builds):");
    for (const c of spec.constraints) {
      const when = JSON.stringify(c.when ?? {});
      const forbid = JSON.stringify(c.forbid ?? {});
      lines.push(` *   when ${when} forbid ${forbid}`);
      if (c.reason) lines.push(` *     ${c.reason}`);
    }
    lines.push(" */");
  }

  for (const [propName, propDef] of Object.entries(spec.props)) {
    if (propDef.pattern === "controllable" && propDef.type === "boolean") {
      // Expand the controllable triple — `name` + `defaultName` + `onNameChange`.
      const PName = pascalCase(propName);
      if (propDef.description) propLines.push(`  /** ${propDef.description} */`);
      propLines.push(`  ${propName}?: boolean;`);
      propLines.push(`  /** Initial open state (uncontrolled). */`);
      propLines.push(`  default${PName}?: boolean;`);
      propLines.push(`  /** Fires when the open state changes. */`);
      propLines.push(`  on${PName}Change?: (${propName}: boolean) => void;`);
      continue;
    }
    const propValues = propDef.values ?? [];
    // Slot kinds in the contract:
    //  - Atomic-root slot (e.g. Button's `iconStart`): renderable child.
    //    Contract emits `unknown`; React widens to ReactNode, Vue maps to
    //    a named slot via `defineSlots`.
    //  - Composite-part slot (e.g. Tooltip's `text` on the `content` part):
    //    scalar body content (string in the contract). React + Vue wrappers
    //    use the same scalar type.
    // The `__part` marker (set by flattenSpec) distinguishes the two: empty
    // string for atomic-root props, the originating part name for composite.
    // `__part` is "" for atomic-root props (set by flattenSpec) and the
    // originating part name for composite. Tests that bypass flatten see
    // `undefined`; treat both empty and missing as the atomic-root case.
    const isAtomicSlot = propDef.slot === true && !propDef.__part;
    const baseType = isAtomicSlot
      ? "unknown"
      : propValues.length > 0
        ? `${Name}${pascalCase(propName)}`
        : mapPropType(propDef.type);
    const tsType =
      propDef.responsive === true && propDef.slot !== true ? responsiveType(baseType) : baseType;
    if (propDef.description) propLines.push(`  /** ${propDef.description} */`);
    propLines.push(`  ${propName}?: ${tsType};`);
  }

  lines.push(`export type ${Name}Props = {`);
  for (const line of propLines) lines.push(line);
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

async function loadFlatSpec(name: string): Promise<FlatSpec> {
  const path = resolve(SPECS_DIR, `${name}.yaml`);
  const raw = await readFile(path, "utf8");
  const parsed = parseYaml(raw);
  const result = SpecSchema.safeParse(parsed);
  if (!result.success) {
    const messages = result.error.issues
      .map((i) => `  ${i.path.join(".")}: ${i.message}`)
      .join("\n");
    throw new Error(`spec ${name}.yaml failed schema validation:\n${messages}`);
  }
  if (result.data.name !== name) {
    throw new Error(`spec name "${result.data.name}" in ${name}.yaml does not match file basename`);
  }
  return flattenSpec(result.data);
}

async function listSpecNames(): Promise<string[]> {
  const entries = await readdir(SPECS_DIR);
  return entries
    .filter((f) => f.endsWith(".yaml") && !f.startsWith("_"))
    .map((f) => f.slice(0, -5))
    .sort();
}

async function emitContract(name: string): Promise<string> {
  const spec = await loadFlatSpec(name);
  const content = renderContract(spec);
  const outPath = resolve(CONTRACT_SRC_DIR, `${pascalCase(name)}.ts`);
  await mkdir(CONTRACT_SRC_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

function renderResponsiveModule(breakpoints: string[]): string {
  const keys = ["base", ...breakpoints].map(quote).join(" | ");
  return `// AUTOGENERATED by gen-contract. Do not edit.

type Breakpoint = ${keys};

export type Responsive<T> = T | Partial<Record<Breakpoint, T>>;
`;
}

async function emitResponsiveModule(breakpoints: string[]): Promise<string> {
  const content = renderResponsiveModule(breakpoints);
  const outPath = resolve(CONTRACT_SRC_DIR, "_responsive.ts");
  await mkdir(CONTRACT_SRC_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

function renderReadme(specs: FlatSpec[]): string {
  const componentList = specs
    .map((spec) => {
      const Name = pascalCase(spec.name);
      const exports: string[] = [];
      if (spec.variants) exports.push(`\`${Name}Variant\``);
      if (spec.intents) exports.push(`\`${Name}Intent\``);
      if (spec.sizes) exports.push(`\`${Name}Size\``);
      exports.push(`\`${Name}Props\``);
      return `- \`${Name}\` — ${exports.join(", ")}`;
    })
    .join("\n");

  const firstSpec = specs[0];
  const exampleName = firstSpec ? pascalCase(firstSpec.name) : "Button";

  return `<!-- AUTOGENERATED by gen-contract. Do not edit. -->

# @teseor/contract

Framework-agnostic TypeScript type contracts for Teseor components. Generated from \`specs/*.yaml\`.

The React wrapper (\`@teseor/react\`) inlines its own type unions for self-containment; this package is the canonical type surface for consumers integrating Teseor in non-React TypeScript codebases (or in framework-agnostic tooling).

## Install

\`\`\`
pnpm add @teseor/contract
\`\`\`

## Usage

\`\`\`ts
import type { ${exampleName}Props } from "@teseor/contract/${exampleName}.ts";

function buildAttrs(props: ${exampleName}Props): Record<string, string | undefined> {
  return { "data-variant": props.variant, "data-intent": props.intent };
}
\`\`\`

## Types

${componentList}

## Generated content

Files in \`src/\` are autogenerated from \`specs/*.yaml\`. Do not edit them. The generator is \`scripts/codegen/src/generators/gen-contract.ts\`.
`;
}

async function emitReadme(specs: FlatSpec[]): Promise<string> {
  const content = renderReadme(specs);
  const outPath = resolve(REPO_ROOT, "packages", "contract", "README.md");
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function contractGenerator(ctx: GeneratorContext): Promise<GeneratorReport> {
  const requested = ctx.positionals[0];
  const allNames = await listSpecNames();
  const targets = requested ? [requested] : allNames;

  const filesWritten: string[] = [];
  const notes: string[] = [];
  for (const name of targets) {
    const path = await emitContract(name);
    filesWritten.push(path);
    notes.push(`contract: ${name} -> ${path.replace(`${REPO_ROOT}/`, "")}`);
  }

  const breakpoints = await loadBreakpoints();
  const responsivePath = await emitResponsiveModule(breakpoints);
  filesWritten.push(responsivePath);
  notes.push(`contract: responsive module -> ${responsivePath.replace(`${REPO_ROOT}/`, "")}`);

  const allSpecs = await Promise.all(allNames.map(loadFlatSpec));
  const readmePath = await emitReadme(allSpecs);
  filesWritten.push(readmePath);
  notes.push(`contract: readme -> ${readmePath.replace(`${REPO_ROOT}/`, "")}`);

  return { filesWritten, notes };
}

registerGenerator("contract", contractGenerator);

export { loadFlatSpec, renderContract, renderResponsiveModule };
