import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";
import type { GeneratorContext, GeneratorReport } from "../registry.ts";
import { registerGenerator } from "../registry.ts";
import type { Spec, SpecProp } from "./gen-contract.ts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const SPECS_DIR = resolve(REPO_ROOT, "specs");
const FIXTURES_DIR = resolve(REPO_ROOT, "apps", "harness", "src", "fixtures");
const TESTS_DIR = resolve(REPO_ROOT, "tests", "contract");

function pascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((part) => (part.length === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function jsLiteral(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "string") return quote(value);
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return `[${value.map(jsLiteral).join(", ")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${quote(k)}: ${jsLiteral(v)}`,
    );
    return `{ ${entries.join(", ")} }`;
  }
  return "undefined";
}

function jsxAttr(name: string, value: unknown): string {
  if (typeof value === "string") return ` ${name}=${quote(value)}`;
  if (typeof value === "boolean") return value ? ` ${name}` : ` ${name}={false}`;
  if (typeof value === "number") return ` ${name}={${value}}`;
  return ` ${name}={${jsLiteral(value)}}`;
}

function splitProps(
  spec: Spec,
  exampleProps: Record<string, unknown>,
): { regular: Array<[string, unknown]>; slots: Array<[string, string]> } {
  const regular: Array<[string, unknown]> = [];
  const slots: Array<[string, string]> = [];
  const specProps = spec.props ?? {};
  for (const [name, value] of Object.entries(exampleProps)) {
    const def: SpecProp | undefined = specProps[name];
    if (def?.slot === true) {
      slots.push([name, String(value)]);
    } else {
      regular.push([name, value]);
    }
  }
  return { regular, slots };
}

function renderReactFixtureBody(
  spec: Spec,
  Name: string,
  exampleProps: Record<string, unknown>,
): string {
  const { regular, slots } = splitProps(spec, exampleProps);
  const attrString = regular.map(([n, v]) => jsxAttr(n, v)).join("");
  const slotAttrs = slots.map(([n, v]) => ` ${n}={SLOT(${quote(v)})}`).join("");
  return `<${Name}${attrString}${slotAttrs}>{LABEL}</${Name}>`;
}

function renderVueFixtureBody(
  spec: Spec,
  Name: string,
  exampleProps: Record<string, unknown>,
): string {
  const { regular, slots } = splitProps(spec, exampleProps);
  const propEntries = regular.map(([n, v]) => `${quote(n)}: ${jsLiteral(v)}`);
  const propsObj = propEntries.length === 0 ? "{}" : `{ ${propEntries.join(", ")} }`;
  const slotEntries = ["default: LABEL", ...slots.map(([n, v]) => `${n}: SLOT(${quote(v)})`)];
  const slotsObj = `{ ${slotEntries.join(", ")} }`;
  return `h(${Name}, ${propsObj}, ${slotsObj})`;
}

function hasSlotProps(spec: Spec): boolean {
  return Object.values(spec.props ?? {}).some((def) => def.slot === true);
}

function renderReactFixtureFile(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const examples = spec.examples ?? [];
  const entries = examples
    .filter((e): e is { id: string; props?: Record<string, unknown> } => typeof e.id === "string")
    .map((e) => {
      const body = renderReactFixtureBody(spec, Name, e.props ?? {});
      return `  ${quote(e.id)}: () => ${body},`;
    })
    .join("\n");
  const slotHelper = hasSlotProps(spec)
    ? `const SLOT = (name: string): ReactNode => <span data-fixture-slot={name} />;\n`
    : "";
  return `// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/${spec.name}.yaml

import { ${Name} } from "@teseor/react";
import type { ReactNode } from "react";

${slotHelper}const LABEL = "Label";

export const fixtures: Record<string, () => ReactNode> = {
${entries}
};
`;
}

function renderVueFixtureFile(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const examples = spec.examples ?? [];
  const entries = examples
    .filter((e): e is { id: string; props?: Record<string, unknown> } => typeof e.id === "string")
    .map((e) => {
      const body = renderVueFixtureBody(spec, Name, e.props ?? {});
      return `  ${quote(e.id)}: () => ${body},`;
    })
    .join("\n");
  const slotHelper = hasSlotProps(spec)
    ? `const SLOT = (name: string) => () => h("span", { "data-fixture-slot": name });\n`
    : "";
  return `// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/${spec.name}.yaml

import { h, type VNode } from "vue";
import { ${Name} } from "@teseor/vue";

${slotHelper}const LABEL = () => "Label";

export const fixtures: Record<string, () => VNode> = {
${entries}
};
`;
}

function renderReactBarrel(names: string[]): string {
  const imports = names
    .map((n) => `import { fixtures as ${n}Fixtures } from "./${pascalCase(n)}.react.tsx";`)
    .join("\n");
  const entries = names.map((n) => `  ${n}: ${n}Fixtures,`).join("\n");
  return `// AUTOGENERATED by gen-tests. Do not edit.

import type { ReactNode } from "react";
${imports}

export const reactFixtures: Record<string, Record<string, () => ReactNode>> = {
${entries}
};
`;
}

function renderVueBarrel(names: string[]): string {
  const imports = names
    .map((n) => `import { fixtures as ${n}Fixtures } from "./${pascalCase(n)}.vue.ts";`)
    .join("\n");
  const entries = names.map((n) => `  ${n}: ${n}Fixtures,`).join("\n");
  return `// AUTOGENERATED by gen-tests. Do not edit.

import type { VNode } from "vue";
${imports}

export const vueFixtures: Record<string, Record<string, () => VNode>> = {
${entries}
};
`;
}

function renderSpecFile(spec: Spec): string {
  const rootClass = spec.rootClass ?? `t-${spec.name}`;
  const ids = (spec.examples ?? [])
    .map((e) => e.id)
    .filter((id): id is string => typeof id === "string");
  const idList = ids.map((id) => `  ${quote(id)},`).join("\n");
  return `// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/${spec.name}.yaml

import { expect, test } from "@playwright/test";

const ROOT_CLASS = ${quote(rootClass)};
const COMPONENT = ${quote(spec.name)};

const FIXTURE_IDS = [
${idList}
] as const;

async function capture(
  page: import("@playwright/test").Page,
  framework: "react" | "vue",
  fixture: string,
): Promise<string> {
  await page.goto(\`/\${framework}/\${COMPONENT}?fixture=\${fixture}\`);
  await page.locator(\`.\${ROOT_CLASS}\`).first().waitFor({ state: "attached" });
  return page.evaluate((selector) => {
    function canon(el: Element): string {
      const tag = el.tagName.toLowerCase();
      const attrs = Array.from(el.attributes)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((a) => {
          const v = a.value.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
          return \`\${a.name}="\${v}"\`;
        })
        .join(" ");
      const open = attrs ? \`<\${tag} \${attrs}>\` : \`<\${tag}>\`;
      const close = \`</\${tag}>\`;
      const children = Array.from(el.childNodes)
        .map((node) => {
          if (node.nodeType === 1) return canon(node as Element);
          if (node.nodeType === 3) {
            const text = node.textContent ?? "";
            return text.trim() === "" ? "" : text;
          }
          return "";
        })
        .join("");
      return \`\${open}\${children}\${close}\`;
    }
    const root = document.querySelector(selector);
    if (!root) throw new Error(\`harness: selector "\${selector}" not found\`);
    return canon(root);
  }, \`.\${ROOT_CLASS}\`);
}

for (const id of FIXTURE_IDS) {
  test(\`\${COMPONENT} "\${id}" — React and Vue render identical DOM\`, async ({ page }) => {
    const reactHtml = await capture(page, "react", id);
    const vueHtml = await capture(page, "vue", id);
    expect(vueHtml).toBe(reactHtml);
  });
}

test(\`\${COMPONENT} — combined DOM snapshot\`, async ({ page }) => {
  const sections: string[] = [];
  for (const id of FIXTURE_IDS) {
    const reactHtml = await capture(page, "react", id);
    sections.push(\`<!-- \${id} -->\\n\${reactHtml}\`);
  }
  expect(\`\${sections.join("\\n\\n")}\\n\`).toMatchSnapshot(\`\${COMPONENT}.html\`);
});
`;
}

async function loadSpec(name: string): Promise<Spec> {
  const path = resolve(SPECS_DIR, `${name}.yaml`);
  const raw = await readFile(path, "utf8");
  const parsed = parseYaml(raw) as Spec;
  if (parsed.name !== name) {
    throw new Error(`spec name "${parsed.name}" in ${name}.yaml does not match file basename`);
  }
  return parsed;
}

async function listSpecNames(): Promise<string[]> {
  const entries = await readdir(SPECS_DIR);
  return entries
    .filter((f) => f.endsWith(".yaml") && !f.startsWith("_"))
    .map((f) => f.slice(0, -5))
    .sort();
}

async function emitReactFixtures(spec: Spec): Promise<string> {
  const content = renderReactFixtureFile(spec);
  const outPath = resolve(FIXTURES_DIR, `${pascalCase(spec.name)}.react.tsx`);
  await mkdir(FIXTURES_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitVueFixtures(spec: Spec): Promise<string> {
  const content = renderVueFixtureFile(spec);
  const outPath = resolve(FIXTURES_DIR, `${pascalCase(spec.name)}.vue.ts`);
  await mkdir(FIXTURES_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitReactBarrel(names: string[]): Promise<string> {
  const content = renderReactBarrel(names);
  const outPath = resolve(FIXTURES_DIR, "index.react.ts");
  await mkdir(FIXTURES_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitVueBarrel(names: string[]): Promise<string> {
  const content = renderVueBarrel(names);
  const outPath = resolve(FIXTURES_DIR, "index.vue.ts");
  await mkdir(FIXTURES_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function emitSpec(spec: Spec): Promise<string> {
  const content = renderSpecFile(spec);
  const outPath = resolve(TESTS_DIR, `${spec.name}.spec.ts`);
  await mkdir(TESTS_DIR, { recursive: true });
  await writeFile(outPath, content, "utf8");
  return outPath;
}

async function testsGenerator(ctx: GeneratorContext): Promise<GeneratorReport> {
  const requested = ctx.positionals[0];
  const allNames = await listSpecNames();
  const targets = requested ? [requested] : allNames;

  const filesWritten: string[] = [];
  const notes: string[] = [];

  for (const name of targets) {
    const spec = await loadSpec(name);

    const reactPath = await emitReactFixtures(spec);
    filesWritten.push(reactPath);
    notes.push(`tests: ${name} react fixtures -> ${reactPath.replace(`${REPO_ROOT}/`, "")}`);

    const vuePath = await emitVueFixtures(spec);
    filesWritten.push(vuePath);
    notes.push(`tests: ${name} vue fixtures -> ${vuePath.replace(`${REPO_ROOT}/`, "")}`);

    const specPath = await emitSpec(spec);
    filesWritten.push(specPath);
    notes.push(`tests: ${name} spec -> ${specPath.replace(`${REPO_ROOT}/`, "")}`);
  }

  const reactBarrelPath = await emitReactBarrel(allNames);
  filesWritten.push(reactBarrelPath);
  notes.push(`tests: react barrel -> ${reactBarrelPath.replace(`${REPO_ROOT}/`, "")}`);

  const vueBarrelPath = await emitVueBarrel(allNames);
  filesWritten.push(vueBarrelPath);
  notes.push(`tests: vue barrel -> ${vueBarrelPath.replace(`${REPO_ROOT}/`, "")}`);

  return { filesWritten, notes };
}

registerGenerator("tests", testsGenerator);

export {
  renderReactBarrel,
  renderReactFixtureFile,
  renderSpecFile,
  renderVueBarrel,
  renderVueFixtureFile,
};
