import { describe, expect, test } from "vitest";
import type { Spec, SpecProp } from "../../gen-contract.ts";
import { renderAtomicVueWrapper } from "./atomic.ts";

function prop(overrides: Partial<SpecProp> & { type: SpecProp["type"] }): SpecProp {
  return { description: "", __part: "", ...overrides };
}

function atomicSpec(overrides: Partial<Spec> = {}): Spec {
  return {
    name: "button",
    kind: "atomic",
    props: {},
    tokens: {},
    visualStates: {},
    ...overrides,
  };
}

describe("renderAtomicVueWrapper", () => {
  test("opens with the AUTOGENERATED banner and the spec source comment", () => {
    const out = renderAtomicVueWrapper(atomicSpec(), {});
    expect(out).toContain("<!-- AUTOGENERATED by gen-vue. Do not edit. -->");
    expect(out).toContain("<!-- Source: specs/button.yaml -->");
  });

  test("imports the per-component CSS module", () => {
    const out = renderAtomicVueWrapper(atomicSpec(), {});
    expect(out).toContain(`import "@teseor/css/components/button.css";`);
  });

  test("uses the spec's `element` for the root tag when no `as` prop exists", () => {
    const out = renderAtomicVueWrapper(atomicSpec({ element: "span" }), {});
    expect(out).toContain(`<span class="t-button" v-bind="attrs">`);
    expect(out).toContain("</span>");
  });

  test('switches to `<component :is="as">` when an `as` prop is declared', () => {
    const out = renderAtomicVueWrapper(
      atomicSpec({ props: { as: prop({ type: "string", default: "button" }) } }),
      {},
    );
    expect(out).toContain(`<component :is="as" class="t-button" v-bind="attrs">`);
    expect(out).toContain("</component>");
  });

  test("imports the responsive runtime helpers only when there's a responsive prop", () => {
    const noResp = renderAtomicVueWrapper(atomicSpec(), {});
    expect(noResp).not.toContain("responsiveDataAttrs");

    const withResp = renderAtomicVueWrapper(atomicSpec({ sizes: { md: { description: "" } } }), {});
    expect(withResp).toContain(
      `import { type Responsive, responsiveDataAttrs } from "./_runtime.ts";`,
    );
  });

  test("wraps `<slot />` in slotElement when set", () => {
    const out = renderAtomicVueWrapper(
      atomicSpec({ name: "codeblock", element: "pre", slotElement: "code" }),
      {},
    );
    expect(out).toContain("<pre");
    expect(out).toContain("<code>");
    expect(out).toContain("<slot");
    expect(out).toContain("</code>");
  });

  test("omits the slot wrapper when slotElement is unset", () => {
    const out = renderAtomicVueWrapper(atomicSpec({ element: "div" }), {});
    expect(out).not.toContain("<code>");
  });

  describe("polymorphic: 'asChild'", () => {
    test("imports Slot, adds the asChild prop, and switches root via `:is`", () => {
      const out = renderAtomicVueWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toContain(`import { Slot } from "./components/Slot.ts";`);
      expect(out).toContain("asChild?: boolean;");
      expect(out).toContain(
        `<component :is="asChild ? Slot : 'div'" class="t-button" v-bind="attrs">`,
      );
      expect(out).toContain("</component>");
    });

    test("includes asChild in the defineProps destructure", () => {
      const out = renderAtomicVueWrapper(
        atomicSpec({ element: "div", polymorphic: "asChild" }),
        {},
      );
      expect(out).toMatch(/const\s*\{[^}]*\basChild\b[^}]*\}\s*=\s*defineProps/s);
    });

    test("omits Slot import and asChild prop when polymorphic is unset", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain(`import { Slot }`);
      expect(out).not.toContain("asChild?: boolean;");
    });
  });

  describe("elementByProp", () => {
    function headingSpec(extra: Partial<Spec> = {}): Spec {
      return atomicSpec({
        name: "heading",
        elementByProp: {
          prop: "level",
          map: { "1": "h1", "2": "h2", "3": "h3" },
        },
        props: {
          level: prop({ type: "string", values: ["1", "2", "3"], default: "1" }),
        },
        ...extra,
      });
    }

    test("emits a tagMap constant and a `:is` expression keyed by the prop", () => {
      const out = renderAtomicVueWrapper(headingSpec(), {});
      expect(out).toContain(`const tagMap = { "1": "h1", "2": "h2", "3": "h3" } as const;`);
      expect(out).toContain(`<component :is="tagMap[level ?? '1']"`);
      expect(out).toContain("</component>");
    });

    test("falls back to the first map key when the prop has no `default`", () => {
      const out = renderAtomicVueWrapper(
        headingSpec({
          props: {
            level: prop({ type: "string", values: ["1", "2", "3"] }),
          },
        }),
        {},
      );
      expect(out).toContain(`<component :is="tagMap[level ?? '1']"`);
    });

    test("composes with `polymorphic: 'asChild'`", () => {
      const out = renderAtomicVueWrapper(headingSpec({ polymorphic: "asChild" }), {});
      expect(out).toContain(`const tagMap =`);
      expect(out).toContain(`<component :is="asChild ? Slot : tagMap[level ?? '1']"`);
    });

    test("omits tagMap when elementByProp is unset", () => {
      const out = renderAtomicVueWrapper(atomicSpec({ element: "div" }), {});
      expect(out).not.toContain("const tagMap");
    });

    describe("mixed elementByProp.map (void + non-void)", () => {
      function dividerSpec(extra: Partial<Spec> = {}): Spec {
        return atomicSpec({
          name: "divider",
          elementByProp: {
            prop: "orientation",
            map: { horizontal: "hr", vertical: "div" },
          },
          props: {
            orientation: prop({
              type: "string",
              values: ["horizontal", "vertical"],
              default: "horizontal",
            }),
          },
          ...extra,
        });
      }

      test("emits resolvedTag + isVoidResolved computeds derived from the tagMap", () => {
        const out = renderAtomicVueWrapper(dividerSpec(), {});
        expect(out).toContain(`const tagMap = { "horizontal": "hr", "vertical": "div" } as const;`);
        expect(out).toContain(
          `const resolvedTag = computed(() => tagMap[orientation ?? 'horizontal']);`,
        );
        expect(out).toContain(`const isVoidResolved = computed(() => resolvedTag.value === 'hr');`);
      });

      test("branches the template on isVoidResolved with v-if / v-else", () => {
        const out = renderAtomicVueWrapper(dividerSpec(), {});
        expect(out).toContain(`<template v-if="isVoidResolved">`);
        expect(out).toContain(`<template v-else>`);
        expect(out).toContain(`<component :is="resolvedTag" class="t-divider" v-bind="attrs" />`);
        expect(out).toContain(`<component :is="resolvedTag" class="t-divider" v-bind="attrs">`);
        expect(out).toContain("</component>");
      });

      test("guards asChild on the non-void branch so Slot never wraps a void tag", () => {
        const out = renderAtomicVueWrapper(dividerSpec({ polymorphic: "asChild" }), {});
        expect(out).toContain(`asChild && !isVoidResolved ? Slot : resolvedTag`);
      });
    });

    describe("boolean state props", () => {
      test("emits a `data-{name}` entry on the attrs object for boolean state props", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            element: "div",
            props: {
              decorative: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).toContain(`"data-decorative": decorative ? "true" : undefined,`);
      });

      test("does not emit a data-* entry for the elementByProp controlling prop", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            elementByProp: {
              prop: "ordered",
              map: { false: "ul", true: "ol" },
            },
            props: {
              ordered: prop({ type: "boolean", description: "" }),
            },
          }),
          {},
        );
        expect(out).not.toContain(`"data-ordered":`);
      });
    });

    describe("a11y emission", () => {
      test("emits a static role on the root from spec.a11y.role", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({ element: "div", a11y: { role: "separator" } }),
          {},
        );
        expect(out).toContain(`role: "separator",`);
      });

      test('forwards each ariaProps entry as `"aria-{prop}": prop`', () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            element: "div",
            props: {
              orientation: prop({
                type: "string",
                values: ["horizontal", "vertical"],
                responsive: false,
                description: "",
              }),
            },
            a11y: { ariaProps: ["orientation"] },
          }),
          {},
        );
        expect(out).toContain(`"aria-orientation": orientation,`);
      });

      test("toggles role to none and adds aria-hidden when decorativeProp is set", () => {
        const out = renderAtomicVueWrapper(
          atomicSpec({
            element: "div",
            props: { decorative: prop({ type: "boolean", description: "" }) },
            a11y: { role: "separator", decorativeProp: "decorative" },
          }),
          {},
        );
        expect(out).toContain(`role: decorative ? "none" : "separator",`);
        expect(out).toContain(`"aria-hidden": decorative ? "true" : undefined,`);
      });
    });
  });
});
