import type { FlatItemProp, FlatRepeatingPart } from "../../../lib/flatten.ts";
import { renderComponentJsDoc, vueJsDocFlavor } from "../../../lib/jsdoc-shape.ts";
import { pascalCase } from "../../../lib/pascal-case.ts";
import type { Spec } from "../../gen-contract.ts";

/**
 * Emits a Vue SFC for a composite spec that uses repeating parts (RFC-0005)
 * and has no `overlay:` block. Shape is one non-repeating wrapper part + one
 * or more repeating parts rendered as its direct children via `v-for`.
 *
 * Parts sharing the same `groupKey:` are interleaved into a single `v-for`
 * loop over a `<template>` element. Ungrouped repeating parts get their own
 * `v-for` directly on the element.
 */
export function renderCompositeListVueWrapper(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const partsMap = spec.parts ?? {};
  const partEntries = Object.entries(partsMap);
  const wrapperEntry = partEntries.find(([, p]) => p.repeating !== true);
  if (!wrapperEntry) {
    throw new Error(
      `composite-list spec '${spec.name}' must declare exactly one non-repeating wrapper part`,
    );
  }
  const [, wrapperPart] = wrapperEntry;
  const wrapperElement = wrapperPart.element ?? "div";
  const wrapperClass = wrapperPart.rootClass ?? `t-${spec.name}`;
  const repeating = spec.repeating ?? [];

  const repeatingGroups = new Map<string, FlatRepeatingPart[]>();
  for (const r of repeating) {
    const g = repeatingGroups.get(r.propName) ?? [];
    g.push(r);
    repeatingGroups.set(r.propName, g);
  }

  const itemTypeBlocks: string[] = [];
  for (const [, group] of repeatingGroups) {
    const first = group[0];
    if (!first) continue;
    const ItemName = itemTypeName(Name, first);
    const mergedItemProps = mergeItemProps(group);
    const fields = [
      `  /** Stable item identity; required. */`,
      `  id: string;`,
      ...mergedItemProps.flatMap(([n, d]) => [
        ...(d.description ? [`  /** ${d.description} */`] : []),
        `  ${n}?: ${mapItemPropType(d)};`,
      ]),
    ].join("\n");
    itemTypeBlocks.push(`export type ${ItemName} = {\n${fields}\n};`);
  }

  // Group-level scalar props from the wrapper / non-repeating parts.
  const groupPropLines: string[] = [];
  for (const [n, d] of Object.entries(spec.props ?? {})) {
    if (d.description) groupPropLines.push(`  /** ${d.description} */`);
    groupPropLines.push(`  ${n}?: ${mapGroupPropType(d)};`);
  }

  const propLines: string[] = [...groupPropLines];
  for (const [propName, group] of repeatingGroups) {
    const first = group[0];
    if (!first) continue;
    const ItemName = itemTypeName(Name, first);
    const partLabel =
      group.length === 1
        ? `\`${first.partName}\``
        : group.map((g) => `\`${g.partName}\``).join(" + ");
    propLines.push(
      `  /** Items rendered by the repeating ${partLabel} part${group.length > 1 ? "s" : ""}. */`,
    );
    propLines.push(`  ${propName}?: ReadonlyArray<${ItemName}>;`);
  }

  const destructureLines: string[] = [];
  for (const [propName] of repeatingGroups) {
    destructureLines.push(`  ${propName} = [],`);
  }
  for (const n of Object.keys(spec.props ?? {})) {
    destructureLines.push(`  ${n},`);
  }

  const iterationBlocks = [...repeatingGroups.entries()].map(([propName, group]) =>
    renderIterationBlock(propName, group),
  );

  // Named ES module exports (`export type …`) are not allowed inside a
  // `<script setup>` block. Emit a sibling `<script lang="ts">` first; its
  // top-level declarations are in scope for the setup block.
  const exportsBlock = `<script lang="ts">
${itemTypeBlocks.join("\n\n")}
</script>

`;

  return `<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/${spec.name}.yaml -->
${exportsBlock}<script setup lang="ts">
${renderComponentJsDoc(spec, Name, vueJsDocFlavor)}
import "@teseor/css/components/${spec.name}.css";

type ${Name}Props = {
${propLines.join("\n")}
};

const {
${destructureLines.join("\n")}
} = defineProps<${Name}Props>();
</script>

<template>
  <${wrapperElement} class="${wrapperClass}">
${iterationBlocks.join("\n")}
  </${wrapperElement}>
</template>
`;
}

function singularize(word: string): string {
  return word.endsWith("s") ? word.slice(0, -1) : word;
}

function itemTypeName(Name: string, part: FlatRepeatingPart): string {
  const base = part.groupKey ? singularize(part.groupKey) : part.partName;
  const basePascal = pascalCase(base);
  return basePascal.toLowerCase() === "item" ? `${Name}Item` : `${Name}${basePascal}Item`;
}

function mergeItemProps(group: FlatRepeatingPart[]): Array<[string, FlatItemProp]> {
  const merged: Array<[string, FlatItemProp]> = [];
  const seen = new Set<string>();
  for (const part of group) {
    for (const [n, def] of Object.entries(part.itemProps)) {
      if (seen.has(n)) continue;
      seen.add(n);
      merged.push([n, def]);
    }
  }
  return merged;
}

function mapItemPropType(def: FlatItemProp): string {
  const values = def.values ?? [];
  if (values.length > 0) return values.map((v) => `"${v}"`).join(" | ");
  switch (def.type) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function mapGroupPropType(def: { type: string; values?: string[] }): string {
  const values = def.values ?? [];
  if (values.length > 0) return values.map((v) => `"${v}"`).join(" | ");
  switch (def.type) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function renderIterationBlock(propName: string, group: FlatRepeatingPart[]): string {
  if (group.length === 1) {
    const part = group[0];
    if (!part) return "";
    return renderSinglePartLoop(propName, part);
  }
  // Multi-part: wrap each iteration in <template v-for=…>, emit each part
  // inside without its own v-for.
  const inner = group.map((part) => renderItemElement(part, false)).join("\n");
  return `    <template v-for="item in ${propName}" :key="item.id">
${inner}
    </template>`;
}

function renderSinglePartLoop(propName: string, part: FlatRepeatingPart): string {
  const itemElement = part.element ?? "div";
  const itemClass = part.rootClass ?? `t-${part.partName}`;
  const slotEntries = Object.entries(part.itemProps).filter(([, d]) => d.slot === true);
  const attrLines: string[] = [
    `      v-for="item in ${propName}"`,
    `      :key="item.id"`,
    ...(itemElement === "button" ? [`      type="button"`] : []),
    `      class="${itemClass}"`,
    `      :data-id="item.id"`,
  ];
  for (const [n, d] of Object.entries(part.itemProps)) {
    if (d.slot === true) continue;
    if (d.type === "boolean") {
      attrLines.push(`      :data-${n}="item.${n} || undefined"`);
    } else {
      attrLines.push(`      :data-${n}="item.${n}"`);
    }
  }
  const body = slotEntries.length > 0 ? slotEntries.map(([n]) => `{{ item.${n} }}`).join("") : null;
  if (body === null) {
    return `    <${itemElement}\n${attrLines.join("\n")}\n    />`;
  }
  return `    <${itemElement}\n${attrLines.join("\n")}\n    >${body}</${itemElement}>`;
}

function renderItemElement(part: FlatRepeatingPart, includeKey: boolean): string {
  const itemElement = part.element ?? "div";
  const itemClass = part.rootClass ?? `t-${part.partName}`;
  const slotEntries = Object.entries(part.itemProps).filter(([, d]) => d.slot === true);
  const indent = "      ";
  const attrLines: string[] = [
    ...(includeKey ? [`${indent}:key="item.id"`] : []),
    ...(itemElement === "button" ? [`${indent}type="button"`] : []),
    `${indent}class="${itemClass}"`,
    `${indent}:data-id="item.id"`,
  ];
  for (const [n, d] of Object.entries(part.itemProps)) {
    if (d.slot === true) continue;
    if (d.type === "boolean") {
      attrLines.push(`${indent}:data-${n}="item.${n} || undefined"`);
    } else {
      attrLines.push(`${indent}:data-${n}="item.${n}"`);
    }
  }
  const body = slotEntries.length > 0 ? slotEntries.map(([n]) => `{{ item.${n} }}`).join("") : null;
  if (body === null) {
    return `    <${itemElement}\n${attrLines.join("\n")}\n    />`;
  }
  return `    <${itemElement}\n${attrLines.join("\n")}\n    >${body}</${itemElement}>`;
}
