import type { FlatItemProp } from "../../../lib/flatten.ts";
import { renderComponentJsDoc, vueJsDocFlavor } from "../../../lib/jsdoc-shape.ts";
import { pascalCase } from "../../../lib/pascal-case.ts";
import type { Spec } from "../../gen-contract.ts";

/**
 * Emits a Vue SFC for a composite spec that uses repeating parts (RFC-0005,
 * phase 1) and has no `overlay:` block. The phase-1 shape is one
 * non-repeating wrapper part + one or more repeating parts rendered as
 * its direct children via `v-for`.
 */
export function renderCompositeListVueWrapper(spec: Spec): string {
  const Name = pascalCase(spec.name);
  const partsMap = spec.parts ?? {};
  const partEntries = Object.entries(partsMap);
  const wrapperEntry = partEntries.find(([, p]) => p.repeating !== true);
  if (!wrapperEntry) {
    throw new Error(
      `composite-list spec '${spec.name}' must declare exactly one non-repeating wrapper part`,
    );
  }
  const [, wrapperPart] = wrapperEntry;
  const wrapperElement = wrapperPart.element ?? "div";
  const wrapperClass = wrapperPart.rootClass ?? `t-${spec.name}`;
  const repeating = spec.repeating ?? [];

  const itemTypeBlocks = repeating.map((r) => {
    const ItemName = `${Name}${pascalCase(r.partName)}Item`;
    const fields = [
      `  /** Stable item identity; required. */`,
      `  id: string;`,
      ...Object.entries(r.itemProps).flatMap(([n, d]) => [
        ...(d.description ? [`  /** ${d.description} */`] : []),
        `  ${n}?: ${mapItemPropType(d)};`,
      ]),
    ].join("\n");
    return `export type ${ItemName} = {\n${fields}\n};`;
  });

  const propLines = repeating.map(
    (r) =>
      `  /** Items rendered by the repeating \`${r.partName}\` part. */\n  ${r.propName}?: ReadonlyArray<${Name}${pascalCase(r.partName)}Item>;`,
  );

  const destructureLines = repeating.map((r) => `  ${r.propName} = [],`).join("\n");

  const iterationBlocks = repeating.map((r) => renderIterationBlock(Name, r));

  // Named ES module exports (`export type …`) are not allowed inside a
  // `<script setup>` block. The canonical Vue pattern is to emit a sibling
  // plain `<script lang="ts">` block before the setup block — top-level
  // declarations from the plain block are in scope for the setup block.
  const exportsBlock = `<script lang="ts">
${itemTypeBlocks.join("\n\n")}
</script>

`;

  return `<!-- AUTOGENERATED by gen-vue. Do not edit. -->
<!-- Source: specs/${spec.name}.yaml -->
${exportsBlock}<script setup lang="ts">
${renderComponentJsDoc(spec, Name, vueJsDocFlavor)}
import "@teseor/css/components/${spec.name}.css";

type ${Name}Props = {
${propLines.join("\n")}
};

const {
${destructureLines}
} = defineProps<${Name}Props>();
</script>

<template>
  <${wrapperElement} class="${wrapperClass}">
${iterationBlocks.join("\n")}
  </${wrapperElement}>
</template>
`;
}

function mapItemPropType(def: FlatItemProp): string {
  const values = def.values ?? [];
  if (values.length > 0) return values.map((v) => `"${v}"`).join(" | ");
  switch (def.type) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    default:
      return "unknown";
  }
}

function renderIterationBlock(
  _Name: string,
  r: {
    partName: string;
    propName: string;
    element?: string;
    rootClass?: string;
    itemProps: Record<string, FlatItemProp>;
  },
): string {
  const itemElement = r.element ?? "div";
  const itemClass = r.rootClass ?? `t-${r.partName}`;
  const slotEntries = Object.entries(r.itemProps).filter(([, d]) => d.slot === true);
  const attrLines: string[] = [
    `      v-for="item in ${r.propName}"`,
    `      :key="item.id"`,
    `      class="${itemClass}"`,
    `      :data-id="item.id"`,
  ];
  for (const [n, d] of Object.entries(r.itemProps)) {
    if (d.slot === true) continue;
    if (d.type === "boolean") {
      attrLines.push(`      :data-${n}="item.${n} || undefined"`);
    } else {
      attrLines.push(`      :data-${n}="item.${n}"`);
    }
  }
  const body = slotEntries.length > 0 ? slotEntries.map(([n]) => `{{ item.${n} }}`).join("") : null;
  if (body === null) {
    return `    <${itemElement}\n${attrLines.join("\n")}\n    />`;
  }
  return `    <${itemElement}\n${attrLines.join("\n")}\n    >${body}</${itemElement}>`;
}
