import { describe, expect, test } from "vitest";
import { renderBarrel } from "./barrel.ts";

describe("renderBarrel", () => {
  test("starts with the AUTOGENERATED banner", () => {
    expect(renderBarrel([]).split("\n")[0]).toBe("// AUTOGENERATED by gen-vue. Do not edit.");
  });

  test("emits one default re-export per spec name, pascal-cased", () => {
    const out = renderBarrel(["button", "tooltip"]);
    expect(out).toContain(`export { default as Button } from "./Button.vue";`);
    expect(out).toContain(`export { default as Tooltip } from "./Tooltip.vue";`);
  });

  test("converts kebab-case spec names to PascalCase", () => {
    const out = renderBarrel(["icon-button"]);
    expect(out).toContain(`export { default as IconButton } from "./IconButton.vue";`);
  });

  test("ends with a trailing newline", () => {
    expect(renderBarrel(["button"]).endsWith("\n")).toBe(true);
  });
});
