#!/usr/bin/env node
// Forbids `typeof document !== "undefined"` / `typeof window !== "undefined"`
// branches in wrapper component files. Gating JSX on `typeof document` causes
// a hydration mismatch: the server renders the "no" branch, the client's
// first render hits the same `typeof document === "undefined"` truth (it
// hasn't run effects yet), then a later render flips it. The user-facing
// result is a flicker plus a React hydration warning.
//
// The fix is the mounted-flag pattern:
//
//   const [mounted, setMounted] = useState(false);
//   useEffect(() => setMounted(true), []);
//   return mounted ? createPortal(...) : null;
//
// Scope: hand-authored wrapper component files only —
// `packages/{react,vue}/src/**/*.{tsx,vue}`. Generated runtime helpers
// (`_runtime.ts`) and primitives (DOM utilities deliberately ssr-guarded at
// the function boundary, not inside JSX) are out of scope. The check is the
// "don't write this in JSX" rule, not a global typeof ban.
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "..", "..");

// `typeof X !== "undefined"` and the reverse direction. Matches either quote
// style and tolerates whitespace.
const TYPEOF_PATTERN = /\btypeof\s+(document|window)\s*(?:!==?|===?)\s*['"]undefined['"]/g;

type Violation = { file: string; line: number; expression: string };

/** Scan one source for `typeof document|window` SSR-gate expressions. */
export function findTypeofViolations(source: string): { line: number; expression: string }[] {
  const out: { line: number; expression: string }[] = [];
  const lines = source.split("\n");
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    for (const match of line.matchAll(TYPEOF_PATTERN)) {
      out.push({ line: i + 1, expression: match[0] });
    }
  }
  return out;
}

function isInScope(path: string): boolean {
  const rel = relative(REPO_ROOT, resolve(path));
  // `_runtime.ts` is autogenerated and gates `matchMedia` at a function
  // boundary, not inside JSX. Tests can mock environments freely.
  if (rel.includes("_runtime.")) return false;
  if (rel.endsWith(".test.ts") || rel.endsWith(".test.tsx")) return false;
  const wrapperFile = /^packages\/(react|vue)\/src\/.*\.(tsx|vue)$/;
  return wrapperFile.test(rel);
}

function enumerateWrappers(): string[] {
  // `:(glob)` enables `**` recursive matching in the git pathspec. Without
  // it, a bare `*` matches one path segment only and the recursive sweep
  // silently picks up files at depth 1 only.
  const stdout = execSync(
    "git ls-files ':(glob)packages/react/src/**/*.tsx' ':(glob)packages/vue/src/**/*.vue'",
    { cwd: REPO_ROOT, encoding: "utf8" },
  );
  return stdout
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .map((p) => resolve(REPO_ROOT, p))
    .filter(isInScope);
}

function main(): void {
  const argv = process.argv.slice(2);
  const files = argv.length > 0 ? argv.filter(isInScope) : enumerateWrappers();
  const violations: Violation[] = [];
  for (const file of files) {
    let source: string;
    try {
      source = readFileSync(file, "utf8");
    } catch {
      continue;
    }
    for (const { line, expression } of findTypeofViolations(source)) {
      violations.push({ file: relative(REPO_ROOT, resolve(file)), line, expression });
    }
  }
  if (violations.length > 0) {
    const lines = violations.map((v) => `  - ${v.file}:${v.line}  \`${v.expression}\``);
    process.stderr.write(
      `check-no-document-typeof: SSR-gate typeof checks in wrapper JSX:\n${lines.join("\n")}\n\n` +
        "Gating JSX on `typeof document` causes a hydration flicker — the server and\n" +
        "the client's first render both see the same branch, then an effect flips it.\n" +
        "Use the mounted flag instead:\n" +
        "  const [mounted, setMounted] = useState(false);\n" +
        "  useEffect(() => setMounted(true), []);\n" +
        "  return mounted ? createPortal(...) : null;\n",
    );
    process.exit(1);
  }
  process.stdout.write(`check-no-document-typeof: ${files.length} wrapper file(s) clean\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
