import type { Spec } from "../../gen-contract.ts";
import { assertUniqueFixtureIds, coverageFixtures, type TestsSpec } from "../_shared/coverage.ts";
import { quote } from "../_shared/printers.ts";

export function renderSpecFile(spec: Spec): string {
  const rootClass = spec.rootClass ?? `t-${spec.name}`;
  const exampleIds = (spec.examples ?? [])
    .map((e) => e.id)
    .filter((id): id is string => typeof id === "string");
  const coverageIds = coverageFixtures(spec as TestsSpec).map((m) => m.id);
  const allIds = [...exampleIds, ...coverageIds];
  assertUniqueFixtureIds(allIds, spec as TestsSpec);
  const idList = allIds.map((id) => `    ${quote(id)},`).join("\n");
  return `// AUTOGENERATED by gen-tests. Do not edit.
// Source: specs/${spec.name}.yaml

import { defineContractTests } from "./_contract.ts";

defineContractTests({
  component: ${quote(spec.name)},
  rootClass: ${quote(rootClass)},
  fixtureIds: [
${idList}
  ],
});
`;
}
